Repository mapbox/mapbox-gl-js, pull requests merged in 2018-11, with the labels that each got.

#7558 fix shaky sprites on scrollZoom
  src/ui/handler/scroll_zoom.js
  src/ui/map.js
Labels: bug :beetle:

#7590 Update style spec for gl-native's release-horchata
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#7574 Update style spec compatibility tables for Horchata
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:

#7594 Canonicalize tile url
  src/index.js
  src/source/load_tilejson.js
  src/util/mapbox.js
  test/unit/util/mapbox.test.js
Labels: GL native → GL JS, breaking change :warning:

#7604 add validation option to style setters
  src/style/light.js
  src/style/style.js
  src/style/style_layer.js
  src/ui/map.js
  test/unit/style/light.test.js
  test/unit/style/style.test.js
Labels: api :memo:, release blocker :no_entry:

#7641 advance image request queue when request aborted
  src/util/ajax.js
  test/unit/util/ajax.test.js
Labels: release blocker :no_entry:
