Repository mapbox/mapbox-gl-js, pull requests merged in 2018-07, with the labels that each got.

#6917 Limit pitch to 60 degrees in render tests
  test/integration/render-tests/circle-pitch-alignment/map-scale-map/style.json
  test/integration/render-tests/circle-pitch-alignment/map-scale-viewport/style.json
  test/integration/render-tests/circle-pitch-alignment/viewport-scale-map/style.json
  test/integration/render-tests/circle-pitch-alignment/viewport-scale-viewport/style.json
  test/integration/render-tests/circle-pitch-scale/default/style.json
  test/integration/render-tests/circle-pitch-scale/map/style.json
  test/integration/render-tests/circle-pitch-scale/viewport/style.json
  test/integration/render-tests/fill-extrusion-base/default/style.json
  test/integration/render-tests/fill-extrusion-base/function/style.json
  test/integration/render-tests/fill-extrusion-base/literal/style.json
  test/integration/render-tests/fill-extrusion-base/negative/style.json
  test/integration/render-tests/fill-extrusion-base/property-function/style.json
  test/integration/render-tests/fill-extrusion-base/zoom-and-property-function/style.json
  test/integration/render-tests/line-pattern/pitch/style.json
  test/integration/render-tests/regressions/mapbox-gl-js#3548/style.json
Labels: GL native → GL JS, testing :100:

#6988 android-v6.3.0, ios-v4.2.0, macos-v0.9.0 in style spec
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:

#7021 remove Level subclass of DEMData
  src/data/dem_data.js
  src/render/draw_hillshade.js
  src/source/raster_dem_tile_worker_source.js
  test/unit/data/dem_data.test.js
  test/unit/source/raster_dem_tile_worker_source.test.js
Labels: refactoring :building_construction:
