Repository mapbox/mapbox-gl-js, pull requests merged in 2018-04, with the labels that each got.

#6487 fix bug in geolocate control due changes in master since #6205 was authored
  src/ui/control/geolocate_control.js
Labels: release blocker :no_entry:

#6455 Render tests for layer zoom visibility
  test/integration/render-tests/zoom-visibility/above/expected.png
  test/integration/render-tests/zoom-visibility/above/style.json
  test/integration/render-tests/zoom-visibility/below/expected.png
  test/integration/render-tests/zoom-visibility/below/style.json
  test/integration/render-tests/zoom-visibility/in-range/expected.png
  test/integration/render-tests/zoom-visibility/in-range/style.json
  test/integration/render-tests/zoom-visibility/out-of-range/expected.png
  test/integration/render-tests/zoom-visibility/out-of-range/style.json
  test/integration/render-tests/zoom-visibility/was-above/expected.png
  test/integration/render-tests/zoom-visibility/was-above/style.json
  test/integration/render-tests/zoom-visibility/was-below/expected.png
  test/integration/render-tests/zoom-visibility/was-below/style.json
Labels: testing :100:

#6545 Update style spec compat tables for Boba releases
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#6573 List gl-accessibility plugin on plugins page
  docs/pages/plugins.js
Labels: docs :scroll:
