Repository mapbox/mapbox-gl-js, pull requests merged in 2018-09, with the labels that each got.

#7178 Support GL face culling
  src/data/bucket/fill_extrusion_bucket.js
  src/gl/context.js
  src/gl/cull_face_mode.js
  src/gl/types.js
  src/gl/value.js
  src/render/draw_background.js
  src/render/draw_circle.js
  src/render/draw_collision_debug.js
  src/render/draw_debug.js
  src/render/draw_fill.js
  src/render/draw_fill_extrusion.js
  src/render/draw_heatmap.js
  src/render/draw_hillshade.js
  src/render/draw_line.js
  src/render/draw_raster.js
  src/render/draw_symbol.js
  src/render/offscreen.js
  src/render/painter.js
  src/render/program.js
  test/integration/render-tests/fill-extrusion-pattern/@2x/expected.png
  test/integration/render-tests/fill-extrusion-pattern/feature-expression/expected.png
  test/integration/render-tests/fill-extrusion-pattern/function-2/expected.png
  test/integration/render-tests/fill-extrusion-pattern/function/expected.png
  test/integration/render-tests/fill-extrusion-pattern/literal/expected.png
  test/integration/render-tests/fill-extrusion-pattern/opacity/expected.png
Labels: GL native → GL JS, feature :green_apple:, performance :zap:

#7254 cherry-pick: update platform support tables for *-pattern (#7232)
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#7277 make sure the correct style is used for style benchmarks
  bench/styles/benchmarks.js
Labels: workflow :nail_care:

#7282 Document SDK support for line metrics
  docs/pages/style-spec.js
Labels: cross-platform :tv:, docs :scroll:

#7281 [docs] Update SDK compatibility versions for line-gradient
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#7335 Android collator and resolved-locale reference
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:, docs :scroll:
