Repository mapbox/mapbox-gl-js, pull requests merged in 2018-08, with the labels that each got.

#6803 6768 overdraw fix
  src/source/vector_tile_source.js
  test/ajax_stubs.js
  test/ignores.json
  test/integration/render-tests/sparse-tileset/overdraw/expected.png
  test/integration/render-tests/sparse-tileset/overdraw/style.json
  test/integration/tiles/sparse/0-0-0.mvt
Labels: release blocker :no_entry:

#7040 updating example to forward geocoding with custom data
  docs/pages/example/forward-geocode-custom-data.html
  docs/pages/example/forward-geocode-custom-data.js
Labels: docs :scroll:

#7114 [test] Added {basic,bright,satellite}-v9/z0-wide render tests
  test/integration/render-tests/basic-v9/z0-wide/expected.png
  test/integration/render-tests/basic-v9/z0-wide/style.json
  test/integration/render-tests/bright-v9/z0-wide/expected.png
  test/integration/render-tests/bright-v9/z0-wide/style.json
  test/integration/render-tests/satellite-v9/z0-wide/expected.png
  test/integration/render-tests/satellite-v9/z0-wide/style.json
Labels: GL native → GL JS, testing :100:

#7041 Don't default-show text/icons that depend on the placement of a paired icon/text.
  src/symbol/placement.js
  test/integration/render-tests/regressions/mapbox-gl-js#7032/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#7032/style.json
Labels: bug :beetle:

#7129 don't clear state on reload, just on setData
  src/source/source_cache.js
  src/style-spec/types.js
  test/integration/render-tests/feature-state/set-paint-property/expected.png
  test/integration/render-tests/feature-state/set-paint-property/style.json
  test/unit/ui/map.test.js
Labels: bug :beetle:

#7139 android-v6.4.0, ios-v4.4.0, macos-v0.10.0 in style specification
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:, docs :scroll:

#7128 Convert offsetHeight/Width to clientHeight/Width
  src/style-spec/types.js
  src/ui/map.js
  test/suite_implementation.js
  test/unit/ui/hash.test.js
  test/unit/ui/map.test.js
  test/unit/ui/marker.test.js
  test/unit/ui/popup.test.js
  test/util.js
Labels: breaking change :warning:

#6894 Add CameraForBoxAndBearing function
  CHANGELOG.md
  src/ui/camera.js
  src/ui/handler/box_zoom.js
  test/unit/ui/camera.test.js
Labels: feature :green_apple:
