Repository mapbox/mapbox-gl-js, pull requests merged in 2018-06, with the labels that each got.

#6364 add support for GeoJSON attribution
  debug/debug.html
  flow-typed/style-spec.js
  src/source/geojson_source.js
  src/style-spec/reference/v8.json
  test/unit/ui/control/attribution.test.js
Labels: cross-platform :tv:, feature :green_apple:

#6691 Clarify transition type + global transition
  docs/pages/style-spec.js
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#6813 do not reload errored tiles
  src/source/source_cache.js
  test/unit/source/source_cache.test.js
Labels: bug :beetle:

#6411 add raster-resampling raster paint property
  debug/image.html
  src/render/draw_raster.js
  src/style-spec/reference/v8.json
  src/style/style_layer/raster_style_layer_properties.js
  test/README.md
  test/integration/render-tests/image/raster-resampling/expected.png
  test/integration/render-tests/image/raster-resampling/style.json
  test/integration/render-tests/raster-resampling/default/expected.png
  test/integration/render-tests/raster-resampling/default/style.json
  test/integration/render-tests/raster-resampling/function/expected.png
  test/integration/render-tests/raster-resampling/function/style.json
  test/integration/render-tests/raster-resampling/literal/expected.png
  test/integration/render-tests/raster-resampling/literal/style.json
Labels: cross-platform :tv:, feature :green_apple:

#6887 List expression-jamsession on plugins page
  docs/pages/plugins.js
Labels: docs :scroll:
