Repository mapbox/mapbox-gl-js, pull requests merged in 2018-03, with the labels that each got.

#6259 [test] Back to URL transform in HTTP server
  test/integration/lib/harness.js
  test/integration/lib/server.js
  test/integration/render-tests/basic-v9/z0/style.json
  test/integration/render-tests/bright-v9/z0/style.json
  test/integration/render-tests/mixed-zoom/z10-z11/style.json
  test/integration/render-tests/real-world/bangkok/style.json
  test/integration/render-tests/real-world/chicago/style.json
  test/integration/render-tests/real-world/nepal/style.json
  test/integration/render-tests/real-world/norway/style.json
  test/integration/render-tests/real-world/sanfrancisco/style.json
  test/integration/render-tests/real-world/uruguay/style.json
  test/integration/render-tests/satellite-v9/z0/style.json
  test/integration/sprites/mapbox/basic-v9.json
  test/integration/sprites/mapbox/basic-v9.png
  test/integration/sprites/mapbox/bright-v9.json
  test/integration/sprites/mapbox/bright-v9.png
  test/integration/sprites/mapbox/satellite-v9.json
  test/integration/sprites/mapbox/satellite-v9.png
  test/integration/styles/bangkok.json
  test/integration/styles/chicago.json
  test/integration/styles/nepal.json
  test/integration/styles/norway.json
  test/integration/styles/sanfrancisco.json
  test/integration/styles/uruguay.json
  test/integration/tilesets/mapbox.mapbox-streets-v7
  test/integration/tilesets/mapbox.satellite
  test/suite_implementation.js
Labels: cross-platform

#6371 Merge StyleExpressionWithErrorHandling into StyleExpression
  src/style-spec/expression/index.js
  src/style-spec/style-spec.js
  src/util/web_worker_transfer.js
  test/expression.test.js
Labels: refactoring :building_construction:

#6408 Fix link to filters in style spec reference
  docs/pages/style-spec.js
Labels: docs :scroll:

#6425 Round-trip linear interpolators
  test/integration/expression-tests/heatmap-density/basic/test.json
  test/integration/expression-tests/interpolate/linear-color/test.json
  test/integration/expression-tests/interpolate/linear-many-stops/test.json
  test/integration/expression-tests/interpolate/linear/test.json
  test/integration/expression-tests/let/zoom/test.json
  test/integration/expression-tests/zoom/basic/test.json
  test/integration/expression-tests/zoom/nested-coalesce/test.json
  test/integration/expression-tests/zoom/nested-let/test.json
Labels: bug :beetle:, cross-platform :tv:, testing :100:

#6427 to-rgba of rgba serializes as a literal
  test/integration/expression-tests/to-rgba/zero/test.json
Labels: cross-platform :tv:, testing :100:
