Repository mapbox/mapbox-gl-js, pull requests merged in 2018-10, with the labels that each got.

#7355 make sure worker sends response after reloading 'empty' tile
  src/source/vector_tile_worker_source.js
  test/unit/source/vector_tile_worker_source.test.js
Labels: bug :beetle:

#7381 send correct timestamp with turnstile event
  src/util/mapbox.js
  test/unit/util/mapbox.test.js
Labels: bug :beetle:

#7393 gazpacho backport: send correct timestamp with turnstile event
  src/util/mapbox.js
  test/unit/util/mapbox.test.js
Labels: release blocker :no_entry:

#7392 gazpacho backport: Show IE11 compact attribution
  src/css/mapbox-gl.css
Labels: release blocker :no_entry:

#7408 avoid SecurityError in IE for custom layers example
  docs/pages/example/custom-style-layer.html
Labels: release blocker :no_entry:

#7409 gazpacho backport: fix custom layers example in IE
  docs/pages/example/custom-style-layer.html
Labels: release blocker :no_entry:

#7413 Don't use gl_PointSize, since it sometimes crashes in Edge
  docs/pages/example/custom-style-layer.html
  docs/pages/example/custom-style-layer.js
Labels: bug :beetle:, environment-specific :desktop_computer:, release blocker :no_entry:

#7414 Don't use gl_PointSize, since it sometimes crashes in Edge
  docs/pages/example/custom-style-layer.html
  docs/pages/example/custom-style-layer.js
Labels: bug :beetle:, environment-specific :desktop_computer:

#7420 add RTL plugin to rich text label example
  docs/pages/example/display-and-style-rich-text-labels.html
Labels: docs :scroll:

#7442 deregister marker mouseup and touchend when removing marker
  src/ui/marker.js
  test/unit/ui/marker.test.js
Labels: bug :beetle:
