Repository mapbox/mapbox-gl-js, pull requests merged in 2019-08, with the labels that each got.

#8550 Document type constrain on feature.id for feature state methods.
  src/style-spec/reference/v8.json
  src/ui/map.js
Labels: skip changelog

#8592 Document type constrain on feature.id for feature state methods
  src/style-spec/reference/v8.json
  src/ui/map.js
Labels: skip changelog

#8586 Move esm to devDependencies
  package.json
Labels: skip changelog

#8631 Document `clearStorage` compatibility
  src/index.js
Labels: skip changelog

#8633 Improve cancellation of tile loads
  src/source/canvas_source.js
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/raster_dem_tile_source.js
  src/source/raster_tile_source.js
  src/source/source.js
  src/source/source_cache.js
  src/source/tile.js
  src/source/vector_tile_source.js
  src/source/video_source.js
  src/source/worker_source.js
  src/util/actor.js
  src/util/dispatcher.js
  src/util/tile_request_cache.js
  test/unit/source/geojson_source.test.js
  test/unit/source/query_features.test.js
  test/unit/source/source_cache.test.js
  test/unit/source/vector_tile_source.test.js
  test/unit/util/actor.test.js
Labels: needs changelog

#8673 Use MessageChannel instead of setTimeout to avoid processing delays
  debug/animate.html
  src/util/actor.js
  src/util/throttled_invoker.js
Labels: bug :beetle:, release blocker :no_entry:, skip changelog

#8694 DEMData: save one CPU copy and do decode on GPU
  src/data/dem_data.js
  src/render/draw_hillshade.js
  src/render/program/hillshade_program.js
  src/shaders/hillshade_prepare.fragment.glsl
  src/source/raster_dem_tile_source.js
  src/util/browser.js
  test/ajax_stubs.js
  test/unit/data/dem_data.test.js
Labels: performance :zap:

#8659 Fix icon/text collisionBox translation
  CHANGELOG.md
  src/data/bucket/symbol_bucket.js
  src/render/draw_collision_debug.js
  src/render/draw_symbol.js
  src/symbol/placement.js
  test/integration/render-tests/debug/collision-icon-text-line-translate/expected.png
  test/integration/render-tests/debug/collision-icon-text-line-translate/style.json
  test/integration/render-tests/debug/collision-icon-text-point-translate/expected.png
  test/integration/render-tests/debug/collision-icon-text-point-translate/style.json
  test/integration/render-tests/debug/collision/expected.png
Labels: needs changelog

#8708 Use randomly generated task IDs to avoid collisions when receiving messages from multiple workers
  src/util/actor.js
Labels: bug :beetle:, release blocker :no_entry:
