Repository mapbox/mapbox-gl-js, pull requests merged in 2019-12, with the labels that each got.

#9052 Reset internal attribution control cache when removing from map
  src/ui/control/attribution_control.js
  test/unit/ui/control/attribution.test.js
Labels: bug :beetle:, needs changelog

#9050 optimize findLoadedParent
  src/source/source_cache.js
  src/source/tile_cache.js
  src/source/tile_id.js
Labels: performance :zap:

#9045 make stretchable images work with icon-text-fit: none
  src/data/bucket/symbol_bucket.js
  src/symbol/quads.js
  src/symbol/symbol_layout.js
  test/integration/render-tests/icon-image/stretchable-content/expected.png
  test/integration/render-tests/icon-image/stretchable-content/style.json
  test/integration/render-tests/icon-image/stretchable/expected.png
  test/integration/render-tests/icon-image/stretchable/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-just-height/expected.png
  test/integration/render-tests/icon-text-fit/stretch-nine-part-just-height/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-just-width/expected.png
  test/integration/render-tests/icon-text-fit/stretch-nine-part-just-width/style.json
Labels: bug :beetle:

#9084 Fix `versions` benchmark not being able to fetch latest release
  bench/versions/index.html
Labels: workflow :nail_care:

#8845 ImageBitmap and OffscreenCanvas for DEM tiles
  bench/benchmarks/hillshade_load.js
  bench/lib/create_map.js
  bench/versions/benchmarks.js
  flow-typed/offscreen-canvas.js
  src/source/image_source.js
  src/source/raster_dem_tile_source.js
  src/source/raster_dem_tile_worker_source.js
  src/source/worker_source.js
  src/util/ajax.js
  src/util/offscreen_canvas_supported.js
  src/util/web_worker_transfer.js
Labels: performance :zap:

#9073 Fix validation error messages in the browser
  src/source/video_source.js
  src/style-spec/error/parsing_error.js
  src/style-spec/error/validation_error.js
  src/util/evented.js
  test/unit/style-spec/validate.test.js
  test/unit/style-spec/validate_mapbox_api_supported.test.js
Labels: bug :beetle:

#9106 fix map-design-team tag in PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip changelog

#9102 Remove reference to 'deprecated in expression'
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#9103 Add check for ImageBitmap type for texture uploads
  src/render/texture.js
Labels: bug :beetle:, skip changelog

#9105 Un-hardcode test fixtures root path for fixture builder
  test/integration/lib/generate-fixture-json.js
  test/integration/lib/operation-handlers.js
  test/integration/testem.js
Labels: skip changelog, workflow :nail_care:

#9110 Typo in style spec
  src/style-spec/reference/v8.json
Labels: skip changelog

#9091 Fix lazy load of RTL text plugin on GeoJSON sources
  src/data/bucket/symbol_bucket.js
  src/source/rtl_text_plugin.js
  src/source/tile.js
  src/source/vector_tile_source.js
  test/unit/data/symbol_bucket.test.js
  test/unit/source/tile.test.js
  test/util/create_symbol_layer.js
Labels: bug :beetle:

#9099 Add sdk-support section for `is-supported-script`
  src/style-spec/reference/v8.json
  test/unit/style-spec/spec.test.js
Labels: skip changelog

#9122 Fix CSP errors caused by using a blobURL to load the rtl-text-plugin
  src/source/rtl_text_plugin.js
  src/source/worker.js
  src/style/style.js
  test/unit/style/style.test.js
Labels: bug :beetle:, release blocker :no_entry:

#9127 CP v1.6.1 CHANGELOG
  CHANGELOG.md
Labels: skip changelog
