Repository mapbox/mapbox-gl-js, pull requests merged in 2019-02, with the labels that each got.

#7876 Increase height of example code snippets
  docs/components/page_shell.js
  docs/components/site.css
Labels: docs :scroll:

#7878 Upgrade Earcut to v2.1.5
  package.json
  yarn.lock
Labels: release blocker :no_entry:

#7967 Optimize matrix calculation for labels
  src/geo/transform.js
  src/symbol/projection.js
Labels: performance :zap:
