Repository mapbox/mapbox-gl-js, pull requests merged in 2019-10, with the labels that each got.

#8868 Relax check for webworker transferability
  src/util/web_worker_transfer.js
Labels: bug :beetle:

#8872 Fire 'rotate' and 'pitch' events only when their value changed
  src/ui/handler/drag_rotate.js
  test/unit/ui/handler/drag_rotate.test.js
Labels: bug :beetle:

#8871 Show a disabled geolocate button if user or system denies geolocation
  src/css/mapbox-gl.css
  src/css/svg/mapboxgl-ctrl-geolocate-disabled.svg
  src/ui/control/geolocate_control.js
Labels: feature :green_apple:

#8807 [docs] Address user feedback for /api: setStyle, getStyle, isStyleLoaded
  src/ui/map.js
Labels: docs :scroll:

#8874 Add rules for High Contrast mode on Windows
  .stylelintrc
  debug/debug.html
  postcss.config.js
  src/css/mapbox-gl.css
  src/css/svg/mapboxgl-ctrl-attrib.svg
  src/css/svg/mapboxgl-ctrl-compass.svg
  src/css/svg/mapboxgl-ctrl-fullscreen.svg
  src/css/svg/mapboxgl-ctrl-geolocate-background.svg
  src/css/svg/mapboxgl-ctrl-geolocate-disabled.svg
  src/css/svg/mapboxgl-ctrl-geolocate.svg
  src/css/svg/mapboxgl-ctrl-logo-compact.svg
  src/css/svg/mapboxgl-ctrl-logo.svg
  src/css/svg/mapboxgl-ctrl-shrink.svg
  src/css/svg/mapboxgl-ctrl-zoom-in.svg
  src/css/svg/mapboxgl-ctrl-zoom-out.svg
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/navigation_control.js
Labels: bug :beetle:
