Repository mapbox/mapbox-gl-js, pull requests merged in 2019-03, with the labels that each got.

#7988 ensure we're calling the correct cancellation function
  src/util/actor.js
Labels: bug :beetle:, release blocker :no_entry:

#7995 Exclude current Safari from using Fetch API
  src/util/ajax.js
Labels: bug :beetle:

#8018 Avoid reapplying marker anchor class on every frame
  src/ui/marker.js
Labels: performance :zap:
