Repository mapbox/mapbox-gl-js, pull requests merged in 2020-01, with the labels that each got.

#9156 Prevent changing bearing via URL hash when rotation is disabled
  src/ui/hash.js
  test/unit/ui/hash.test.js
Labels: bug :beetle:

#9092 Immediately update map when more than one geolocation watch event is triggered
  debug/multiple.html
  src/ui/control/geolocate_control.js
Labels: bug :beetle:

#9138 fix extrusion querying for polygons with coincident points
  src/style/style_layer/fill_extrusion_style_layer.js
  test/integration/query-tests/regressions/mapbox-gl-js#8999/expected.json
  test/integration/query-tests/regressions/mapbox-gl-js#8999/style.json
  test/unit/style/style_layer/fill_extrusion_style_layer.js
Labels: bug :beetle:

#9157 Update symbol-avoid-edges doc copy to acknowledge the existence of global collision detection
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#9163 Add option to close popup on map move
  src/ui/popup.js
  test/unit/ui/popup.test.js
Labels: feature :green_apple:

#9054 make placement respect symbol-sort-key
  src/data/bucket/symbol_bucket.js
  src/style/pauseable_placement.js
  src/symbol/placement.js
  src/symbol/symbol_layout.js
  test/integration/render-tests/symbol-sort-key/placement-tile-boundary-left-then-right/expected.png
  test/integration/render-tests/symbol-sort-key/placement-tile-boundary-left-then-right/style.json
  test/integration/render-tests/symbol-sort-key/placement-tile-boundary-right-then-left/expected.png
  test/integration/render-tests/symbol-sort-key/placement-tile-boundary-right-then-left/style.json
  test/unit/data/symbol_bucket.test.js
Labels: bug :beetle:

#9170 Fix hash
  src/ui/hash.js
Labels: skip changelog

#9165 Add instructions for changelog authoring to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip changelog

#9190 Update package version to 1.8.0-dev
  package.json
Labels: skip changelog

#9189 Prefer line-pattern over line-dasharray in accordance with documentation
  src/render/draw_line.js
  test/integration/render-tests/line-pattern/with-dasharray/expected.png
  test/integration/render-tests/line-pattern/with-dasharray/style.json
Labels: bug :beetle:, cross-platform :tv:

#9194 Remove Object.values usage that was causing IE11 to fail
  src/source/source_cache.js
Labels: bug :beetle:

#9195 v1.7.0-beta.1
  CHANGELOG.md
  package.json
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#9212 Fix promoteId spec definitions
  src/style-spec/reference/v8.json
Labels: skip changelog

#9220 Fix line distances breaking gradient across tile boundaries
  src/data/bucket/line_bucket.js
  test/integration/render-tests/line-gradient/gradient-tile-boundaries/expected.png
  test/integration/render-tests/line-gradient/gradient-tile-boundaries/style.json
Labels: bug :beetle:

#9228 Update image expression SDK support table
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#9235 [tests][tile mode] Add left-top-right-buttom-offset-tile-map-mode test
  test/ignores.json
  test/integration/render-tests/text-variable-anchor/left-top-right-buttom-offset-tile-map-mode/expected.png
  test/integration/render-tests/text-variable-anchor/left-top-right-buttom-offset-tile-map-mode/style.json
Labels: cross-platform :tv:, testing :100:

#9232 Reduce size of line atlas by removing unused channels
  src/render/line_atlas.js
Labels: performance :zap:

#9218 Fix a bug where lines with duplicate endpoint disappear on z18+
  src/data/bucket/line_bucket.js
  src/style-spec/types.js
  test/integration/render-tests/regressions/mapbox-gl-js#5171/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#5171/style.json
Labels: bug :beetle:

#9217 Canonicalize Mapbox tile URLs from inline TileJSON as well
  src/source/load_tilejson.js
  src/source/raster_dem_tile_source.js
  src/source/raster_tile_source.js
  src/source/vector_tile_source.js
  src/util/mapbox.js
  test/unit/source/vector_tile_source.test.js
  test/unit/ui/control/logo.test.js
  test/unit/util/mapbox.test.js
Labels: bug :beetle:

#9237 Prevent empty buffers from being created for debug data when unused
  src/data/bucket/symbol_bucket.js
Labels: performance :zap:
