Repository mapbox/mapbox-gl-js, pull requests merged in 2020-03, with the labels that each got.

#9364 Disable depth mode for heatmaps
  src/render/draw_heatmap.js
Labels: skip changelog

#9367 Start quickly with Streets v11
  docs/components/quickstart.js
Labels: docs :scroll:

#9355 Simplify text-font static output validation
  src/style-spec/expression/compound_expression.js
  src/style-spec/expression/definitions/assertion.js
  src/style-spec/expression/definitions/at.js
  src/style-spec/expression/definitions/case.js
  src/style-spec/expression/definitions/coalesce.js
  src/style-spec/expression/definitions/coercion.js
  src/style-spec/expression/definitions/collator.js
  src/style-spec/expression/definitions/comparison.js
  src/style-spec/expression/definitions/format.js
  src/style-spec/expression/definitions/format_section_override.js
  src/style-spec/expression/definitions/image.js
  src/style-spec/expression/definitions/in.js
  src/style-spec/expression/definitions/interpolate.js
  src/style-spec/expression/definitions/length.js
  src/style-spec/expression/definitions/let.js
  src/style-spec/expression/definitions/literal.js
  src/style-spec/expression/definitions/match.js
  src/style-spec/expression/definitions/number_format.js
  src/style-spec/expression/definitions/step.js
  src/style-spec/expression/definitions/var.js
  src/style-spec/expression/expression.js
  src/style-spec/validate/validate_expression.js
Labels: skip changelog

#9374 Correctly detect expressions and legacy filters for the new in expression
  src/style-spec/feature_filter/index.js
  test/unit/style-spec/feature_filter.test.js
Labels: bug :beetle:

#9358 Remove unused struct code
  src/data/array_types.js
  src/util/struct_array.js.ejs
Labels: skip changelog

#9377 Prevent creation of unused depth renderbuffer attachments
  src/gl/context.js
  src/gl/framebuffer.js
  src/render/draw_heatmap.js
  src/render/draw_hillshade.js
  src/render/painter.js
Labels: performance :zap:

#9380 Do not warn about icon-image expressions evaluating to ''
  src/data/bucket/symbol_bucket.js
  src/style-spec/expression/definitions/image.js
  src/style-spec/expression/types/resolved_image.js
  test/unit/ui/map.test.js
Labels: bug :beetle:

#9385 Fix corner case with dash-array 0-length collapsing
  src/render/line_atlas.js
  test/unit/render/line_atlas.test.js
Labels: bug :beetle:

#9397 [render tests][tile mode] Add symbol-placement/line-center render tests
  test/ignores.json
  test/integration/render-tests/symbol-placement/line-center-buffer-tile-map-mode/expected.png
  test/integration/render-tests/symbol-placement/line-center-buffer-tile-map-mode/style.json
  test/integration/render-tests/symbol-placement/line-center-tile-map-mode/expected.png
  test/integration/render-tests/symbol-placement/line-center-tile-map-mode/style.json
Labels: testing :100:

#9393 Add render test for filter with expression in.
  test/integration/render-tests/filter/in/expected.png
  test/integration/render-tests/filter/in/style.json
Labels: testing :100:

#9266 Fix line-pattern artifacts under overscaling and underscaling
  src/shaders/line_pattern.fragment.glsl
  src/shaders/line_pattern.vertex.glsl
  test/integration/render-tests/line-pattern/@2x/expected.png
  test/integration/render-tests/line-pattern/literal/expected.png
  test/integration/render-tests/line-pattern/opacity/expected.png
  test/integration/render-tests/line-pattern/overscaled/expected.png
  test/integration/render-tests/line-pattern/pitch/expected.png
  test/integration/render-tests/line-pattern/property-function/expected.png
  test/integration/render-tests/line-pattern/step-curve/expected.png
  test/integration/render-tests/line-pattern/with-dasharray/expected.png
  test/integration/render-tests/line-pattern/zoom-expression/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#5978/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#8273/expected.png
  test/integration/render-tests/regressions/mapbox-gl-native#9976/expected.png
Labels: bug :beetle:

#9372 Fix addImage API option for pixel ratio
  src/data/array_types.js
  src/data/bucket/pattern_attributes.js
  src/data/program_configuration.js
  src/render/program/fill_extrusion_program.js
  src/render/program/fill_program.js
  src/render/program/line_program.js
  src/render/program/pattern.js
  src/shaders/fill_extrusion_pattern.fragment.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
  src/shaders/fill_outline_pattern.vertex.glsl
  src/shaders/fill_pattern.vertex.glsl
  src/shaders/line_pattern.fragment.glsl
  src/shaders/line_pattern.vertex.glsl
  test/integration/render-tests/fill-extrusion-pattern/1.5x-on-1x-add-image/expected.png
  test/integration/render-tests/fill-extrusion-pattern/1.5x-on-1x-add-image/style.json
  test/integration/render-tests/fill-pattern/3x-on-2x-add-image/expected.png
  test/integration/render-tests/fill-pattern/3x-on-2x-add-image/style.json
  test/integration/render-tests/line-pattern/3x-on-2x-add-image/expected.png
  test/integration/render-tests/line-pattern/3x-on-2x-add-image/style.json
Labels: api :memo:, bug :beetle:

#9352 Introduce `within` expression
  bench/benchmarks/symbol_layout.js
  src/data/bucket.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/data/feature_index.js
  src/data/program_configuration.js
  src/source/tile.js
  src/source/worker_tile.js
  src/style-spec/expression/definitions/index.js
  src/style-spec/expression/definitions/within.js
  src/style-spec/expression/evaluation_context.js
  src/style-spec/expression/index.js
  src/style-spec/expression/is_constant.js
  src/style-spec/expression/parsing_context.js
  src/style-spec/feature_filter/index.js
  src/style-spec/package.json
  src/style-spec/reference/v8.json
  src/style/properties.js
  src/style/style_layer.js
  src/style/style_layer/symbol_style_layer.js
  src/symbol/symbol_layout.js
  test/expression.test.js
  test/ignores.json
  test/integration/expression-tests/within/invalid-geojson/test.json
  test/integration/render-tests/within/filter-with-inlined-geojson/expected.png
  test/integration/render-tests/within/filter-with-inlined-geojson/style.json
  test/integration/render-tests/within/layout-text/expected.png
  test/integration/render-tests/within/layout-text/style.json
  test/integration/render-tests/within/paint-circle/expected.png
  test/integration/render-tests/within/paint-circle/style.json
  test/integration/render-tests/within/paint-icon/expected.png
  test/integration/render-tests/within/paint-icon/style.json
  test/integration/render-tests/within/paint-line-with-simple-polygon/expected.png
  test/integration/render-tests/within/paint-line-with-simple-polygon/style.json
  test/integration/render-tests/within/paint-text/expected.png
  test/integration/render-tests/within/paint-text/style.json
  test/unit/style-spec/feature_filter.test.js
Labels: needs changelog

#9409 Fix for IE11 not supporting startsWith
  src/data/program_configuration.js
Labels: bug :beetle:, release blocker :no_entry:, skip changelog

#9410 Fix webgl error on IE11 for mismatching texture formats
  src/render/painter.js
Labels: release blocker :no_entry:, skip changelog

#9433 Avoid throwing errors when popup container is undefined
  src/ui/popup.js
Labels: bug :beetle:

#9452 populate paint arrays only once per line feature
  src/data/bucket/line_bucket.js
Labels: skip changelog

#9454 fix fill extrusion querying for colinear points
  src/style/style_layer/fill_extrusion_style_layer.js
  test/integration/query-tests/regressions/mapbox-gl-js#8999-2/expected.json
  test/integration/query-tests/regressions/mapbox-gl-js#8999-2/style.json
Labels: bug :beetle:

#9466 Upgrade direct dependencies & do yarn upgrade
  build/test/build-tape.js
  package.json
  test/unit/gl/state.test.js
  yarn.lock
Labels: skip changelog

#9470 Remove leftover page shell (unused since the docs split)
  vendor/docs-page-shell/page-shell-script.js
  vendor/docs-page-shell/page-shell-styles.css
  vendor/docs-page-shell/react-page-shell.js
Labels: skip changelog

#9472 More resilient paint check in setFeatureState
  src/source/tile.js
Labels: skip changelog

#9480 [release-caspian] Ensure padding is not propagated from fitBounds to transform padding
  src/ui/camera.js
  test/unit/ui/camera.test.js
Labels: bug :beetle:

#9481 [master] Ensure padding is not propagated from fitBounds to transform padding
  src/ui/camera.js
  test/unit/ui/camera.test.js
Labels: bug :beetle:

#9482 Fix pattern attributes vertex layout
  src/data/bucket/pattern_attributes.js
  src/data/program_configuration.js
  src/render/draw_fill_extrusion.js
  test/integration/render-tests/fill-extrusion-pattern/2x-on-1x-add-image-dds/expected.png
  test/integration/render-tests/fill-extrusion-pattern/2x-on-1x-add-image-dds/style.json
Labels: bug :beetle:
