Repository mapbox/mapbox-gl-js, pull requests merged in 2020-04, with the labels that each got.

#9463 Optimize tail calls in feature state sorting
  src/data/feature_position_map.js
Labels: bug :beetle:

#9474 Update per mdn webgl recommendations
  src/gl/context.js
  src/render/draw_heatmap.js
  src/render/program.js
  test/release/index.js
Labels: skip changelog

#9486 fix documented type of the locale option to Map
  src/ui/map.js
Labels: skip changelog

#9491 [release-caspian] Fix binder.setUniform error symbol in draw loop
  src/render/draw_symbol.js
Labels: bug :beetle:

#9493 [master] Fix binder.setUniform error symbol in draw loop
  src/render/draw_symbol.js
Labels: bug :beetle:

#9489 Allow client to retry RTLTextPlugin load after NetworkError
  debug/rtl.html
  src/source/rtl_text_plugin.js
Labels: feature :green_apple:

#9498 Fix several listener leaks in popups
  src/ui/popup.js
Labels: bug :beetle:

#9391 Add methods to mapboxgl namespace to allow preloading of workers.
  src/index.js
  src/util/global_worker_pool.js
  src/util/worker_pool.js
Labels: feature :green_apple:, performance :zap:

#9365 gesture handling refactor
  bench/benchmarks/paint.js
  src/ui/bind_handlers.js
  src/ui/camera.js
  src/ui/control/navigation_control.js
  src/ui/events.js
  src/ui/handler/box_zoom.js
  src/ui/handler/click_zoom.js
  src/ui/handler/dblclick_zoom.js
  src/ui/handler/drag_pan.js
  src/ui/handler/drag_rotate.js
  src/ui/handler/handler_util.js
  src/ui/handler/keyboard.js
  src/ui/handler/map_event.js
  src/ui/handler/mouse.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler/shim/dblclick_zoom.js
  src/ui/handler/shim/drag_pan.js
  src/ui/handler/shim/drag_rotate.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/tap_drag_zoom.js
  src/ui/handler/tap_recognizer.js
  src/ui/handler/tap_zoom.js
  src/ui/handler/touch_pan.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/handler_inertia.js
  src/ui/handler_manager.js
  src/ui/map.js
  src/util/debug.js
  src/util/dom.js
  src/util/task_queue.js
  test/build/dev.test.js
  test/build/min.test.js
  test/unit/ui/camera.test.js
  test/unit/ui/handler/dblclick_zoom.test.js
  test/unit/ui/handler/drag_pan.test.js
  test/unit/ui/handler/drag_rotate.test.js
  test/unit/ui/handler/keyboard.test.js
  test/unit/ui/handler/scroll_zoom.test.js
  test/unit/ui/handler/touch_zoom_rotate.test.js
  test/unit/ui/map.test.js
  test/unit/ui/map/isMoving.test.js
  test/unit/ui/map/isZooming.test.js
  test/util/simulate_interaction.js
  test/util/test.js
Labels: bug :beetle:, feature :green_apple:

#9511 fix DragRotateHandler#isActive
  src/ui/handler/shim/drag_rotate.js
  test/unit/ui/handler/drag_rotate.test.js
Labels: release blocker :no_entry:, skip changelog

#9508 remove handler event listeners when map is removed
  src/ui/control/navigation_control.js
  src/ui/handler/box_zoom.js
  src/ui/handler/mouse.js
  src/ui/handler_manager.js
  src/ui/map.js
Labels: skip changelog

#9509 Update style specification compatibility tables (release-vanillashake)
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:, docs :scroll:

#9520 Fix for issue 9518
  src/render/painter.js
  test/integration/render-tests/regressions/mapbox-gl-js#9518/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#9518/style.json
Labels: bug :beetle:, release blocker :no_entry:

#9526 fix #9519 click map event on touch devices
  src/ui/handler/tap_recognizer.js
  src/ui/handler/tap_zoom.js
Labels: skip changelog

#9521 [release-caspian] Fix style-spec isolation for within expression
  src/style-spec/expression/definitions/within.js
  src/style-spec/rollup.config.js
Labels: release blocker :no_entry:

#9522 [master] Fix style-spec isolation for within expression
  src/style-spec/expression/definitions/within.js
  src/style-spec/rollup.config.js
Labels: release blocker :no_entry:

#9530 export isExpressionFilter from spec
  src/style-spec/style-spec.js
Labels: refactoring :building_construction:

#9534 [danube] export isExpressionFilter from spec (#9530)
  src/style-spec/style-spec.js
Labels: release blocker :no_entry:

#9533 [caspian] export isExpressionFilter from spec (#9530)
  src/style-spec/style-spec.js
Labels: release blocker :no_entry:

#9536 fix mapTouchEvent.point for touchend events
  src/ui/events.js
  test/unit/ui/handler/map_event.test.js
Labels: skip changelog

#9537 [release-danube] fix mapTouchEvent.point for touchend events (#9536)
  src/ui/events.js
  test/unit/ui/handler/map_event.test.js
Labels: bug :beetle:, release blocker :no_entry:

#9543 Refactor format_section_override out of style-spec
  src/style/format_section_override.js
  src/style/style_layer/symbol_style_layer.js
  test/unit/style/format_section_override.test.js
  test/unit/symbol/symbol_style_layer.test.js
Labels: skip changelog

#9550 More explicit files property in package.json
  .npmignore
  build/diff-tarball.js
  package.json
  yarn.lock
Labels: skip changelog

#9589 [docsprint] Clarify meaning of Map#isSourceLoaded
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9552 [docsprint] Add geolocate trigger example
  src/ui/control/geolocate_control.js
Labels: DO NOT MERGE, docs :scroll:

#9592 [docsprint] Add inline snippet to marker#addTo
  src/ui/marker.js
Labels: DO NOT MERGE, docs :scroll:

#9538 [docsprint] Add inline snippet and related examples to popup.setHTML
  src/ui/popup.js
Labels: DO NOT MERGE, docs :scroll:

#9547 [docsprint] Add inline and related example for panTo
  src/ui/camera.js
Labels: DO NOT MERGE, docs :scroll:

#9548 [docsprint] Add inline snippet to LngLatBounds.contains
  src/geo/lng_lat_bounds.js
Labels: DO NOT MERGE, docs :scroll:

#9549 [docsprint] Add inline snippet and examples to map.jumpTo
  src/ui/camera.js
Labels: DO NOT MERGE, docs :scroll:

#9551 [docsprint] Add inline snippet and tutorial example to map.getCenter
  src/ui/camera.js
Labels: DO NOT MERGE, docs :scroll:

#9553 [docsprint] Add code snippet and related examples for Marker class setLngLat
  src/ui/marker.js
Labels: DO NOT MERGE, docs :scroll:

#9554 [docsprint] Add examples to get- and setLayoutProperty
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9555 [docsprint] Add inline snippet and related examples to map.triggerRepaint
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9556 [docsprint] CameraOptions - update pitch and bearing definitions, add code examples
  src/ui/camera.js
Labels: DO NOT MERGE, docs :scroll:

#9557 [docsprint] Add inline code snippet to map.showTileBoundaries
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9558 [docsprint] Mark Debug namespace as private to hide it from the docs
  src/util/debug.js
Labels: DO NOT MERGE, docs :scroll:

#9559 [docsprint] Add detail to docs on setFeatureState, removeFeatureState, getFeatureState
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9560 [docsprint] map.on: remove extra on section, link to event types, add code snippet, add related
  src/ui/events.js
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9565 [docsprint] Add examples to open and close popup events
  src/ui/popup.js
Labels: DO NOT MERGE, docs :scroll:

#9566 [docsprint] Clarify how map.moveLayer works
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9570 [doscprint] add links to EPSG and minor example changes for LngLat
  src/geo/lng_lat.js
Labels: DO NOT MERGE, docs :scroll:

#9571 [docsprint] Document the layer object's properties in addLayer
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9572 [docsprint] Add inline snippet and examples to popup.addTo
  src/ui/popup.js
Labels: DO NOT MERGE, docs :scroll:

#9575 [docsprint] Add inline example for trackPointer
  src/ui/popup.js
Labels: DO NOT MERGE, docs :scroll:

#9576 [docsprint] Add inline example for Popup#getElement
  src/ui/popup.js
Labels: DO NOT MERGE, docs :scroll:

#9577 [docsprint] Add inline examples for Point & PointLike types
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9564 [docsprint] Cleanup doc for MapBoxZoomEvent
  src/ui/events.js
Labels: DO NOT MERGE, docs :scroll:

#9579 [docsprint] Describe map style object returned by Map#getStyle
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9580 [docsprint] Add inline example for getClusterLeaves
  src/source/geojson_source.js
Labels: DO NOT MERGE, docs :scroll:

#9581 [docsprint] PaddingOptions - update definition, example, and related
  src/ui/camera.js
Labels: DO NOT MERGE, docs :scroll:

#9582 [docsprint] Add inline snippet to marker#setPopup, marker#getPopup, and marker#togglePopup
  src/ui/marker.js
Labels: DO NOT MERGE, docs :scroll:

#9586 update setFilter jsdoc
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9587 [docsprint] Add more details to getSource
  src/ui/map.js
Labels: DO NOT MERGE, docs :scroll:

#9588 [docsprint] Add clearStorage example
  src/index.js
Labels: DO NOT MERGE, docs :scroll:

#9573 [docsprint] Add documentation for RequestParameters
  src/util/ajax.js
Labels: DO NOT MERGE, docs :scroll:

#9593 [docsprint] Add inline example for setZoomRate and setWheelZoomRate of scrollZoomHandler
  src/ui/handler/scroll_zoom.js
Labels: DO NOT MERGE, docs :scroll:

#9594 [docsprint] Add inline examples for map zoom-related methods
  src/ui/camera.js
Labels: DO NOT MERGE, docs :scroll:

#9595 [docsprint] Add example to MapMouseEvent
  src/ui/events.js
Labels: DO NOT MERGE, docs :scroll:

#9596 [docsprint] Add examples for GeolocateControl events
  src/ui/control/geolocate_control.js
Labels: DO NOT MERGE, docs :scroll:

#9597 [docsprint] Add example to MapDataEvent
  src/ui/events.js
Labels: DO NOT MERGE, docs :scroll:

#9591 [docsprint] Add inline snippet and related example to getLngLat
  src/ui/marker.js
Labels: DO NOT MERGE, docs :scroll:

#9590 Clean check in `prepublishOnly`
  package.json
  src/style-spec/package.json
Labels: skip changelog

#9414 Add scale to Marker options
  debug/markers.html
  src/ui/marker.js
  test/unit/ui/marker.test.js
Labels: feature :green_apple:

#9604 Change return type to boolean for StyleImageInterface type alias
  src/style/style_image.js
Labels: api :memo:, skip changelog

#9611 Fix using `within` expression with complex `filter`
  src/style-spec/feature_filter/index.js
  src/style-spec/reference/v8.json
  src/style-spec/validate/validate_filter.js
  test/integration/render-tests/within/within-in-complex-filter/expected.png
  test/integration/render-tests/within/within-in-complex-filter/style.json
Labels: needs changelog

#9622 Trigger memory metrics
  .circleci/config.yml
Labels: skip changelog

#9607 Docs sprint primary pull request
  src/geo/lng_lat.js
  src/geo/lng_lat_bounds.js
  src/index.js
  src/source/geojson_source.js
  src/ui/camera.js
  src/ui/control/geolocate_control.js
  src/ui/events.js
  src/ui/handler/scroll_zoom.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
  src/util/ajax.js
  src/util/debug.js
Labels: docs :scroll:, release blocker :no_entry:

#9618 Reverse tap-drag-zoom direction
  src/ui/handler/tap_drag_zoom.js
Labels: release blocker :no_entry:, skip changelog
