Repository mapbox/mapbox-gl-js, pull requests merged in 2020-06, with the labels that each got.

#9748 Add clusterMinPoints option for GeoJSONSource
  package.json
  src/source/geojson_source.js
  src/style-spec/reference/v8.json
  test/unit/source/geojson_source.test.js
  yarn.lock
Labels: feature :green_apple:

#9749 Avoid errors when requiring the browser bundle in Node
  rollup/bundle_prelude.js
  src/util/browser.js
  src/util/browser/window.js
  src/util/dom.js
  test/build/min.test.js
Labels: bug :beetle:

#9754 add extra geolocate control private method documentation
  src/ui/control/geolocate_control.js
  src/util/throttle.js
Labels: skip changelog

#9753 Do not warn about exceeding extent when off by 1px
  src/data/load_geometry.js
Labels: bug :beetle:

#9758 update addLayer beforeId documentation to mention how it appears visually in the style
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#9780 jsdoc formatting
  src/ui/camera.js
Labels: docs :scroll:, skip changelog

#9792 Remove expression_name enum from bundled spec
  build/rollup_plugin_minify_style_spec.js
Labels: skip changelog
