Repository mapbox/mapbox-gl-js, pull requests merged in 2020-12, with the labels that each got.

#10171 fire map mouse events during scroll zooming
  src/ui/handler_manager.js
  test/unit/ui/handler/map_event.test.js
Labels: bug :beetle:

#10149 [docs] Update getStyle example
  src/ui/map.js
Labels: docs :scroll:

#10177 Fix a bug in which map.setStyle() could not be used to enable terrain.
  src/style-spec/diff.js
  src/ui/map.js
  test/integration/render-tests/runtime-styling/set-style-terrain-disable/expected.png
  test/integration/render-tests/runtime-styling/set-style-terrain-disable/style.json
  test/integration/render-tests/runtime-styling/set-style-terrain-enable/expected.png
  test/integration/render-tests/runtime-styling/set-style-terrain-enable/style.json
  test/unit/ui/map.test.js
Labels: bug :beetle:

#10193 Ensure accessToken is available when running render tests
  .circleci/config.yml
  package.json
Labels: skip changelog

#10213 Allow isMapboxHTTPURL to be configured at build time
  src/util/config.js
  src/util/mapbox.js
Labels: skip changelog

#10202 Clean up browser hacks that are no longer necessary
  build/check-bundle-size.js
  src/css/mapbox-gl.css
  src/ui/control/fullscreen_control.js
  src/ui/hash.js
  src/util/browser.js
  src/util/dom.js
Labels: skip changelog

#10164 Fix some docs issues
  src/ui/camera.js
  src/ui/events.js
  src/ui/free_camera.js
  src/ui/map.js
Labels: skip changelog

#10230 Fix ImageSource not working in FF/Safari
  src/util/ajax.js
Labels: bug :beetle:

#10237 Upgrade mapbox-gl-supported to v2.0.0
  flow-typed/mapbox-gl-supported.js
  package.json
  src/index.js
  src/ui/map.js
  yarn.lock
Labels: skip changelog
