Repository mapbox/mapbox-gl-js, pull requests merged in 2020-07, with the labels that each got.

#9863 Fix precedence of promoteId over feature id in fill extrusions
  src/data/bucket/fill_extrusion_bucket.js
  test/integration/render-tests/feature-state/promote-id-fill-extrusion/style.json
Labels: bug :beetle:

#8048 add support for dynamic vector tiles rendering #3709
  src/source/vector_tile_source.js
  test/unit/source/vector_tile_source.test.js
Labels: feature :green_apple:

#9834 Fix multiple layer sharing the same source for line gradients
  src/data/bucket/line_bucket.js
  src/render/draw_line.js
  test/integration/render-tests/line-gradient/gradient-shared-source/expected.png
  test/integration/render-tests/line-gradient/gradient-shared-source/style.json
Labels: bug :beetle:, skip changelog

#9892 [docs] Fix setRotationAlignment link
  src/ui/marker.js
Labels: docs :scroll:

#9899 Clarification in clusterMaxZoom documentation
  src/style-spec/reference/v8.json
Labels: skip changelog
