Repository mapbox/mapbox-gl-js, pull requests merged in 2020-02, with the labels that each got.

#9252 Update gl-js and style-spec changelogs, update style-spec version to 13.12.0-dev
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#9251 Pass errors to cluster function callbacks
  src/source/geojson_worker_source.js
Labels: bug :beetle:

#9261 Fix severe performance regression after introduction of image expression
  src/style/style.js
Labels: bug :beetle:, release blocker :no_entry:

#9258 Simplify formatted sections code
  src/data/bucket/symbol_bucket.js
  src/style/style_layer/symbol_style_layer.js
  test/unit/symbol/symbol_style_layer.test.js
Labels: skip changelog

#9246 Fix visual artifact for line-dasharray
  src/render/line_atlas.js
  test/integration/render-tests/line-dasharray/zero-length-gap/expected.png
  test/integration/render-tests/line-dasharray/zero-length-gap/style.json
Labels: bug :beetle:

#9276 add space before units in scale bar
  src/ui/control/scale_control.js
Labels: feature :green_apple:

#9268 Only normalize canonicalized mapbox tile URLs
  src/util/mapbox.js
Labels: skip changelog

#9288 Set geolocate onZoom callback only after ui is setup
  src/ui/control/geolocate_control.js
Labels: bug :beetle:

#9291 fix bug in GeolocateControl where onSuccess and onError callbacks were still being called after control was removed
  src/ui/control/geolocate_control.js
  test/unit/ui/control/geolocate.test.js
Labels: bug :beetle:

#9295 Allow needle argument to 'in' expression to be false
  src/style-spec/expression/definitions/in.js
  test/integration/expression-tests/in/basic-string/test.json
Labels: bug :beetle:

#9293 Letting `LngLatBounds.extend` accepts LngLatLike and LngLatBoundsLike as well.
  src/geo/lng_lat_bounds.js
  test/unit/geo/lng_lat_bounds.test.js
Labels: docs :scroll:, good first issue

#9305 Clearing the underlying source's tiles while removing a layer.
  src/source/tile.js
  src/style/style.js
Labels: bug :beetle:

#9326 fix links to addImage
  src/ui/map.js
Labels: skip changelog

#9325 link to hover effect example from getFeatureState
  src/ui/map.js
Labels: skip changelog

#9324 clarify GeolocateControl interaction states
  src/ui/control/geolocate_control.js
Labels: docs :scroll:

#9323 replace incorrect LatLngBounds with LngLatBounds
  src/ui/camera.js
Labels: skip changelog

#9322 Add benchmark coverage for text-variable-anchor and symbol-sort-key
  bench/benchmarks/layers.js
  bench/versions/benchmarks.js
Labels: skip changelog, testing :100:

#9332 Fix map not displaying inside RTL elements
  src/css/mapbox-gl.css
  src/ui/map.js
Labels: bug :beetle:

#9347 Fix style.hasLayer
  src/style/style.js
Labels: skip changelog

#9349 Use glUniform1i for boolean uniforms
  src/render/program/symbol_program.js
Labels: bug :beetle:

#9357 Terser options for better compression
  build/rollup_plugins.js
Labels: skip changelog
