Repository mapbox/mapbox-gl-js, pull requests merged in 2020-05, with the labels that each got.

#9654 Fix instrumentation for memory metrics
  src/ui/map.js
Labels: skip changelog

#9653 Fix CONTRIBUTING.md documentation of setup.
  CONTRIBUTING.md
Labels: skip changelog

#9667 Mapbox Maps SDK for iOS v5.9.0, macOS v0.16.0
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:, docs :scroll:

#9674 Cherry pick style spec docs updates
  src/style-spec/reference/v8.json
  test/unit/style-spec/expression.test.js
Labels: release blocker :no_entry:

#9668 Fix image expression
  src/source/worker.js
  src/source/worker_source.js
  src/style/properties.js
  src/style/style_layer.js
Labels: bug :beetle:

#9685 fix #9676, fire touchmove event while handlers are active
  src/ui/handler/map_event.js
  test/unit/ui/handler/map_event.test.js
Labels: bug :beetle:

#9681 Pattern attributes 4-bytes alignment
  build/generate-struct-arrays.js
  src/data/array_types.js
  src/data/bucket/pattern_attributes.js
  test/ignores.json
Labels: skip changelog

#9679 map.isMoving() match move events fix #9647
  src/ui/handler_manager.js
  src/ui/map.js
  test/unit/ui/handler/drag_rotate.test.js
  test/unit/ui/map/isMoving.test.js
  test/unit/ui/map_events.test.js
Labels: bug :beetle:

#9683 fix pinching while touching markers
  src/ui/handler/handler_util.js
  src/ui/handler/tap_drag_zoom.js
  src/ui/handler/tap_recognizer.js
  src/ui/handler/tap_zoom.js
  src/ui/handler/touch_pan.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/handler_manager.js
  test/unit/ui/handler/dblclick_zoom.test.js
  test/unit/ui/handler/drag_pan.test.js
  test/unit/ui/handler/map_event.test.js
  test/unit/ui/handler/touch_zoom_rotate.test.js
  test/unit/ui/map.test.js
Labels: bug :beetle:

#9696 Add tests for undocumented but supported ["literal"] expression forms
  test/integration/README.md
  test/integration/expression-tests/literal/literal-false/test.json
  test/integration/expression-tests/literal/literal-null/test.json
  test/integration/expression-tests/literal/literal-number/test.json
  test/integration/expression-tests/literal/literal-string/test.json
  test/integration/expression-tests/literal/literal-true/test.json
Labels: skip changelog
