Repository mapbox/mapbox-gl-js, pull requests merged in 2020-08, with the labels that each got.

#9911 Update the worker images once an image is added or removed + Render tests
  src/style/style.js
  test/integration/render-tests/runtime-styling/image-add-coalesce/expected.png
  test/integration/render-tests/runtime-styling/image-add-coalesce/style.json
Labels: bug :beetle:

#9884 Prevent bearing snap ease interfering with new ease
  src/ui/camera.js
  src/ui/handler_manager.js
Labels: bug :beetle:

#9852 fix(dragPan.touchmove): only call preventDefault when valid minTouches
  src/ui/handler/touch_pan.js
Labels: skip changelog

#9864 Add a filter option for GeoJSON sources
  src/source/geojson_source.js
  src/source/geojson_worker_source.js
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  test/integration/render-tests/geojson/clustered-filter/expected.png
  test/integration/render-tests/geojson/clustered-filter/style.json
Labels: feature :green_apple:

#9944 [docs only] Add a Marker example that uses options
  src/ui/marker.js
Labels: docs :scroll:

#9821 When fitBounds() is called with nonzero bearing, rotate padding
  src/ui/camera.js
  test/unit/ui/camera.test.js
Labels: bug :beetle:

#9943 Update attribution on layer visibility changes
  src/style/style.js
  src/ui/control/attribution_control.js
  src/ui/events.js
  test/unit/ui/control/attribution.test.js
Labels: bug :beetle:
