Repository mapbox/mapbox-gl-js, pull requests merged in 2021-03, with the labels that each got.

#10420 Add link to related example for `CanvasSource`
  src/source/canvas_source.js
Labels: skip changelog

#10418 Fix incorrect style serialization when using raster DEM tile sources
  src/source/raster_dem_tile_source.js
  test/unit/source/raster_dem_tile_source.test.js
Labels: bug :beetle:

#10432 Account for negative terrain elevation in frustum far plane definition
  src/data/dem_tree.js
  src/geo/transform.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  test/unit/geo/transform.test.js
  test/unit/terrain/terrain.test.js
Labels: bug :beetle:

#10433 Add related links to GL JS Examples for `FreeCameraOptions` and `AnimationOptions`
  src/ui/camera.js
  src/ui/free_camera.js
Labels: docs :scroll:

#10434 Add related links to GL JS Examples for all Handlers
  src/ui/handler/box_zoom.js
  src/ui/handler/keyboard.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler/shim/dblclick_zoom.js
  src/ui/handler/shim/drag_pan.js
  src/ui/handler/shim/drag_rotate.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/touch_zoom_rotate.js
Labels: docs :scroll:

#10401 update queryRenderedFeatures documentation to be clearer the geometry…
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10403 Update the docs to show the default limit and offset of getClusterLeaves
  src/source/geojson_source.js
Labels: docs :scroll:

#10413 Add getTerrain method
  src/style/style.js
  src/ui/map.js
  test/unit/style/style.test.js
Labels: feature :green_apple:

#10445 Add a `testMode` Map option to allow for usage in tests without an access token
  src/render/painter.js
  src/render/program.js
  src/ui/map.js
  src/util/browser.js
  src/util/mapbox.js
  test/browser/drag.test.js
  test/browser/fixtures/land.html
  test/browser/zoom.test.js
  test/unit/ui/handler/scroll_zoom.test.js
  test/unit/ui/map.test.js
  test/util/index.js
Labels: feature :green_apple:

#10455 Allow to run `codegen` command with latest main
  build/generate-struct-arrays.js
  build/generate-style-code.js
Labels: skip changelog, workflow :nail_care:

#10417 Simplify and optimize worker task scheduling
  src/source/geojson_source.js
  src/source/geojson_worker_source.js
  src/source/raster_dem_tile_source.js
  src/source/vector_tile_source.js
  src/source/worker.js
  src/source/worker_tile.js
  src/util/actor.js
  src/util/scheduler.js
  test/unit/source/geojson_source.test.js
  test/unit/source/geojson_worker_source.test.js
Labels: bug :beetle:

#10456 Fix fill outline rendering
  src/shaders/fill_outline.fragment.glsl
  src/shaders/fill_outline.vertex.glsl
  test/integration/render-tests/fill-extrusion-opacity/function/expected.png
  test/integration/render-tests/fill-extrusion-opacity/literal/expected.png
  test/integration/render-tests/fill-outline-color/pitch/expected.png
  test/integration/render-tests/fill-outline-color/pitch/style.json
  test/integration/render-tests/text-pitch-alignment/viewport-text-depthtest/expected.png
Labels: bug :beetle:

#10485 Disable terrain render cache during style property transitions
  src/terrain/terrain.js
  test/integration/lib/operation-handlers.js
  test/integration/render-tests/terrain/cache-invalidation/background-layer/expected.png
  test/integration/render-tests/terrain/cache-invalidation/background-layer/style.json
  test/integration/render-tests/terrain/cache-invalidation/fill-layer-change-color/expected.png
  test/integration/render-tests/terrain/cache-invalidation/fill-layer-change-color/style.json
  test/integration/render-tests/terrain/cache-invalidation/hide-layer/expected.png
  test/integration/render-tests/terrain/cache-invalidation/hide-layer/style.json
  test/integration/render-tests/terrain/cache-invalidation/hillshade-shared/expected.png
  test/integration/render-tests/terrain/cache-invalidation/hillshade-shared/style.json
  test/integration/render-tests/terrain/cache-invalidation/remove-layer/expected.png
  test/integration/render-tests/terrain/cache-invalidation/remove-layer/style.json
  test/integration/render-tests/terrain/cache-invalidation/show-layer/expected.png
  test/integration/render-tests/terrain/cache-invalidation/show-layer/style.json
Labels: bug :beetle:

#10486 [docs] Clarify nature of match for `match` expression in Style Spec
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#10475 [docs only] Link to Map#addControl from each control section
  src/ui/control/attribution_control.js
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/logo_control.js
  src/ui/control/navigation_control.js
  src/ui/control/scale_control.js
Labels: docs :scroll:

#10480 Add note about fullscreen compatibility with mobile safari
  src/ui/control/fullscreen_control.js
Labels: skip changelog

#10494 Always retain raster tile cache control data
  src/source/raster_dem_tile_source.js
  src/source/raster_tile_source.js
  src/util/ajax.js
  test/unit/util/ajax.test.js
Labels: bug :beetle:

#10502 Add a WebGL error reporter script to debug/
  debug/webgl-error-reporter.js
Labels: skip changelog

#10503 Add specificity to triggerRepaint jsdoc
  src/ui/map.js
Labels: skip changelog

#10504 Clarify that `zoomend` can be complete before map rendering is complete.
  src/ui/events.js
Labels: docs :scroll:

#10523 Upgrade supercluster to v7.1.3
  package.json
  yarn.lock
Labels: bug :beetle:

#10524 Fix an edge case with loadImage in Safari and older Firefox
  src/ui/map.js
Labels: bug :beetle:
