Repository mapbox/mapbox-gl-js, pull requests merged in 2021-08, with the labels that each got.

#10901 Change `sprite` link from glossary --> style spec
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10889 Allow edits to popup container class while the popup is not on the map
  src/ui/anchor.js
  src/ui/marker.js
  src/ui/popup.js
  test/unit/ui/popup.test.js
Labels: api :memo:, bug :beetle:, feature :green_apple:, refactoring :building_construction:

#10907 Remove event listener for Safari resize
  src/ui/map.js
Labels: skip changelog

#10900 Update RTL plugin callback description
  src/index.js
  src/source/rtl_text_plugin.js
Labels: docs :scroll:, skip changelog

#10912 [docs] Add parenthesis around JSDoc param `data` for addImage and updateImage
  src/ui/map.js
Labels: skip changelog

#10910 Improves `DragPanHandler` example and docs
  src/ui/handler/shim/drag_pan.js
Labels: docs :scroll:, skip changelog

#10918 Improve collision detection for labels along lines by switching to runtime evaluation of collision circle's pixelated radius
  src/symbol/placement.js
  src/symbol/symbol_layout.js
  test/integration/render-tests/debug/collision-icon-text-line-translate-fractional-zoom/expected.png
  test/integration/render-tests/free-camera/default/expected.png
  test/integration/render-tests/real-world/chicago/expected.png
Labels: feature :green_apple:

#10928 Add gradient-with-corners render test
  test/integration/render-tests/line-gradient/gradient-with-corners/expected.png
  test/integration/render-tests/line-gradient/gradient-with-corners/style.json
Labels: skip changelog

#10926 Handles firing closeOnClick before another listener
  src/ui/events.js
  src/ui/handler/map_event.js
  src/ui/map.js
  src/ui/popup.js
  src/util/evented.js
  test/unit/ui/map_events.test.js
Labels: bug :beetle:

#10903 Fix to map jumping when bounds cross longitude 180
  debug/antimeridian.html
  src/geo/transform.js
  test/unit/geo/transform.test.js
Labels: bug :beetle:

#10937 Fixing render test console.logs in browser
  build/test/build-tape.js
  package.json
  test/integration/testem/testem.js
  test/util/tape_config.js
  yarn.lock
Labels: skip changelog
