Repository mapbox/mapbox-gl-js, pull requests merged in 2021-09, with the labels that each got.

#10988 Add render test for setting line-gradient style property at runtime
  test/integration/render-tests/line-gradient/runtime-set-gradient/expected.png
  test/integration/render-tests/line-gradient/runtime-set-gradient/style.json
Labels: skip changelog

#10996 Implement queryRenderedFeatures for heatmap layers
  debug/heatmap.html
  src/style-spec/reference/v8.json
  src/style/style_layer/circle_style_layer.js
  src/style/style_layer/heatmap_style_layer.js
  test/integration/query-tests/heatmap/inside/expected.json
  test/integration/query-tests/heatmap/inside/style.json
  test/integration/query-tests/heatmap/outside/expected.json
  test/integration/query-tests/heatmap/outside/style.json
  test/integration/query-tests/regressions/mapbox-gl-js#5473/expected.json
Labels: feature :green_apple:

#10936 Fix canvas size to round up to container size
  debug/canvas-size.html
  src/ui/control/geolocate_control.js
  src/ui/control/scale_control.js
  src/ui/map.js
  test/integration/render-tests/icon-image/icon-snapping/expected.png
  test/integration/render-tests/icon-image/icon-snapping/style.json
  test/release/canvas-size.html
  test/release/index.js
  test/unit/terrain/terrain.test.js
  test/unit/ui/hash.test.js
  test/unit/ui/map.test.js
  test/unit/ui/marker.test.js
  test/unit/ui/popup.test.js
  test/util/index.js
Labels: bug :lady_beetle:

#10995 Added links to SDF image documentation for icon-color and icon-halo-color
  src/style-spec/reference/v8.json
Labels: skip changelog

#10952 Documentation and tests to clarify ['image'] and ['coalesce']
  src/style-spec/reference/v8.json
  test/integration/expression-tests/image/basic/test.json
  test/integration/expression-tests/image/coalesce/compare/test.json
  test/integration/expression-tests/image/coalesce/get/test.json
  test/integration/expression-tests/image/coalesce/to-string/test.json
  test/integration/lib/harness.js
Labels: docs :scroll:, skip changelog

#11000 Backport v2.4.1 fix from 0a35e9
  package.json
Labels: release blocker :no_entry:, skip changelog

#10989 Don't draw SDF image inside text
  src/style-spec/reference/v8.json
  src/symbol/quads.js
  test/integration/render-tests/text-field/formatted-text-with-sdf-image-non-sdf-image/expected.png
  test/integration/render-tests/text-field/formatted-text-with-sdf-image-non-sdf-image/style.json
Labels: bug :lady_beetle:

#11001 Fix mismatching symbol vertex layouts
  src/shaders/symbol_text_and_icon.vertex.glsl
Labels: release blocker :no_entry:, skip changelog

#10985 Markers update on terrain change
  debug/markers.html
  src/ui/map.js
  test/unit/terrain/terrain.test.js
Labels: bug :lady_beetle:, 3d :triangular_ruler:

#10998 Note that `prewarm()` is synchronous
  src/index.js
Labels: docs :scroll:, skip changelog

#11025 Execute DOM queue tasks immediately before initial map load
  src/ui/map.js
Labels: bug :lady_beetle:

#11017 Hide control button overflow
  src/css/mapbox-gl.css
Labels: bug :lady_beetle:

#11040 Hide X char in popup close button [accessibility]
  src/ui/popup.js
Labels: skip changelog

#11047 Upgrade to TinySDF v2 with a fix to CJK performance
  package.json
  src/render/glyph_manager.js
  test/unit/render/glyph_manager.test.js
  yarn.lock
Labels: release blocker :no_entry:

#11018 Update NavigationControl when min/maxZoom/Pitch change
  src/ui/map.js
  test/unit/ui/map.test.js
  test/unit/ui/map_events.test.js
Labels: bug :lady_beetle:
