Repository mapbox/mapbox-gl-js, pull requests merged in 2021-04, with the labels that each got.

#10527 Fog-sky blending
  src/shaders/_prelude_fog.fragment.glsl
  src/shaders/skybox.fragment.glsl
  src/shaders/skybox_gradient.fragment.glsl
Labels: 3d :triangular_ruler:

#10533 Switch fog to use window-scaled units
  debug/fog.html
  src/geo/transform.js
  src/style-spec/reference/v8.json
  src/style-spec/validate/validate_fog.js
  src/ui/free_camera.js
  test/unit/style-spec/fixture/fog-invalid-input.input.json
  test/unit/style-spec/fixture/fog-invalid-input.output-api-supported.json
  test/unit/style-spec/fixture/fog-invalid-input.output.json
  test/unit/style-spec/fixture/fog-invalid-range.input.json
  test/unit/style-spec/fixture/fog-invalid-range.output-api-supported.json
  test/unit/style-spec/fixture/fog-invalid-range.output.json
  test/unit/style/style.test.js
Labels: 3d :triangular_ruler:

#10537 Add haziness property to fog
  debug/fog.html
  src/css/mapbox-gl.css
  src/render/fog.js
  src/render/painter.js
  src/render/program.js
  src/shaders/_prelude.fragment.glsl
  src/shaders/_prelude_fog.fragment.glsl
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  src/style/fog.js
Labels: 3d :triangular_ruler:

#10544 Rename cameraMatrix --> fogTileMatrix
  src/geo/transform.js
  src/render/fog.js
  src/render/painter.js
  src/shaders/_prelude_fog.vertex.glsl
  src/style/fog_helpers.js
Labels: 3d :triangular_ruler:, skip changelog

#10553 Fix rendering bug in formatted images using case expressions
  src/symbol/symbol_layout.js
  test/integration/render-tests/text-field/formatted-images-case/expected.png
  test/integration/render-tests/text-field/formatted-images-case/style.json
Labels: bug :beetle:

#10566 Add 2D tests for fog
  test/integration/render-tests/fog/2d/background-color/expected.png
  test/integration/render-tests/fog/2d/background-color/style.json
  test/integration/render-tests/fog/2d/background-pattern/expected.png
  test/integration/render-tests/fog/2d/background-pattern/style.json
  test/integration/render-tests/fog/2d/basic/expected.png
  test/integration/render-tests/fog/2d/basic/style.json
  test/integration/render-tests/fog/2d/fill-color/expected.png
  test/integration/render-tests/fog/2d/fill-color/style.json
  test/integration/render-tests/fog/2d/fill-extrusion-pattern/expected.png
  test/integration/render-tests/fog/2d/fill-extrusion-pattern/style.json
  test/integration/render-tests/fog/2d/fill-extrusion/expected.png
  test/integration/render-tests/fog/2d/fill-extrusion/style.json
  test/integration/render-tests/fog/2d/fill-outline/expected.png
  test/integration/render-tests/fog/2d/fill-outline/style.json
  test/integration/render-tests/fog/2d/fill-pattern/expected.png
  test/integration/render-tests/fog/2d/fill-pattern/style.json
  test/integration/render-tests/fog/2d/heatmap/expected-half-float.png
  test/integration/render-tests/fog/2d/heatmap/expected.png
  test/integration/render-tests/fog/2d/heatmap/style.json
  test/integration/render-tests/fog/2d/hillshade/expected.png
  test/integration/render-tests/fog/2d/hillshade/style.json
  test/integration/render-tests/fog/2d/line-gradient/expected.png
  test/integration/render-tests/fog/2d/line-gradient/style.json
  test/integration/render-tests/fog/2d/line-pattern/expected.png
  test/integration/render-tests/fog/2d/line-pattern/style.json
  test/integration/render-tests/fog/2d/line-sdf/expected.png
  test/integration/render-tests/fog/2d/line-sdf/style.json
  test/integration/render-tests/fog/2d/line/expected.png
  test/integration/render-tests/fog/2d/line/style.json
  test/integration/render-tests/fog/2d/raster/expected.png
  test/integration/render-tests/fog/2d/raster/style.json
Labels: 3d :triangular_ruler:, skip changelog

#10570 Fix fill extrusion elevation encoding below sea level
  src/data/bucket/fill_extrusion_bucket.js
  src/shaders/_prelude_terrain.vertex.glsl
  src/style/style_layer/fill_extrusion_style_layer.js
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-over-border/expected.png
  test/integration/render-tests/fill-extrusion-terrain/flat-roof/expected.png
Labels: 3d :triangular_ruler:, bug :beetle:, mapbox.js → GL JS

#10588 Add style url input and button to reset stats
  debug/bucket-stats.html
Labels: skip changelog

#10584 Add a debug page with per-bucket/property GPU memory statistics
  debug/bucket-stats.html
Labels: skip changelog

#10598 Clarify mouseleave docs
  src/ui/events.js
Labels: docs :scroll:, skip changelog

#10606 Simplify haze evaluation
  src/render/fog.js
  src/render/painter.js
  src/shaders/_prelude.fragment.glsl
  src/shaders/_prelude_fog.fragment.glsl
  src/shaders/_prelude_fog.vertex.glsl
  src/shaders/terrain_raster.fragment.glsl
  src/shaders/terrain_raster.vertex.glsl
Labels: 3d :triangular_ruler:

#10625 Use prepublishOnly script to build the style spec.
  src/style-spec/package.json
Labels: skip changelog, workflow :nail_care:

#10611 Reuse one renderbuffer for all draping.
  src/terrain/terrain.js
Labels: 3d :triangular_ruler:, performance :zap:

#10631 Add new skybox render test
  test/integration/render-tests/skybox/cubemap-bottom-face/expected.png
  test/integration/render-tests/skybox/cubemap-bottom-face/style.json
Labels: skip changelog
