Repository mapbox/mapbox-gl-js, pull requests merged in 2021-12, with the labels that each got.

#11308 Relaxed tolerance allowing two failing render tests to pass on GL-Native linux
  test/integration/render-tests/debug/collision-fractional-zoom/style.json
  test/integration/render-tests/icon-text-fit/enlargen-both/style.json
Labels: skip changelog

#11321 Remove outdated DOM utilities and simplify marker SVG
  src/ui/control/attribution_control.js
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/logo_control.js
  src/ui/control/navigation_control.js
  src/ui/control/scale_control.js
  src/ui/handler/box_zoom.js
  src/ui/handler_manager.js
  src/ui/marker.js
  src/ui/popup.js
  src/util/dom.js
Labels: performance :zap:

#11325 doc: update link to projection spec
  src/style-spec/reference/v8.json
  src/ui/map.js
Labels: skip changelog

#11335 Apply height lift on globe with terrain in fill extrusion shaders
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
Labels: skip changelog

#11342 Use base height for fill extrusion lift
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
Labels: skip changelog

#11082 Improved transparency for line layers
  src/render/draw_fill_extrusion.js
  src/render/draw_hillshade.js
  src/render/draw_line.js
  src/render/draw_raster.js
  src/render/painter.js
  src/render/program/line_program.js
  src/shaders/line.fragment.glsl
  test/integration/render-tests/line-join/bevel-transparent/expected.png
  test/integration/render-tests/line-join/miter-transparent/expected.png
  test/integration/render-tests/line-join/round-transparent/expected.png
  test/integration/render-tests/line-opacity/function/expected.png
  test/integration/render-tests/line-opacity/literal/expected.png
  test/integration/render-tests/line-opacity/multiple-layers/expected.png
  test/integration/render-tests/line-opacity/multiple-layers/style.json
  test/integration/render-tests/line-triangulation/round/expected.png
  test/integration/render-tests/regressions/mapbox-gl-native#7714/expected.png
  test/integration/render-tests/terrain/transparent-lines/expected.png
  test/integration/render-tests/terrain/transparent-lines/style.json
Labels: feature :green_apple:

#11310 Fix canvas sizing with cases that use the css property transform
  debug/canvas-size.html
  src/ui/control/geolocate_control.js
  src/ui/control/scale_control.js
  src/ui/map.js
  test/unit/terrain/terrain.test.js
  test/unit/ui/hash.test.js
  test/unit/ui/map.test.js
  test/unit/ui/marker.test.js
  test/unit/ui/popup.test.js
  test/util/index.js
Labels: bug :lady_beetle:

#11339 Fix invalid LngLat with no currently loaded DEM tiles
  src/geo/transform.js
  test/unit/terrain/terrain.test.js
Labels: bug :lady_beetle:, 3d :triangular_ruler:

#11167 debounce rounding position on Marker
  src/ui/marker.js
  test/unit/ui/marker.test.js
Labels: feature :green_apple:

#11276 fix recursive dem tiles loading for 404s
  src/source/source_cache.js
  src/terrain/terrain.js
  test/integration/render-tests/fit-screen-coordinates/terrain/expected.png
  test/unit/source/source_cache.test.js
  test/unit/terrain/terrain.test.js
Labels: bug :lady_beetle:

#11328 Preloading tiles for camera animation
  debug/preload-tiles.html
  src/source/source_cache.js
  src/ui/camera.js
  src/ui/map.js
  test/release/index.js
  test/release/preload-tiles.html
  test/unit/source/source_cache.test.js
  test/unit/ui/camera.test.js
Labels: feature :green_apple:

#11260 Skip rendering of fully clipped symbol buckets
  src/data/bucket/symbol_bucket.js
  src/render/draw_symbol.js
  src/symbol/placement.js
Labels: skip changelog

#11240 Adding terrain to feature state debug
  debug/featurestate.html
Labels: skip changelog

#11330 Fix `undefined is not an object` warning (Safari)
  src/render/program.js
Labels: bug :lady_beetle:, environment-specific :desktop_computer:

#11360 Fix redundant title in Map Feedback attribution
  src/ui/control/attribution_control.js
Labels: bug :lady_beetle:
