Repository mapbox/mapbox-gl-js, pull requests merged in 2021-10, with the labels that each got.

#11067 Prevent fullscreen video source in iOS
  src/source/video_source.js
Labels: bug :lady_beetle:

#11029 Add gestureHandling map option to implement scroll zoom blocker
  debug/scroll_zoom_blocker.html
  src/css/mapbox-gl.css
  src/ui/default_locale.js
  src/ui/handler/scroll_zoom.js
  src/ui/map.js
  test/unit/ui/handler/scroll_zoom.test.js
Labels: feature :green_apple:, api :memo:, retrospective

#11086 Fixed conditional for _isFullscreen to accommodate for Safari
  src/ui/handler/scroll_zoom.js
Labels: skip changelog

#11087 Move blur event reset into non-touch handlers
  src/ui/handler/box_zoom.js
  src/ui/handler/click_zoom.js
  src/ui/handler/keyboard.js
  src/ui/handler/mouse.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler_manager.js
  test/unit/ui/handler/drag_pan.test.js
  test/unit/ui/handler/drag_rotate.test.js
Labels: bug :lady_beetle:

#11084 Fix an iOS15 issue where Safari tab bar interrupts panning
  src/ui/handler/box_zoom.js
  src/ui/handler/click_zoom.js
  src/ui/handler/keyboard.js
  src/ui/handler/mouse.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler_manager.js
  src/ui/map.js
  test/unit/ui/control/attribution.test.js
  test/unit/ui/control/logo.test.js
  test/unit/ui/handler/drag_pan.test.js
  test/unit/ui/handler/drag_rotate.test.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:
