Repository mapbox/mapbox-gl-js, pull requests merged in 2021-11, with the labels that each got.

#11200 add undistortion for equirectangular projection
  src/geo/projection/equirectangular.js
Labels: skip changelog

#11198 Fix bad shallow copy in filter splitting algorithm
  src/style-spec/feature_filter/index.js
  test/unit/style-spec/feature_filter.test.js
Labels: skip changelog

#11203 don't reload tiles when projection doesn't change
  src/geo/transform.js
  src/style/style.js
  test/unit/geo/transform.test.js
Labels: skip changelog

#11206 disable custom layers for non-mercator projections
  src/render/draw_custom.js
  src/style-spec/reference/v8.json
Labels: skip changelog

#11204 change how stylesheet and runtime projections interact
  src/geo/transform.js
  src/style/style.js
  src/ui/map.js
  test/integration/render-tests/satellite-v9/z0-albers/style.json
  test/unit/style/style.test.js
  test/unit/ui/map.test.js
Labels: release blocker :no_entry:, skip changelog

#11212 fix projection rotation adjustment when more than 180deg
  src/geo/projection/adjustments.js
  test/integration/render-tests/map-projections/rotation-correction-flip/expected.png
  test/integration/render-tests/map-projections/rotation-correction-flip/style.json
Labels: skip changelog

#11216 Use cylindrical projection functions when conic projections have cylindrical parallels
  src/geo/projection/albers.js
  src/geo/projection/cylindrical_equal_area.js
  src/geo/projection/index.js
  src/geo/projection/lambert.js
  src/ui/map.js
  test/integration/render-tests/map-projections/albers-cylindrical/expected.png
  test/integration/render-tests/map-projections/albers-cylindrical/style.json
  test/integration/render-tests/map-projections/lambert-cylindrical/expected.png
  test/integration/render-tests/map-projections/lambert-cylindrical/style.json
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#11219 fix raster tile seams with non-mercator projections
  src/source/tile_mesh.js
Labels: skip changelog

#11220 disable free camera apis with non-mercator projections
  src/ui/camera.js
Labels: skip changelog

#11209 Fix terrain cache not updating on `setFeatureState`
  src/source/source_state.js
  src/source/tile.js
  src/terrain/terrain.js
Labels: bug :lady_beetle:, release blocker :no_entry:

#11222 Better constraining and clamping for non-Mercator projections
  src/geo/projection/albers.js
  src/geo/projection/cylindrical_equal_area.js
  src/geo/projection/equal_earth.js
  src/geo/projection/equirectangular.js
  src/geo/projection/lambert.js
  src/geo/projection/natural_earth.js
  src/geo/projection/winkel_tripel.js
  src/geo/transform.js
Labels: skip changelog

#11224 fix hillshade layers with non-mercator projections
  src/render/draw_hillshade.js
  src/render/painter.js
  src/source/source_cache.js
  test/integration/render-tests/hillshade/projected/expected.png
  test/integration/render-tests/hillshade/projected/style.json
Labels: skip changelog

#11215 Disable sky after maximum projection transition to mercator
  src/geo/transform.js
  src/render/draw_sky.js
  src/style-spec/reference/v8.json
  src/ui/camera.js
  test/unit/geo/transform.test.js
Labels: skip changelog

#11225 improve lod tile loading for projections
  src/geo/projection/adjustments.js
  src/geo/transform.js
Labels: skip changelog

#11229 fix albers edge cases and lambert center
  src/geo/projection/albers.js
  src/geo/projection/cylindrical_equal_area.js
  src/geo/projection/lambert.js
  test/integration/render-tests/map-projections/lambert/configured/expected.png
  test/integration/render-tests/video/projected/expected.png
Labels: release blocker :no_entry:

#11195 Globe support for circle and fill extrusion layer vertex shaders
  src/shaders/_prelude.vertex.glsl
  src/shaders/circle.vertex.glsl
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
  src/shaders/heatmap.vertex.glsl
Labels: skip changelog

#11196 Allow setting order of custom attribution
  src/ui/control/attribution_control.js
  test/unit/ui/control/attribution.test.js
Labels: bug :lady_beetle:

#11286 ci: fix collect-stats job
  bench/gl-stats.js
  package.json
  yarn.lock
Labels: skip changelog

#11269 Fix rendering of denormalized strings with diacritics
  src/style-spec/expression/types/formatted.js
  test/integration/glyphs/Open Sans Semibold,Arial Unicode MS Bold/768-1023.pbf
  test/integration/render-tests/text-field/diacritics/expected.png
  test/integration/render-tests/text-field/diacritics/style.json
Labels: bug :lady_beetle:

#11292 Add perspective correction for image, canvas and video sources
  debug/image-perspective.html
  src/render/draw_raster.js
  src/render/program/raster_program.js
  src/shaders/raster.vertex.glsl
  src/source/canvas_source.js
  src/source/image_source.js
  src/source/video_source.js
  test/integration/render-tests/canvas/default/expected.png
  test/integration/render-tests/canvas/projected/expected.png
  test/integration/render-tests/image/default-projected/expected.png
  test/integration/render-tests/image/default-terrain/expected.png
  test/integration/render-tests/image/default/expected.png
  test/integration/render-tests/image/raster-brightness/expected.png
  test/integration/render-tests/image/raster-contrast/expected.png
  test/integration/render-tests/image/raster-hue-rotate/expected.png
  test/integration/render-tests/image/raster-opacity/expected.png
  test/integration/render-tests/image/raster-resampling/expected.png
  test/integration/render-tests/image/raster-saturation/expected.png
  test/integration/render-tests/image/raster-visibility/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#3010/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#7302/expected.png
  test/integration/render-tests/video/default/expected.png
  test/integration/render-tests/video/projected/expected.png
Labels: bug :lady_beetle:

#11301 Cherry-pick v2.6.1 CHANGELOG update
  CHANGELOG.md
Labels: skip changelog
