Repository mapbox/mapbox-gl-js, pull requests merged in 2021-06, with the labels that each got.

#10701 Terrain render loop: Prioritize large batches and lazy framebuffer switches
  src/render/painter.js
  src/terrain/terrain.js
Labels: 3d :triangular_ruler:, performance :zap:

#10731 Update README.md
  README.md
Labels: docs :scroll:, skip changelog

#10748 Adds a queryTerrainElevation example to API doc
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10754 Fix `"output": "terrainDepth"` render test option
  test/integration/lib/render.js
Labels: bug :beetle:, skip changelog, workflow :nail_care:

#10753 [projections] Adaptive geometry resampling for alternative projections
  src/data/load_geometry.js
Labels: skip changelog

#10765 [docs] Fix link to idle event
  src/ui/events.js
Labels: docs :scroll:, skip changelog

#10772 Remove strictly-increasing fog range validation
  src/render/painter.js
  src/style-spec/validate/validate_fog.js
  test/integration/render-tests/fog/2d/equal-range/expected.png
  test/integration/render-tests/fog/2d/equal-range/style.json
  test/integration/render-tests/fog/2d/inverted/expected.png
  test/integration/render-tests/fog/2d/inverted/style.json
  test/integration/render-tests/fog/terrain/equal-range/expected.png
  test/integration/render-tests/fog/terrain/equal-range/style.json
  test/integration/render-tests/fog/terrain/inverted/expected.png
  test/integration/render-tests/fog/terrain/inverted/style.json
  test/unit/style-spec/fixture/fog-invalid-range.input.json
  test/unit/style-spec/fixture/fog-invalid-range.output-api-supported.json
  test/unit/style-spec/fixture/fog-invalid-range.output.json
  test/unit/ui/map.test.js
Labels: bug :beetle:

#10732 Refactor projections code to get all tests passing
  build/generate-struct-arrays.js
  debug/projections.html
  debug/satellite.html
  src/data/array_types.js
  src/data/bounds_attributes.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/data/load_geometry.js
  src/geo/projection/albers.js
  src/geo/projection/index.js
  src/geo/projection/mercator.js
  src/geo/projection/sinusoidal.js
  src/geo/projection/tile_transform.js
  src/geo/projection/wgs84.js
  src/geo/projection/winkelTripel.js
  src/geo/projections/albers.js
  src/geo/transform.js
  src/render/draw_background.js
  src/render/draw_debug.js
  src/render/draw_fill.js
  src/render/draw_hillshade.js
  src/render/draw_line.js
  src/render/draw_raster.js
  src/render/painter.js
  src/source/canvas_source.js
  src/source/image_source.js
  src/source/source_cache.js
  src/source/tile.js
  src/source/video_source.js
  src/source/worker_tile.js
  src/terrain/terrain.js
  src/util/util.js
  test/integration/lib/render.js
  test/integration/render-tests/map-projections/albers-usa/expected.png
  test/integration/render-tests/map-projections/albers-usa/style.json
  test/unit/source/source_cache.test.js
Labels: skip changelog

#10774 Update links for docs on terrain and fog
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10780 [projections] Simplify and optimize tile transform code
  debug/projections.html
  src/data/load_geometry.js
  src/geo/projection/albers.js
  src/geo/projection/index.js
  src/geo/projection/mercator.js
  src/geo/projection/sinusoidal.js
  src/geo/projection/tile_transform.js
  src/geo/projection/wgs84.js
  src/geo/projection/winkelTripel.js
  src/geo/transform.js
  src/source/tile.js
Labels: skip changelog

#10782 Add more test coverage around fog transitions
  src/style/fog.js
  test/unit/ui/map.test.js
Labels: skip changelog

#10779 Increase strictness of style API validation.
  src/style-spec/validate_mapbox_api_supported.js
  test/unit/style-spec/fixture/bad-dasharray.output-api-supported.json
  test/unit/style-spec/fixture/bad-sky.output-api-supported.json
  test/unit/style-spec/fixture/fog-invalid-input.output-api-supported.json
  test/unit/style-spec/fixture/layers.output-api-supported.json
  test/unit/style-spec/fixture/non-mapbox-references.output-api-supported.json
  test/unit/style-spec/fixture/numbers.output-api-supported.json
  test/unit/style-spec/fixture/sources.input.json
  test/unit/style-spec/fixture/sources.output-api-supported.json
  test/unit/style-spec/fixture/text-field-format.output-api-supported.json
Labels: bug :beetle:

#10791 Cherry-pick v2.3.1 and style-spec@13.20.1 changelogs
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
Labels: skip changelog

#10793 Update CHANGELOG.md guidelines
  CONTRIBUTING.md
Labels: skip changelog

#10776 Fix anchor calculation for `line-center` placement when the anchor is very near to line segment endpoints
  src/data/array_types.js
  src/data/bucket/symbol_attributes.js
  src/symbol/get_anchors.js
  test/integration/glyphs/Arial Unicode MS Regular/0-255.pbf
  test/integration/render-tests/symbol-placement/line-center/anchor-near-to-endpoint/expected.png
  test/integration/render-tests/symbol-placement/line-center/anchor-near-to-endpoint/style.json
  test/integration/render-tests/symbol-placement/line-center/basic/expected.png
  test/integration/render-tests/symbol-placement/line-center/basic/style.json
  test/integration/render-tests/symbol-placement/line-center/expected.png
  test/integration/tiles/mapbox.mapbox-streets-v8/16-10533-25412.mvt
  test/unit/symbol/get_anchors.test.js
Labels: bug :beetle:

#10747 [projections] Fix performance regression in draw_background
  src/render/draw_background.js
  src/render/painter.js
Labels: skip changelog

#10807 Add tests for average terrain elevation sampling
  src/ui/map.js
  test/unit/terrain/terrain.test.js
Labels: skip changelog

#10809 Disable fog easing on initial load
  src/ui/map.js
  test/integration/render-tests/fog/terrain/basic/expected.png
  test/integration/render-tests/fog/terrain/equal-range/expected.png
  test/integration/render-tests/fog/terrain/inverted/expected.png
  test/integration/render-tests/fog/terrain/sky-composition/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#10763/expected.png
Labels: bug :beetle:
