Repository mapbox/mapbox-gl-js, pull requests merged in 2021-07, with the labels that each got.

#10812 Fix a potential incorrect vertex buffer access
  src/data/bucket/fill_extrusion_bucket.js
  test/integration/render-tests/fill-extrusion-pattern/opacity-terrain/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js-team#217/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js-team#217/style.json
Labels: bug :beetle:

#10821 Adds another inline `NavigationControl` example (with options)
  src/ui/control/navigation_control.js
Labels: docs :scroll:, skip changelog

#10824 Fix linter docs warnings
  src/terrain/elevation.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/map.js
  src/util/eased_variable.js
Labels: docs :scroll:, skip changelog

#10817 add geolocate bearing
  debug/debug.html
  src/css/mapbox-gl.css
  src/ui/control/geolocate_control.js
  test/unit/ui/control/geolocate.test.js
Labels: feature :green_apple:

#10643 [WIP] Small fixes for GL JS API ref docs
  src/ui/control/geolocate_control.js
  src/ui/marker.js
  src/ui/popup.js
Labels: Mapbox GL JS, report card

#10829 Add JS docs for mapboxgl.workerUrl
  src/index.js
Labels: docs :scroll:, skip changelog

#10813 Remove some unnecessary transforms
  src/render/painter.js
  src/render/program/heatmap_program.js
  src/shaders/heatmap_texture.vertex.glsl
Labels: skip changelog

#10838 Fix instances of `MapEventData` to `MapDataEvent`
  src/ui/events.js
Labels: docs :scroll:, skip changelog

#10837 Adds 'resource type' prefix for related items in GL JS API docs
  src/geo/lng_lat.js
  src/geo/mercator_coordinate.js
  src/index.js
  src/source/canvas_source.js
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/vector_tile_source.js
  src/source/video_source.js
  src/style/style_image.js
  src/style/style_layer/custom_style_layer.js
  src/ui/camera.js
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/navigation_control.js
  src/ui/events.js
  src/ui/free_camera.js
  src/ui/handler/box_zoom.js
  src/ui/handler/keyboard.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler/shim/dblclick_zoom.js
  src/ui/handler/shim/drag_pan.js
  src/ui/handler/shim/drag_rotate.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
Labels: docs :scroll:, skip changelog

#10850 Add a few more examples
  src/geo/edge_insets.js
  src/geo/lng_lat_bounds.js
  src/geo/mercator_coordinate.js
  src/source/canvas_source.js
  src/source/source_cache.js
  src/source/tile_cache.js
Labels: docs :scroll:

#10855 `require-example` linting
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/vector_tile_source.js
  src/source/video_source.js
  src/ui/camera.js
  src/ui/free_camera.js
Labels: docs :scroll:

#10830 Add documentation for `sourceId` to `MapDataEvent`
  src/ui/events.js
Labels: docs :scroll:, skip changelog

#10868 Non-test content updates
  README.md
  src/index.js
  src/source/geojson_source.js
  src/source/source_cache.js
  src/ui/camera.js
  src/ui/events.js
  src/ui/handler_manager.js
  src/ui/map.js
  src/ui/marker.js
  src/util/web_worker.js
  src/util/window.js
  test/integration/README.md
  test/unit/style-spec/expression.test.js
Labels: skip changelog

#10858 Resolves `eslint-plugin-jsdoc` test failures
  .eslintrc
  src/geo/lng_lat.js
  src/geo/mercator_coordinate.js
  src/index.js
  src/source/canvas_source.js
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/vector_tile_source.js
  src/source/video_source.js
  src/style-spec/reference/v8.json
  src/style/style_image.js
  src/style/style_layer/custom_style_layer.js
  src/ui/camera.js
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/navigation_control.js
  src/ui/events.js
  src/ui/free_camera.js
  src/ui/handler/box_zoom.js
  src/ui/handler/keyboard.js
  src/ui/handler/shim/dblclick_zoom.js
  src/ui/handler/shim/drag_pan.js
  src/ui/handler/shim/drag_rotate.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
  src/util/browser.js
  src/util/dispatcher.js
  src/util/evented.js
  test/release/index.js
Labels: docs :scroll:, skip changelog

#10864 `jsdoc/check-types` linting
  .circleci/config.yml
  .eslintrc
  package.json
  src/index.js
  src/source/geojson_source.js
  src/ui/control/navigation_control.js
  src/ui/map.js
  src/ui/popup.js
Labels: docs :scroll:

#10823 Add default values to some map API methods
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10890 Updates to `flyTo` docs
  src/ui/camera.js
Labels: docs :scroll:

#10870 "jsdoc/require-property-description" rule and fixes to events.js
  src/style/style_image.js
  src/ui/events.js
Labels: docs :scroll:

#10844 Break down map methods and events into sections for docs
  src/ui/camera.js
  src/ui/events.js
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10894 Combine line shaders
  src/data/array_types.js
  src/data/bucket/line_attributes_ext.js
  src/data/bucket/line_bucket.js
  src/render/draw_line.js
  src/render/program/line_program.js
  src/render/program/program_uniforms.js
  src/shaders/line.fragment.glsl
  src/shaders/line.vertex.glsl
  src/shaders/line_gradient.fragment.glsl
  src/shaders/line_gradient.vertex.glsl
  src/shaders/line_sdf.fragment.glsl
  src/shaders/line_sdf.vertex.glsl
  src/shaders/shaders.js
  src/style-spec/reference/v8.json
  src/style/style_layer/line_style_layer.js
  test/integration/render-tests/line-gradient/gradient-with-dash/expected.png
  test/integration/render-tests/line-gradient/gradient-with-dash/style.json
Labels: feature :green_apple:

#10707 Add and update `ESLint` tests for Mapbox GL JS API docs
  .circleci/config.yml
  .eslintrc
  README.md
  package.json
  src/geo/edge_insets.js
  src/geo/lng_lat.js
  src/geo/lng_lat_bounds.js
  src/geo/mercator_coordinate.js
  src/geo/transform.js
  src/gl/vertex_buffer.js
  src/index.js
  src/source/canvas_source.js
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/source_cache.js
  src/source/tile_cache.js
  src/source/vector_tile_source.js
  src/source/video_source.js
  src/style/query_geometry.js
  src/style/style.js
  src/style/style_image.js
  src/style/style_layer/custom_style_layer.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  src/ui/camera.js
  src/ui/control/attribution_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/navigation_control.js
  src/ui/control/scale_control.js
  src/ui/events.js
  src/ui/free_camera.js
  src/ui/handler/box_zoom.js
  src/ui/handler/keyboard.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler/shim/dblclick_zoom.js
  src/ui/handler/shim/drag_pan.js
  src/ui/handler/shim/drag_rotate.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/handler_manager.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
  src/util/ajax.js
  src/util/browser.js
  src/util/dispatcher.js
  src/util/eased_variable.js
  src/util/evented.js
  src/util/web_worker.js
  src/util/window.js
  test/integration/README.md
  test/integration/lib/expression.js
  test/unit/style-spec/expression.test.js
  yarn.lock
Labels: docs :scroll:, skip changelog

#10905 Add event listener for webkitfullscreenchange to resize maps when entering full screen in Safari
  src/ui/map.js
Labels: bug :beetle:
