Repository mapbox/mapbox-gl-js, pull requests merged in 2021-05, with the labels that each got.

#10509 update generate-release-list for new Octokit
  build/generate-release-list.js
Labels: skip changelog

#10639 Remove a single "Related" link from the bottom of `Map` API doc
  src/ui/map.js
Labels: skip changelog

#10602 Add queryTerrainElevation exaggeration option
  debug/3d-playground.html
  debug/threejs-antenna.html
  src/geo/transform.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  src/ui/map.js
  test/release/index.js
Labels: feature :green_apple:

#10641 Consistify `Options object.` descriptor in GL JS API docs
  src/ui/camera.js
  src/ui/handler/shim/drag_pan.js
Labels: skip changelog

#10612 Data-driven `text-line-height`
  src/style-spec/reference/v8.json
  src/style/style_layer/symbol_style_layer_properties.js
  src/symbol/symbol_layout.js
  test/integration/render-tests/text-line-height/data-driven/expected.png
  test/integration/render-tests/text-line-height/data-driven/style.json
Labels: feature :green_apple:

#10591 Data-driven `line-dasharray` and `line-cap`
  build/generate-struct-arrays.js
  debug/dasharray.html
  src/data/array_types.js
  src/data/bucket.js
  src/data/bucket/dash_attributes.js
  src/data/bucket/line_bucket.js
  src/data/program_configuration.js
  src/render/draw_line.js
  src/render/image_atlas.js
  src/render/line_atlas.js
  src/render/program/line_program.js
  src/shaders/line_sdf.fragment.glsl
  src/shaders/line_sdf.vertex.glsl
  src/source/tile.js
  src/source/worker_source.js
  src/source/worker_tile.js
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  src/style/properties.js
  src/style/style_layer/line_style_layer_properties.js
  test/integration/render-tests/line-cap/data-driven/expected.png
  test/integration/render-tests/line-cap/data-driven/style.json
  test/integration/render-tests/line-dasharray/data-driven/composite-dash-composite-cap/expected.png
  test/integration/render-tests/line-dasharray/data-driven/composite-dash-composite-cap/style.json
  test/integration/render-tests/line-dasharray/data-driven/const-dash-feature-cap/expected.png
  test/integration/render-tests/line-dasharray/data-driven/const-dash-feature-cap/style.json
  test/integration/render-tests/line-dasharray/data-driven/feature-dash-const-cap/expected.png
  test/integration/render-tests/line-dasharray/data-driven/feature-dash-const-cap/style.json
  test/integration/render-tests/line-dasharray/data-driven/feature-dash-feature-cap/expected.png
  test/integration/render-tests/line-dasharray/data-driven/feature-dash-feature-cap/style.json
  test/unit/render/line_atlas.test.js
  test/unit/style-spec/fixture/functions.output-api-supported.json
  test/unit/style-spec/fixture/functions.output.json
Labels: feature :green_apple:

#9561 fix dashed lines with square line caps
  src/data/bucket/line_bucket.js
  src/render/draw_line.js
  src/render/line_atlas.js
  test/ignores.json
  test/integration/render-tests/line-dasharray/case/square/expected.png
Labels: bug :beetle:

#10651 Release testing fixes
  test/release/index.js
Labels: release blocker :no_entry:

#10654 Rebuild flow types
  src/style-spec/types.js
Labels: skip changelog

#10666 Fix a potential mobile GPU issue on zero-value dashes
  src/shaders/line_sdf.vertex.glsl
Labels: skip changelog

#10622 Force line label to keep unflipped in defined rotating angle range to suppress flickering
  src/data/array_types.js
  src/data/bucket/symbol_attributes.js
  src/data/bucket/symbol_bucket.js
  src/symbol/projection.js
  src/util/struct_array.js.ejs
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-cross-5-degree-edge/expected.png
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-cross-5-degree-edge/style.json
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-glyphs/expected.png
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-glyphs/style.json
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-mixed-CJK/expected.png
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-mixed-CJK/style.json
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-single-glyph/expected.png
  test/integration/render-tests/text-keep-upright/line-placement-flip-retain-single-glyph/style.json
Labels: feature :green_apple:

#10669 Fix line atlas not caching dashes properly
  src/render/line_atlas.js
  test/unit/render/line_atlas.test.js
Labels: skip changelog

#10671 Cherry-pick 147901
  src/render/line_atlas.js
  test/unit/render/line_atlas.test.js
Labels: release blocker :no_entry:

#10676 Add coments to transform instance variables
  src/geo/transform.js
Labels: 3d :triangular_ruler:, skip changelog

#10645 Small fixes to GL JS API docs (product docs report card)
  src/ui/handler/scroll_zoom.js
  src/ui/handler/shim/touch_zoom_rotate.js
Labels: docs :scroll:, skip changelog

#10680 Fix transform type error
  src/geo/transform.js
Labels: bug :beetle:, skip changelog

#10690 Add a render test for validating transparent background layers on terrain
  test/integration/render-tests/terrain/background-clear-optimization/expected.png
  test/integration/render-tests/terrain/background-clear-optimization/style.json
Labels: skip changelog

#10691 Update sources and markers while fog transitioning
  src/ui/map.js
Labels: 3d :triangular_ruler:, bug :beetle:, skip changelog

#10697 Update `layer.source` description for `addLayer`
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10703 Fix precision issue in gradient skybox shader
  src/shaders/skybox_gradient.fragment.glsl
Labels: bug :beetle:

#10702 Combines map instance members: `once`, `off` (to match `on`)
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10704 Fix test release page state management
  build/print-release-url.js
  test/release/index.js
Labels: bug :beetle:, skip changelog

#10712 Add code comments and examples to `Map` inline example in API docs
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#10718 Implement dual ESM + CJS compatibility in style-spec
  .gitignore
  src/style-spec/package.json
  src/style-spec/rollup.config.js
  test/build/style-spec.test.js
Labels: skip changelog

#10709 Fix collision boxes for text with variable placement
  src/data/array_types.js
  src/data/bucket/symbol_attributes.js
  src/render/draw_symbol.js
  src/symbol/placement.js
  src/symbol/symbol_layout.js
  test/integration/render-tests/debug/collision-overscaled-fractional-zoom-variable-anchor/expected.png
  test/integration/render-tests/debug/collision-overscaled-fractional-zoom-variable-anchor/style.json
Labels: bug :beetle:

#10706 Replace two broken images on GL JS README.md
  README.md
Labels: docs :scroll:, skip changelog

#10717 [Docs] Update customAttribution code example and parameter description
  src/ui/control/attribution_control.js
Labels: docs :scroll:, skip changelog
