Repository mapbox/mapbox-gl-js, pull requests merged in 2021-01, with the labels that each got.

#10203 Return a promise in "once" if no listener provided
  debug/video-export.html
  src/ui/map.js
  src/util/evented.js
  test/unit/util/evented.test.js
Labels: api :memo:, feature :green_apple:

#10281 Fix evented.listens to return false when no listener exists
  src/util/evented.js
  test/unit/util/evented.test.js
Labels: bug :beetle:

#10296 Fix blurry map-aligned labels on terrain
  src/render/program/symbol_program.js
  test/integration/render-tests/debug/terrain/collision-pitch-with-map-text-and-icon/expected.png
  test/integration/render-tests/debug/terrain/collision-pitch-with-map/expected.png
  test/integration/render-tests/text-pitch-alignment/map-text-rotation-alignment-map-terrain/expected.png
  test/integration/render-tests/text-pitch-alignment/map-text-rotation-alignment-viewport-terrain/expected.png
Labels: bug :beetle:

#10285 Run check-bundle-size script after deploying release to avoid a bug
  .circleci/config.yml
Labels: skip changelog

#10231 Fix forked PRs
  bench/lib/access_token.js
  build/check-bundle-size.js
  debug/access_token.js
  test/browser/drag.test.js
  test/browser/zoom.test.js
  test/release/index.js
Labels: skip changelog

#10306 Hardcode fallback token in release test page
  test/release/index.js
Labels: skip changelog

#10308 Revert usage of restricted access token for release testing
  test/release/index.js
Labels: skip changelog

#10293 Fill extrusion querying with terrain
  build/generate-struct-arrays.js
  debug/extrusion-query.html
  src/data/array_types.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/dem_data.js
  src/data/feature_index.js
  src/shaders/_prelude_terrain.vertex.glsl
  src/style/query_geometry.js
  src/style/style_layer.js
  src/style/style_layer/fill_extrusion_style_layer.js
  src/terrain/elevation.js
  test/integration/query-tests/terrain/fill-extrusion-flat-roof/border-overlap/expected.json
  test/integration/query-tests/terrain/fill-extrusion-flat-roof/border-overlap/style.json
  test/integration/query-tests/terrain/fill-extrusion-flat-roof/default/expected.json
  test/integration/query-tests/terrain/fill-extrusion-flat-roof/default/style.json
  test/unit/util/struct_array.test.js
Labels: bug :beetle:

#10311 Use fallback token with render tests to fix npm commands
  package.json
  test/integration/lib/render.js
Labels: skip changelog

#10300 Fix an issue with small-radius clusters and uncap clusterMaxZoom
  package.json
  src/source/geojson_source.js
  test/integration/render-tests/geojson/clustered-max-zoom/expected.png
  test/integration/render-tests/geojson/clustered-max-zoom/style.json
  yarn.lock
Labels: bug :beetle:

#10307 Avoid building from main in check bundle size
  .circleci/config.yml
  build/check-bundle-size.js
Labels: skip changelog

#10313 Add a few more release testing pages and add 3d test page variants
  test/release/3d-playground.html
  test/release/README.md
  test/release/index.css
  test/release/index.html
  test/release/index.js
  test/release/skybox-gradient.html
Labels: skip changelog, workflow :nail_care:

#10320 Guard against no prior check being found in check-bundle-size
  build/check-bundle-size.js
Labels: skip changelog

#10284 Fix #10033
  src/data/bucket/pattern_attributes.js
  src/data/program_configuration.js
  test/integration/render-tests/regressions/mapbox-gl-js#10033/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#10033/style.json
  test/integration/sprites/128px-grey-square.png
  test/integration/sprites/32px-grey-square.png
  test/integration/sprites/64px-grey-square.png
Labels: bug :beetle:

#10315 Fix fullscreen fill-extrusion querying at low pitch
  src/style/query_geometry.js
  src/util/util.js
  test/integration/query-tests/fill-extrusion/top-down/expected.json
  test/integration/query-tests/fill-extrusion/top-down/style.json
Labels: bug :beetle:

#10298 Port high resolution local SDFs
  package.json
  src/render/glyph_atlas.js
  src/render/glyph_manager.js
  src/style/style.js
  src/style/style_glyph.js
  src/symbol/quads.js
  src/symbol/shaping.js
  src/ui/map.js
  test/expected/text-shaping-default.json
  test/expected/text-shaping-images-horizontal.json
  test/expected/text-shaping-images-vertical.json
  test/expected/text-shaping-linebreak.json
  test/expected/text-shaping-newline.json
  test/expected/text-shaping-newlines-in-middle.json
  test/expected/text-shaping-null.json
  test/expected/text-shaping-spacing.json
  test/expected/text-shaping-zero-width-space.json
  test/unit/render/glyph_manager.test.js
Labels: GL native → GL JS, feature :green_apple:

#10327 Add two more pages on release testing
  test/release/index.js
Labels: workflow :nail_care:

#10294 Wait for sprite to load before parsing tiles
  src/source/geojson_worker_source.js
  src/source/vector_tile_worker_source.js
  src/source/worker.js
  src/style/style.js
  test/unit/source/geojson_worker_source.test.js
  test/unit/source/vector_tile_worker_source.test.js
Labels: bug :beetle:

#10304 shift horizon towards center to reduce the number of tiles loaded
  src/geo/transform.js
  src/symbol/collision_index.js
  test/ignores.json
  test/integration/query-tests/symbol-features-in/tilted-outside/style.json
  test/integration/render-tests/debug/collision-high-pitched-fractional-zoom/expected.png
  test/integration/render-tests/debug/collision-high-pitched/expected.png
  test/integration/render-tests/debug/terrain/camera-under-terrain/expected.png
  test/integration/render-tests/fit-screen-coordinates/horizon/expected.png
  test/integration/render-tests/skybox/atmosphere-color/expected.png
  test/integration/render-tests/skybox/atmosphere-horizon/expected.png
  test/integration/render-tests/skybox/atmosphere-intensity/low/expected.png
  test/integration/render-tests/skybox/atmosphere-intensity/medium/expected.png
  test/integration/render-tests/skybox/atmosphere-mie/expected.png
  test/integration/render-tests/skybox/atmosphere-padding/expected.png
  test/integration/render-tests/skybox/atmosphere-update/expected.png
  test/integration/render-tests/skybox/compositing/alpha-blend/expected.png
  test/integration/render-tests/skybox/compositing/base/expected.png
  test/integration/render-tests/skybox/fill-extrusion-light/horizon-north-east/expected.png
  test/integration/render-tests/skybox/fill-extrusion-light/horizon-south-west/expected.png
  test/integration/render-tests/skybox/fill-extrusion-light/sun-override/expected.png
  test/integration/render-tests/skybox/gradient/east/expected.png
  test/integration/render-tests/skybox/gradient/linear/expected.png
  test/integration/render-tests/skybox/gradient/north/expected.png
  test/integration/render-tests/skybox/gradient/padding/expected.png
  test/integration/render-tests/skybox/gradient/south/expected.png
  test/integration/render-tests/skybox/gradient/update/expected.png
  test/integration/render-tests/skybox/gradient/west/expected.png
  test/integration/render-tests/skybox/horizon-visibility/base/expected.png
  test/integration/render-tests/skybox/horizon-visibility/padding/expected.png
  test/integration/render-tests/symbol-distance-fade/expected.png
  test/integration/render-tests/text-pitch-alignment/viewport-text-rotation-alignment-map/expected.png
  test/unit/source/source_cache.test.js
  test/unit/terrain/terrain.test.js
Labels: performance :zap:

#10332 Collect GL and Bundle size stats. Revert #10161
  .circleci/config.yml
Labels: skip changelog

#10344 Update yarn.lock
  yarn.lock
Labels: skip changelog
