Repository mapbox/mapbox-gl-js, pull requests merged in 2021-02, with the labels that each got.

#10354 Update SDK version check for CI
  .circleci/config.yml
Labels: skip changelog

#10347 Fix building flat roofs with user provided data when terrain is enabled
  src/data/bucket/fill_extrusion_bucket.js
  src/render/draw_fill_extrusion.js
  test/integration/render-tests/regressions/mapbox-gl-js#10170/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#10170/style.json
  test/integration/tiles/13-7536-4912.terrain.png
  test/integration/tiles/13-7536-4913.terrain.png
  test/integration/tiles/13-7536-4914.terrain.png
  test/release/extrusion-query.html
  test/release/index.js
Labels: bug :beetle:

#10353 Update changelog for v2.1.0
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#10371 Pull changelog for v2.1.1 to main
  CHANGELOG.md
Labels: skip changelog

#10367 Switch dev environment to native ESM to support Node 12+
  .circleci/config.yml
  .gitignore
  bench/rollup_config_benchmarks.js
  build/check-bundle-size.js
  build/diff-tarball.js
  build/generate-access-token-script.js
  build/generate-flow-typed-style-spec.js
  build/generate-release-list.js
  build/node-loader.js
  build/rollup_plugins.js
  build/run-node
  build/run-tap
  build/test/build-tape.js
  dist/package.json
  package.json
  postcss.config.cjs
  rollup.config.js
  src/render/painter.js
  src/render/program.js
  src/shaders/index.js
  src/shaders/shaders.js
  src/style-spec/package.json
  src/style-spec/rollup.config.js
  test/build/min.test.js
  test/build/style-spec.test.js
  test/expression.test.js
  test/integration/lib/expression.js
  test/integration/lib/generate-fixture-json.js
  test/integration/lib/harness.js
  test/integration/lib/localize-urls.js
  test/integration/lib/server.js
  test/integration/testem/package.json
  test/integration/testem/testem.js
  test/unit/changelog.js
  test/unit/data/fill_bucket.test.js
  test/unit/data/line_bucket.test.js
  test/unit/data/load_geometry.test.js
  test/unit/data/symbol_bucket.test.js
  test/unit/data/vertex_buffer.test.js
  test/unit/source/tile.test.js
  test/unit/source/vector_tile_source.test.js
  test/unit/source/vector_tile_worker_source.test.js
  test/unit/style-spec/migrate.test.js
  test/unit/style-spec/validate.test.js
  test/unit/style-spec/validate_mapbox_api_supported.test.js
  test/unit/style/load_glyph_range.test.js
  test/unit/symbol/shaping.test.js
  test/unit/ui/control/attribution.test.js
  test/unit/ui/control/geolocate.test.js
  test/unit/util/classify_rings.test.js
  test/util/index.js
  yarn.lock
Labels: workflow :nail_care:

#10321 Dedupe calls to performance.measure
  src/source/geojson_worker_source.js
  src/source/vector_tile_worker_source.js
  src/util/performance.js
  test/unit/source/geojson_worker_source.test.js
  test/unit/source/vector_tile_worker_source.test.js
Labels: bug :beetle:

#10348 Use an upload script for publish step
  .circleci/config.yml
  build/upload.sh
Labels: skip changelog

#10361 Show the Mapbox logo when no style is provided
  src/ui/control/logo_control.js
  test/unit/ui/control/logo.test.js
Labels: bug :beetle:

#10384 Upgrade most dev dependencies
  .eslintrc
  bench/.eslintrc
  build/test/build-tape.js
  debug/.eslintrc
  debug/iframe-blob.html
  package.json
  src/style-spec/.eslintrc
  src/ui/camera.js
  test/.eslintrc
  test/integration/lib/json-diff.js
  test/suite_implementation.js
  test/util/browser_write_file.js
  yarn.lock
Labels: skip changelog

#10351 Integration test setup upgrades
  package.json
  test/integration/image/marker_18x18.png
  test/integration/lib/generate-fixture-json.js
  test/integration/lib/operation-handlers.js
  test/integration/lib/query.js
  test/integration/lib/render.js
  test/integration/render-tests/debug/padding/ease-to-top-distort/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#5740/expected.png
  test/integration/render-tests/runtime-styling/image-update-icon/expected.png
  test/integration/render-tests/runtime-styling/image-update-icon/style.json
  test/integration/render-tests/runtime-styling/image-update-pattern/expected.png
  test/integration/render-tests/runtime-styling/image-update-pattern/style.json
  yarn.lock
Labels: skip changelog, testing :100:, workflow :nail_care:

#10387 Clean up unused dependencies
  .circleci/config.yml
  bench/gl-stats.js
  package.json
  test/build/transpilation/package.json
  yarn.lock
Labels: skip changelog

#10386 account for padding in getBounds
  debug/padding.html
  src/geo/transform.js
  src/ui/camera.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: bug :beetle:

#10395 Fix broken links in Contributing document
  CONTRIBUTING.md
Labels: skip changelog

#10390 Switch to using alphabetic baseline for local glyphs.
  package.json
  src/render/glyph_manager.js
  yarn.lock
Labels: bug :beetle:

#10412 Add additional resets for culling state
  src/render/painter.js
Labels: bug :beetle:
