Repository mapbox/mapbox-gl-js, pull requests merged in 2022-06, with the labels that each got.

#11948 Simplify and cleanup dynamic vertex buffer bindings
  src/render/draw_circle.js
  src/render/draw_collision_debug.js
  src/render/draw_debug.js
  src/render/draw_fill_extrusion.js
  src/render/draw_heatmap.js
  src/render/draw_line.js
  src/render/draw_symbol.js
  src/render/program.js
  src/render/vertex_array_object.js
Labels: refactoring :building_construction:, skip changelog

#11942 Clone stylesheet to allow toggling different styles with `setStyle`
  src/style/style.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#11952 Do not set the map language to the user's preferred language by default
  src/source/load_tilejson.js
  src/source/vector_tile_source.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: release blocker :no_entry:, skip changelog

#11950 Bump minimist to 1.2.6 as per #11944
  src/style-spec/package.json
Labels: skip changelog

#11963 Reload tiles after TileJSON is loaded in VectorTileSource#setSourceProperty
  src/source/vector_tile_source.js
  src/ui/map.js
  test/unit/source/vector_tile_source.test.js
Labels: release blocker :no_entry:, skip changelog

#11965 Update s3 link to lower res video
  debug/globe-with-video.html
Labels: skip changelog

#11970 Updates for v2.9.0-beta.2
  CHANGELOG.md
  debug/globe-with-video.html
  package.json
  src/source/vector_tile_source.js
  src/style-spec/package.json
  src/ui/map.js
  test/unit/source/vector_tile_source.test.js
Labels: skip changelog

#11927 Support pure color with `line-trim-offset` property
  src/render/draw_line.js
  src/shaders/line.fragment.glsl
  src/shaders/line.vertex.glsl
  src/style-spec/reference/v8.json
  src/style-spec/validate/validate_layer.js
  test/integration/render-tests/line-trim-offset/pure-color-end-offset/expected.png
  test/integration/render-tests/line-trim-offset/pure-color-end-offset/style.json
  test/integration/render-tests/line-trim-offset/pure-color-mid-offset/expected.png
  test/integration/render-tests/line-trim-offset/pure-color-mid-offset/style.json
  test/integration/render-tests/line-trim-offset/pure-color-round-cap/expected.png
  test/integration/render-tests/line-trim-offset/pure-color-round-cap/style.json
  test/integration/render-tests/line-trim-offset/pure-color-shared-source/expected.png
  test/integration/render-tests/line-trim-offset/pure-color-shared-source/style.json
  test/integration/render-tests/line-trim-offset/pure-color-start-offset/expected.png
  test/integration/render-tests/line-trim-offset/pure-color-start-offset/style.json
  test/integration/render-tests/line-trim-offset/pure-color-with-dash/expected.png
  test/integration/render-tests/line-trim-offset/pure-color-with-dash/style.json
Labels: feature :green_apple:

#11990 Add render tests for validating fog parameters on style change
  test/ignores.json
  test/integration/render-tests/fog/switch-style-disable/expected.png
  test/integration/render-tests/fog/switch-style-disable/style.json
  test/integration/render-tests/fog/switch-style-reset-defaults/expected.png
  test/integration/render-tests/fog/switch-style-reset-defaults/style.json
Labels: skip changelog

#11999 Fix symbols not rendering on globe after style change
  src/ui/map.js
  test/integration/render-tests/globe/globe-set-style/symbol/expected.png
  test/integration/render-tests/globe/globe-set-style/symbol/style.json
Labels: bug :lady_beetle:, release blocker :no_entry:, skip changelog

#12005 Fix precision errors in pack/unpack depth
  src/shaders/_prelude.fragment.glsl
  src/shaders/_prelude_terrain.vertex.glsl
Labels: bug :lady_beetle:

#12004 Add extra constrain to avoid unnecessary line shader calculations if 'line-trim-offset' is not set
  src/render/program/line_program.js
  src/shaders/line.fragment.glsl
  src/shaders/line.vertex.glsl
Labels: skip changelog

#12002 Doc changes for globe view
  src/style-spec/reference/v8.json
  src/ui/map.js
Labels: skip changelog

#12008 Relaxed behavior for unsupported globe APIs
  src/ui/camera.js
  src/ui/map.js
  test/unit/ui/camera.test.js
  test/unit/ui/map.test.js
Labels: skip changelog

#11957 Prevent flickering of symbols during globe mercator transition
  src/data/bucket.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/geo/projection/adjustments.js
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/geo/projection/projection.js
  src/geo/projection/projection_util.js
  src/geo/transform.js
  src/render/draw_circle.js
  src/render/draw_collision_debug.js
  src/render/draw_fill_extrusion.js
  src/render/draw_heatmap.js
  src/render/draw_symbol.js
  src/render/program/collision_program.js
  src/render/program/symbol_program.js
  src/source/worker_tile.js
  src/symbol/collision_index.js
  src/symbol/placement.js
  src/symbol/projection.js
  src/terrain/terrain.js
  src/ui/map.js
  test/util/create_symbol_layer.js
Labels: skip changelog

#11992 Fix setting fog default values when calling setStyle
  src/style/fog.js
  src/style/style.js
  test/ignores.json
  test/integration/render-tests/fog/set-fog-default-toggling/expected.png
  test/integration/render-tests/fog/set-fog-default-toggling/style.json
  test/integration/render-tests/fog/switch-style-disable/style.json
  test/integration/render-tests/fog/switch-style-reset-defaults/style.json
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:, release blocker :no_entry:

#11931 Refactor circle and heatmap layer rendering on globe
  src/data/array_types.js
  src/data/bucket/circle_attributes.js
  src/data/bucket/circle_bucket.js
  src/render/program/circle_program.js
  src/render/program/heatmap_program.js
  src/shaders/circle.vertex.glsl
  src/shaders/heatmap.vertex.glsl
  src/style/query_geometry.js
  src/style/style_layer/circle_style_layer.js
  test/ignores.json
  test/integration/render-tests/globe/globe-circle/change-projection/set-projection/expected.png
  test/integration/render-tests/globe/globe-circle/change-projection/set-style/expected.png
  test/integration/render-tests/globe/globe-circle/default-zoomed/expected.png
  test/integration/render-tests/globe/globe-circle/default/expected.png
  test/integration/render-tests/globe/globe-circle/horizontal/expected.png
  test/integration/render-tests/globe/globe-circle/near-horizon/expected.png
  test/integration/render-tests/globe/globe-circle/near-transition/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-map-scaled-map-aligned/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-map-scaled-viewport-aligned/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-viewport-scaled-map-aligned/expected.png
  test/integration/render-tests/globe/globe-heatmap/default-zoomed/expected.png
  test/integration/render-tests/globe/globe-heatmap/default/expected.png
  test/integration/render-tests/globe/globe-heatmap/horizontal/expected.png
  test/integration/render-tests/globe/globe-heatmap/near-horizon/expected.png
  test/integration/render-tests/globe/globe-heatmap/vertical/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-globe/expected.png
Labels: skip changelog

#12012 Release v2.9.0 final
  CHANGELOG.md
  package.json
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#12015 Trivial: one liner that blocks native shader generation
  src/shaders/circle.vertex.glsl
Labels: skip changelog

#12017 fix line-trim-offset shader
  src/render/program/line_program.js
  src/shaders/line.fragment.glsl
Labels: bug :lady_beetle:, release blocker :no_entry:

#12020 Reuse canvas in custom source debug page for performance
  debug/custom-source.html
Labels: skip changelog

#12019 v2.9.1 changelog and version bump
  CHANGELOG.md
  package.json
Labels: skip changelog

#12022 flat-roof-ao render test transition duration set to 0
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-ao/expected.png
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-ao/style.json
Labels: skip changelog

#11987 Refactoring globe tile position calculation
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/geo/transform.js
  src/render/program/circle_program.js
  src/render/program/heatmap_program.js
  src/style/query_geometry.js
  src/terrain/draw_terrain_raster.js
  src/terrain/terrain.js
  src/ui/handler/scroll_zoom.js
Labels: refactoring :building_construction:, skip changelog

#11985 Add shadow rendering to shaders
  src/shaders/_prelude.fragment.glsl
  src/shaders/_prelude_shadow.fragment.glsl
  src/shaders/_prelude_terrain.vertex.glsl
  src/shaders/fill_extrusion.fragment.glsl
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_depth.fragment.glsl
  src/shaders/fill_extrusion_depth.vertex.glsl
  src/shaders/ground_shadow.fragment.glsl
  src/shaders/ground_shadow.vertex.glsl
  src/shaders/shaders.js
  src/shaders/terrain_raster.fragment.glsl
  src/shaders/terrain_raster.vertex.glsl
Labels: skip changelog

#12030 Fix shadows PCF precision issues in android
  src/shaders/_prelude_shadow.fragment.glsl
Labels: skip changelog

#12050 Optimize tile calculations for globe
  src/geo/projection/globe_util.js
  src/terrain/draw_terrain_raster.js
Labels: performance :zap:

#12054 Adjust ground shadow strength based on fog opacity
  src/shaders/ground_shadow.fragment.glsl
  src/shaders/ground_shadow.vertex.glsl
Labels: skip changelog
