Repository mapbox/mapbox-gl-js, pull requests merged in 2022-01, with the labels that each got.

#11289 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: skip changelog

#11371 Coalesce on missing images to return ResolvedImage instead of String
  src/style-spec/expression/definitions/coalesce.js
  test/integration/expression-tests/image/coalesce/test.json
Labels: skip changelog

#11376 Relaxed tolerance allowing four new render tests to pass on GL-Native linux
  test/integration/render-tests/image-fallback-nested/feature-state-inside/style.json
  test/integration/render-tests/image-fallback-nested/feature-state-outside/style.json
  test/integration/render-tests/image-fallback-nested/verbose/feature-state-inside/style.json
  test/integration/render-tests/image-fallback-nested/verbose/feature-state-outside/style.json
Labels: skip changelog

#11387 Add globe view support to the debug shader
  src/shaders/debug.vertex.glsl
Labels: skip changelog

#11396 Update test/README.md
  test/README.md
Labels: skip changelog

#11397 Less conservative check to enable stencil lines
  src/render/program/line_program.js
  test/integration/render-tests/line-opacity/data-driven/expected.png
  test/integration/render-tests/line-opacity/data-driven/style.json
  test/integration/tiles/16-19296-24630.mvt
Labels: bug :lady_beetle:

#11404 Log a warning when the map container isn't empty
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: skip changelog

#11416 update style spec changelog and version
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#11415 update changelog and version number for v2.7.0
  CHANGELOG.md
  package.json
Labels: skip changelog

#11395 Fix variable anchors on globe
  src/geo/projection/flat_tile_transform.js
  src/geo/projection/globe.js
  src/geo/projection/globe_tile_transform.js
  src/geo/projection/index.js
  src/render/draw_symbol.js
  src/symbol/collision_index.js
  src/symbol/projection.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  test/ignores.json
  test/integration/render-tests/globe/globe-symbols/variable-anchor-text/expected.png
Labels: bug :lady_beetle:, skip changelog

#11411 Added missing argument to new test instructions
  test/integration/README.md
Labels: docs :scroll:, skip changelog

#11414 Thin out repeated line labels at overscaled tiles
  src/symbol/symbol_layout.js
  test/integration/render-tests/text-pitch-alignment/viewport-overzoomed-single-glyph/expected.png
Labels: performance :zap:

#11400 Type matrix and vector calculations
  .flowconfig
  flow-typed/gl-matrix.js
  package.json
  src/data/bucket/symbol_bucket.js
  src/data/dem_tree.js
  src/geo/projection/flat_tile_transform.js
  src/geo/projection/globe.js
  src/geo/projection/globe_tile_transform.js
  src/geo/projection/index.js
  src/geo/projection/tile_transform.js
  src/geo/transform.js
  src/render/draw_collision_debug.js
  src/render/draw_globe_atmosphere.js
  src/render/draw_sky.js
  src/render/draw_symbol.js
  src/render/painter.js
  src/render/program/skybox_capture_program.js
  src/render/program/skybox_program.js
  src/source/query_features.js
  src/style/style_layer/fill_extrusion_style_layer.js
  src/style/style_layer/sky_style_layer.js
  src/symbol/collision_index.js
  src/symbol/placement.js
  src/symbol/projection.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  src/ui/camera.js
  src/ui/free_camera.js
  src/ui/handler_manager.js
  src/util/primitives.js
  src/util/util.js
  yarn.lock
Labels: testing :100:, skip changelog

#11428 Remove unused uniform
  src/render/program/symbol_program.js
  src/shaders/symbol_icon.vertex.glsl
  src/shaders/symbol_sdf.vertex.glsl
  src/shaders/symbol_text_and_icon.vertex.glsl
Labels: skip changelog

#11401 Fix pole rendering on globe view
  src/geo/projection/globe.js
  src/source/tile.js
  src/terrain/draw_terrain_raster.js
  test/integration/render-tests/globe/globe-transforms/north-pole-z0/expected.png
  test/integration/render-tests/globe/globe-transforms/north-pole-z0/style.json
  test/integration/render-tests/globe/globe-transforms/south-pole-z0/expected.png
  test/integration/render-tests/globe/globe-transforms/south-pole-z0/style.json
Labels: bug :lady_beetle:, skip changelog

#11399 Globe View: Prevent drawing symbols on the non-visible side of the globe
  src/geo/projection/globe.js
  src/render/draw_symbol.js
  src/render/program/symbol_program.js
  src/shaders/_prelude.vertex.glsl
  src/shaders/symbol_icon.vertex.glsl
  src/shaders/symbol_sdf.vertex.glsl
  src/shaders/symbol_text_and_icon.vertex.glsl
  src/symbol/collision_index.js
  src/symbol/placement.js
  test/integration/render-tests/globe/globe-symbols/globe-edge-clipping-allow-overlap/expected.png
  test/integration/render-tests/globe/globe-symbols/icon-allow-overlap/expected.png
  test/integration/render-tests/globe/globe-symbols/icon-allow-overlap/style.json
  test/integration/render-tests/globe/globe-symbols/text-allow-overlap/expected.png
  test/integration/render-tests/globe/globe-symbols/text-allow-overlap/style.json
Labels: bug :lady_beetle:, skip changelog

#11423 Apply border-radius to control buttons
  src/css/mapbox-gl.css
Labels: bug :lady_beetle:

#11434 Free vertex/index buffers after uploading to GPU
  src/gl/index_buffer.js
  src/gl/vertex_buffer.js
  src/util/struct_array.js
Labels: performance :zap:

#11393 Fix e.isSourceLoaded to check if specific source is loaded
  src/style/style.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#11436 Upgrade Flow to v0.131.0
  .flowconfig
  package.json
  src/data/bucket/symbol_bucket.js
  src/data/dem_tree.js
  src/geo/projection/resample.js
  src/terrain/terrain.js
  src/ui/camera.js
  yarn.lock
Labels: skip changelog

#11435 add doc for minTileCacheSize
  src/source/source_cache.js
  src/ui/map.js
Labels: skip changelog

#11437 Globe view: add circle layer support
  build/generate-struct-arrays.js
  src/data/array_types.js
  src/data/bucket/circle_attributes.js
  src/data/bucket/circle_bucket.js
  src/geo/projection/albers.js
  src/geo/projection/equal_earth.js
  src/geo/projection/equirectangular.js
  src/geo/projection/flat_tile_transform.js
  src/geo/projection/globe.js
  src/geo/projection/globe_tile_transform.js
  src/geo/projection/index.js
  src/geo/projection/lambert.js
  src/geo/projection/mercator.js
  src/geo/projection/natural_earth.js
  src/geo/projection/winkel_tripel.js
  src/render/draw_circle.js
  src/render/draw_symbol.js
  src/render/program/circle_program.js
  src/render/program/symbol_program.js
  src/source/source_cache.js
  src/style/style.js
  src/symbol/collision_index.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  src/ui/map.js
  test/ignores.json
  test/integration/render-tests/globe/globe-symbols/variable-anchor-text/expected.png
Labels: feature :green_apple:, skip changelog

#11450 Update to v2.7.0 gl-js and v13.23.1 style-spec final versions and changelogs
  CHANGELOG.md
  package.json
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#11452 Update changelog for v2.7.0 and style-spec@13.23.1
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
Labels: skip changelog

#11449 Update version number to `2.8.0-dev`
  package.json
Labels: skip changelog
