Repository mapbox/mapbox-gl-js, pull requests merged in 2022-07, with the labels that each got.

#11988 Fix missing tiles at bottom of screen during globe-Mercator transition
  src/geo/projection/globe_util.js
  src/geo/transform.js
  test/integration/render-tests/globe/globe-transition/tiles-high-pitch/expected.png
  test/integration/render-tests/globe/globe-transition/tiles-high-pitch/style.json
  test/integration/tiles/3-4-1.mvt
  test/integration/tiles/4-7-4.mvt
  test/integration/tiles/4-8-4.mvt
Labels: bug :lady_beetle:, 3d :triangular_ruler:

#12056 Pass separate shadow direction to shaders
  src/shaders/_prelude_shadow.fragment.glsl
  src/shaders/fill_extrusion.fragment.glsl
Labels: skip changelog

#12071 Pass shadow bias values via a uniform
  src/shaders/_prelude_shadow.fragment.glsl
Labels: skip changelog

#12068 Fallback to hardcoded units in browsers without `NumberFormat` support in `ScaleControl`
  src/ui/control/scale_control.js
  test/unit/ui/control/scale.test.js
Labels: bug :lady_beetle:, skip changelog

#12049 Fix clearing tiles when using setStyle to switch projections
  src/geo/projection/index.js
  src/geo/transform.js
  src/style/style.js
  src/ui/map.js
  test/integration/render-tests/globe/globe-set-style/albers-globe-toggle/expected.png
  test/integration/render-tests/globe/globe-set-style/albers-globe-toggle/style.json
  test/integration/render-tests/globe/globe-set-style/raster/expected.png
  test/integration/render-tests/globe/globe-set-style/raster/style.json
  test/unit/style/style.test.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#12080 Fix GeolocateControl in Safari
  src/ui/control/geolocate_control.js
  test/unit/ui/control/geolocate.test.js
Labels: bug :lady_beetle:

#12042 Add render tests for map resize
  test/ignores.json
  test/integration/render-tests/resize/globe/expected.png
  test/integration/render-tests/resize/globe/style.json
  test/integration/render-tests/resize/mercator/expected.png
  test/integration/render-tests/resize/mercator/style.json
Labels: skip changelog

#12087 Blend shadow between cascades and fade out at distance
  src/shaders/_prelude_shadow.fragment.glsl
Labels: skip changelog

#12086 Refactoring to replace redundant code with `tileCoordToECEF`
  src/data/bucket/symbol_bucket.js
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/render/draw_debug.js
Labels: skip changelog

#12088 v2.9.2 cherry-picks
  src/ui/control/geolocate_control.js
  src/ui/control/scale_control.js
  test/unit/ui/control/geolocate.test.js
  test/unit/ui/control/scale.test.js
Labels: skip changelog

#12089 v2.9.2
  CHANGELOG.md
  package.json
Labels: skip changelog

#12091 Update CHANGELOG with 2.9.2 changes
  CHANGELOG.md
Labels: skip changelog

#11708 Add localization for UI strings in Malay
  src/ui/locales/ms.js
Labels: skip changelog

#12097 Optimize globe normalization matrices
  flow-typed/gl-matrix.js
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
Labels: skip changelog

#11711 Add localization for UI strings in Norwegian
  src/ui/locales/no.js
Labels: skip changelog

#11709 Add localization for UI strings in Norwegian Bokmål
  src/ui/locales/nb.js
Labels: skip changelog

#12104 is-supported-script is supported on iOS/macOS
  src/style-spec/reference/v8.json
Labels: cross-platform :tv:, docs :scroll:, skip changelog, style-spec

#11959 Round edges for fill extrusions
  debug/buildings.html
  src/data/bucket/fill_extrusion_bucket.js
  src/render/draw_fill_extrusion.js
  src/render/program/fill_extrusion_program.js
  src/shaders/fill_extrusion.vertex.glsl
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  src/style/style_layer/fill_extrusion_style_layer.js
  src/style/style_layer/fill_extrusion_style_layer_properties.js
  test/integration/render-tests/fill-extrusion-base/rounded-edge/expected.png
  test/integration/render-tests/fill-extrusion-base/rounded-edge/style.json
  test/integration/render-tests/fill-extrusion-height/z-fighting/expected.png
  test/integration/render-tests/fill-extrusion-pattern/2x-on-1x-add-image-dds/expected.png
  test/integration/render-tests/fill-extrusion-pattern/@2x/expected.png
  test/integration/render-tests/fill-extrusion-pattern/feature-expression/expected.png
  test/integration/render-tests/fill-extrusion-pattern/function-2/expected.png
  test/integration/render-tests/fill-extrusion-pattern/function/expected.png
  test/integration/render-tests/fill-extrusion-pattern/literal/expected.png
  test/integration/render-tests/fill-extrusion-pattern/opacity-terrain-flat/expected.png
  test/integration/render-tests/fill-extrusion-pattern/opacity/expected.png
  test/integration/render-tests/fill-pattern/projected/expected.png
  test/integration/render-tests/fog/2d/fill-extrusion-pattern/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/pattern/expected.png
Labels: feature :green_apple:

#12101 fix running in <iframe sandbox="allow-scripts">
  debug/iframe-sandbox.html
  src/util/tile_request_cache.js
Labels: bug :lady_beetle:

#12108 Fix mismatching zoom on first interaction in `globe` view
  src/geo/transform.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: release blocker :no_entry:, skip changelog

#12117 Update versions for `fill-extrusion-ambient-occlusion-*` and `fill-extrusion-edge-radius`
  src/style-spec/reference/v8.json
Labels: skip changelog

#12114 Improve globe constraints and panning precision
  src/geo/transform.js
  src/ui/handler_manager.js
  test/integration/query-tests/globe/poles/south-pole-box-inside/style.json
  test/unit/style/query_geometry.test.js
Labels: feature :green_apple:

#12120 Update z0 pole render tests to cover new constraints
  test/integration/render-tests/globe/globe-transforms/north-pole-z0/expected.png
  test/integration/render-tests/globe/globe-transforms/north-pole-z0/style.json
  test/integration/render-tests/globe/globe-transforms/south-pole-z0/expected.png
  test/integration/render-tests/globe/globe-transforms/south-pole-z0/style.json
Labels: skip changelog

#12122 Fix "improve map" link to include location when hash is disabled
  src/ui/control/attribution_control.js
  src/ui/hash.js
  test/unit/ui/control/attribution.test.js
Labels: bug :lady_beetle:
