Repository mapbox/mapbox-gl-js, pull requests merged in 2022-04, with the labels that each got.

#11441 Tile URL: placeholders can be duplicated
  src/source/tile_id.js
  test/unit/source/tile_id.test.js
Labels: bug :lady_beetle:

#11656 Fix clipped tiles near globe view transition
  src/geo/projection/globe.js
  test/integration/render-tests/globe/globe-transition/at-transition-zoom/expected.png
  test/integration/render-tests/globe/globe-transition/at-transition-zoom/style.json
Labels: skip changelog

#11649 refactor CustomSource
  src/source/custom_source.js
  test/integration/lib/operation-handlers.js
  test/integration/render-tests/custom-source/albers/style.json
  test/integration/render-tests/custom-source/equal-earth/style.json
  test/integration/render-tests/custom-source/equirectangular/style.json
  test/integration/render-tests/custom-source/lambert/style.json
  test/integration/render-tests/custom-source/natural-earth/style.json
  test/integration/render-tests/custom-source/satellite/style.json
  test/integration/render-tests/custom-source/terrain/expected.png
  test/integration/render-tests/custom-source/terrain/style.json
  test/integration/render-tests/custom-source/winkel-tripel/style.json
  test/unit/source/custom_source.test.js
Labels: release blocker :no_entry:, refactoring :building_construction:, skip changelog

#11668 temporarily revert dependency version to fix build issue
  package.json
Labels: skip changelog

#11670 Cherry pick fixes into v2.8.0 for final release
  .github/actions/check-changelog/action.yml
  .github/actions/check-changelog/index.js
  .github/actions/package.json
  .github/actions/yarn.lock
  .github/workflows/pull-request-requirements.yml
  CHANGELOG.md
  package.json
  src/source/custom_source.js
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
  src/ui/control/scale_control.js
  test/integration/lib/operation-handlers.js
  test/integration/render-tests/custom-source/albers/style.json
  test/integration/render-tests/custom-source/equal-earth/style.json
  test/integration/render-tests/custom-source/equirectangular/style.json
  test/integration/render-tests/custom-source/lambert/style.json
  test/integration/render-tests/custom-source/natural-earth/style.json
  test/integration/render-tests/custom-source/satellite/style.json
  test/integration/render-tests/custom-source/terrain/expected.png
  test/integration/render-tests/custom-source/terrain/style.json
  test/integration/render-tests/custom-source/winkel-tripel/style.json
  test/unit/source/custom_source.test.js
  test/unit/ui/control/scale.test.js
Labels: skip changelog

#11637 Updating changelogs to include v2.8.0 (#11636)
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
Labels: skip changelog

#11570 Introduce line-trim-offset paint property
  src/data/array_types.js
  src/data/bucket/line_attributes_ext.js
  src/data/bucket/line_bucket.js
  src/render/draw_line.js
  src/render/program/line_program.js
  src/shaders/line.fragment.glsl
  src/shaders/line.vertex.glsl
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  src/style-spec/validate/validate_layer.js
  src/style/style_layer/line_style_layer_properties.js
  test/integration/render-tests/line-trim-offset/gradient-end-offset/expected.png
  test/integration/render-tests/line-trim-offset/gradient-end-offset/style.json
  test/integration/render-tests/line-trim-offset/gradient-mid-offset/expected.png
  test/integration/render-tests/line-trim-offset/gradient-mid-offset/style.json
  test/integration/render-tests/line-trim-offset/gradient-round-cap/expected.png
  test/integration/render-tests/line-trim-offset/gradient-round-cap/style.json
  test/integration/render-tests/line-trim-offset/gradient-shared-source/expected.png
  test/integration/render-tests/line-trim-offset/gradient-shared-source/style.json
  test/integration/render-tests/line-trim-offset/gradient-start-offset/expected.png
  test/integration/render-tests/line-trim-offset/gradient-start-offset/style.json
  test/integration/render-tests/line-trim-offset/gradient-step/expected.png
  test/integration/render-tests/line-trim-offset/gradient-step/style.json
  test/integration/render-tests/line-trim-offset/gradient-with-dash/expected.png
  test/integration/render-tests/line-trim-offset/gradient-with-dash/style.json
Labels: feature :green_apple:

#11674 fix: force loaded state for CustomSource tiles
  src/source/custom_source.js
  test/unit/source/custom_source.test.js
Labels: bug :lady_beetle:, release blocker :no_entry:, skip changelog

#11675 Improve debug page for the CustomSource
  debug/custom-source.html
  test/release/custom-source.html
  test/release/index.js
Labels: skip changelog

#11677 Cherry picking CustomSource fix to release v2.8.0
  debug/custom-source.html
  src/source/custom_source.js
  test/release/custom-source.html
  test/release/index.js
  test/unit/source/custom_source.test.js
Labels: skip changelog

#11676 Fix missing release testing pages due to broken CI
  .circleci/config.yml
  test/release/README.md
  test/release/custom-source.html
  test/release/extrusion-query.html
  test/release/featurestate.html
  test/release/index.js
  test/release/local_release_page_list.txt
  test/release/markers.html
  test/release/preload-tiles.html
  test/release/projections.html
  test/release/scroll_zoom_blocker.html
  test/release/three-js-antenna.html
  test/release/video.html
Labels: skip changelog

#11680 Custom source debug page support for Safari and Firefox
  debug/custom-source.html
Labels: skip changelog

#11682 Fix missing release testing pages due to broken CI
  .circleci/config.yml
  test/release/README.md
  test/release/custom-source.html
  test/release/extrusion-query.html
  test/release/featurestate.html
  test/release/index.js
  test/release/local_release_page_list.txt
  test/release/markers.html
  test/release/preload-tiles.html
  test/release/projections.html
  test/release/scroll_zoom_blocker.html
  test/release/three-js-antenna.html
  test/release/video.html
Labels: skip changelog

#11673 Move fog properties to stage-specific preludes
  src/shaders/_prelude.glsl
  src/shaders/_prelude_fog.fragment.glsl
  src/shaders/_prelude_fog.vertex.glsl
Labels: skip changelog

#11681 Custom source debug page support for Safari and Firefox
  debug/custom-source.html
Labels: skip changelog

#11683 Show render test diff in result page
  test/integration/lib/render.js
  test/util/html_generator.js
Labels: workflow :nail_care:, skip changelog

#11688 Add localization for UI strings in Russian
  src/ui/locales/ru.js
Labels: skip changelog

#11722 Add localization for UI strings in Vietnamese
  src/ui/locales/vi.js
Labels: skip changelog

#11713 Add localization for UI strings in Portuguese
  src/ui/locales/pt.js
Labels: skip changelog

#11712 Add localization for UI strings in Polish
  src/ui/locales/pl.js
Labels: skip changelog

#11718 Add localization for UI strings in Swedish
  src/ui/locales/sv.js
Labels: skip changelog

#11710 Add localization for UI strings in Dutch
  src/ui/locales/nl.js
Labels: skip changelog

#11714 Add localization for UI strings in Romanian
  src/ui/locales/ro.js
Labels: skip changelog

#11720 Add localization for UI strings in Tagalog
  src/ui/locales/tl.js
Labels: skip changelog

#11693 Add localization for UI strings in Danish
  src/ui/locales/da.js
Labels: skip changelog

#11689 Add localization for UI strings in Ukrainian
  src/ui/locales/uk.js
Labels: skip changelog

#11723 Add localization for UI strings in Simplified Chinese
  src/ui/locales/zh-Hans.js
Labels: skip changelog

#11694 Add localization for UI strings in German
  src/ui/locales/de.js
Labels: skip changelog

#11697 Add localization for UI strings in Farsi
  src/ui/locales/fa.js
Labels: skip changelog

#11743 Update gitignore to exclude vscode files
  .gitignore
Labels: skip changelog

#11739 Fix CSP bundle by not mangling class names there, and add CSP tests
  .circleci/config.yml
  bench/rollup_config_benchmarks.js
  build/rollup_plugins.js
  package.json
  rollup.config.csp.js
  rollup.config.js
  src/util/web_worker_transfer.js
  test/integration/rollup.config.test.js
  test/integration/testem/testem.js
  test/integration/testem_page_csp.html
Labels: bug :lady_beetle:

#11717 Add localization for UI strings in Serbian
  src/ui/locales/sr.js
Labels: skip changelog

#11698 Add localization for UI strings in Finnish
  src/ui/locales/fi.js
Labels: skip changelog

#11744 Update sr.js
  src/ui/locales/sr.js
Labels: skip changelog

#11706 Add localization for UI strings in Korean
  src/ui/locales/ko.js
Labels: skip changelog

#11749 add missing roundZoom in CustomSource coveringTiles
  src/source/custom_source.js
Labels: skip changelog

#11751 Cherry picks v2.8.1
  .circleci/config.yml
  bench/rollup_config_benchmarks.js
  build/rollup_plugins.js
  package.json
  rollup.config.csp.js
  rollup.config.js
  src/source/custom_source.js
  src/util/web_worker_transfer.js
  test/integration/rollup.config.test.js
  test/integration/testem/testem.js
  test/integration/testem_page_csp.html
Labels: skip changelog

#11752 update changelog
  CHANGELOG.md
Labels: skip changelog

#11704 Add localization for UI strings in Japanese
  src/ui/locales/ja.js
Labels: skip changelog

#11721 Add localization for UI strings in Turkish
  src/ui/locales/tr.js
Labels: skip changelog

#11696 Add localization for UI strings in Spanish
  src/ui/locales/es.js
Labels: skip changelog

#11691 Add localization for UI strings in Catalan
  src/ui/locales/ca.js
Labels: skip changelog

#11614 Add `geolocation` adapter for customizing geolocation in `GeolocateControl`
  src/ui/control/geolocate_control.js
Labels: feature :green_apple:

#11703 Add localization for UI strings in Italian
  src/ui/locales/it.js
Labels: skip changelog

#11767 Add image source render test for globe
  test/integration/render-tests/globe/globe-image-source/expected.png
  test/integration/render-tests/globe/globe-image-source/style.json
Labels: skip changelog

#11766 Add render test for `addImage` and `addLayer` API with `globe` projection
  test/integration/render-tests/globe/globe-fill-pattern/3x-on-2x-add-image/expected.png
  test/integration/render-tests/globe/globe-fill-pattern/3x-on-2x-add-image/style.json
Labels: skip changelog

#11770 Add clustered geojson source render test for globe
  test/integration/render-tests/globe/globe-geojson/clustered/expected.png
  test/integration/render-tests/globe/globe-geojson/clustered/style.json
Labels: skip changelog

#11768 Add video source render test for globe
  test/integration/render-tests/globe/globe-video/expected.png
  test/integration/render-tests/globe/globe-video/style.json
Labels: skip changelog

#11773 Adding correct example to `setLight` docs and improving docs types
  debug/extrusion-query.html
  src/ui/map.js
Labels: skip changelog

#11771 Add globe runtime styling render tests
  test/integration/render-tests/globe/globe-runtime-styling/image-remove/expected.png
  test/integration/render-tests/globe/globe-runtime-styling/image-remove/style.json
  test/integration/render-tests/globe/globe-runtime-styling/layer-remove/expected.png
  test/integration/render-tests/globe/globe-runtime-styling/layer-remove/style.json
  test/integration/render-tests/globe/globe-runtime-styling/remove-source/expected.png
  test/integration/render-tests/globe/globe-runtime-styling/remove-source/style.json
Labels: skip changelog

#11666 Implement i18n API
  debug/i18n.html
  src/source/load_tilejson.js
  src/source/raster_tile_source.js
  src/source/source.js
  src/source/vector_tile_source.js
  src/ui/map.js
  src/util/mapbox.js
  src/util/tile_request_cache.js
  test/unit/ui/map.test.js
  test/unit/util/mapbox.test.js
  test/unit/util/tile_request_cache.test.js
Labels: feature :green_apple:

#11777 Adding unit tests for map.snapToNorth()
  test/unit/ui/map.test.js
Labels: skip changelog

#11756 Simplify and consolidate globe atmosphere uniforms
  src/geo/transform.js
  src/render/draw_atmosphere.js
  src/render/painter.js
  src/shaders/atmosphere.vertex.glsl
  src/terrain/globe_raster_program.js
  src/util/primitives.js
Labels: skip changelog

#11780 Increase test coverage of the camera in globe view
  test/integration/render-tests/globe/globe-camera/reset-north-pitch/expected.png
  test/integration/render-tests/globe/globe-camera/reset-north-pitch/style.json
  test/integration/render-tests/globe/globe-camera/reset-north/expected.png
  test/integration/render-tests/globe/globe-camera/reset-north/style.json
  test/unit/ui/camera.test.js
Labels: skip changelog

#11787 Adding unit tests for map.project in globe and other projections
  test/unit/ui/map.test.js
Labels: skip changelog

#11790 Revert web worker registry name refactor to fix CSP build edge case
  src/data/array_types.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/heatmap_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/data/dem_data.js
  src/data/feature_index.js
  src/data/feature_position_map.js
  src/data/program_configuration.js
  src/data/segment.js
  src/render/glyph_atlas.js
  src/render/image_atlas.js
  src/render/line_atlas.js
  src/source/tile_id.js
  src/style/format_section_override.js
  src/style/properties.js
  src/symbol/anchor.js
  src/symbol/opacity_state.js
  src/util/image.js
  src/util/struct_array.js.ejs
  src/util/struct_array_layout.js.ejs
  src/util/web_worker_transfer.js
  test/unit/util/web_worker_transfer.test.js
  yarn.lock
Labels: bug :lady_beetle:

#11782 Add render tests for `setLayoutProperty` and `setLayerZoomRange` in globe view
  test/integration/render-tests/globe/globe-runtime-styling/set-layout-property/expected.png
  test/integration/render-tests/globe/globe-runtime-styling/set-layout-property/style.json
  test/integration/render-tests/globe/globe-zoom-visibility/above/expected.png
  test/integration/render-tests/globe/globe-zoom-visibility/above/style.json
  test/integration/render-tests/globe/globe-zoom-visibility/below/expected.png
  test/integration/render-tests/globe/globe-zoom-visibility/below/style.json
  test/integration/render-tests/globe/globe-zoom-visibility/in-range/expected.png
  test/integration/render-tests/globe/globe-zoom-visibility/in-range/style.json
Labels: skip changelog

#11796 Add unit test for `map.remove` in globe view
  test/unit/ui/map.test.js
Labels: skip changelog

#11785 Remove unnecessary conversions and reuse projection scaler
  src/geo/projection/globe.js
  test/integration/render-tests/globe/globe-transition/with-symbols/expected.png
  test/integration/render-tests/globe/globe-transition/with-symbols/style.json
Labels: skip changelog

#11801 Add test for atmosphere buffer destroy
  test/unit/ui/map.test.js
Labels: skip changelog

#11806 v2.8.2 changelog and version bump
  CHANGELOG.md
  package.json
Labels: skip changelog

#11807 cherry-pick v2.8.2 changelog to main
  CHANGELOG.md
Labels: skip changelog

#11803 Add atmosphere render tests
  test/integration/render-tests/fog/globe/high-color-opacity/expected.png
  test/integration/render-tests/fog/globe/high-color-opacity/style.json
  test/integration/render-tests/fog/globe/high-color-transparent/expected.png
  test/integration/render-tests/fog/globe/high-color-transparent/style.json
  test/integration/render-tests/fog/globe/high-color/expected.png
  test/integration/render-tests/fog/globe/high-color/style.json
  test/integration/render-tests/fog/globe/space-color-opacity/expected.png
  test/integration/render-tests/fog/globe/space-color-opacity/style.json
  test/integration/render-tests/fog/globe/space-color/expected.png
  test/integration/render-tests/fog/globe/space-color/style.json
  test/integration/render-tests/fog/globe/star-intensity/expected.png
  test/integration/render-tests/fog/globe/star-intensity/style.json
  test/integration/render-tests/fog/high-color-opacity/expected.png
  test/integration/render-tests/fog/high-color-opacity/style.json
  test/integration/render-tests/fog/high-color-transparent/expected.png
  test/integration/render-tests/fog/high-color-transparent/style.json
  test/integration/render-tests/fog/high-color/expected.png
  test/integration/render-tests/fog/high-color/style.json
  test/integration/render-tests/fog/space-color-opacity/expected.png
  test/integration/render-tests/fog/space-color-opacity/style.json
  test/integration/render-tests/fog/space-color/expected.png
  test/integration/render-tests/fog/space-color/style.json
  test/integration/render-tests/fog/star-intensity/expected.png
  test/integration/render-tests/fog/star-intensity/style.json
Labels: skip changelog

#11802 Adding render test for `map.updateImage()` on globe
  test/integration/render-tests/globe/globe-runtime-styling/image-update-icon/expected.png
  test/integration/render-tests/globe/globe-runtime-styling/image-update-icon/style.json
Labels: skip changelog

#11810 Adding unit test ensuring `mapboxgl.version` is valid regex
  test/unit/mapbox-gl.js
Labels: skip changelog

#11804 Adding image dimensions to `map.updateImage` error message and fixing incorrect example
  src/source/image_source.js
  src/ui/map.js
Labels: skip changelog

#11818 Adding unit tests for map.version
  test/unit/ui/map.test.js
Labels: skip changelog

#11821 Add boxzoomcancel unit tests
  test/unit/ui/handler/box_zoom.test.js
Labels: skip changelog

#11788 Move fog shader functions from common prelude to stage specific preludes
  src/shaders/_prelude.glsl
  src/shaders/_prelude_fog.fragment.glsl
  src/shaders/_prelude_fog.vertex.glsl
Labels: skip changelog

#11817 Cover globe projection for some isMoving and isRotating test
  test/unit/ui/map/isMoving.test.js
  test/unit/ui/map/isRotating.test.js
Labels: skip changelog

#11825 Adding links to prewarm() and clearPrewarmedResources() documentation
  src/index.js
Labels: docs :scroll:, skip changelog

#11658 Globe occlusion for popups and improving marker performance on globe
  src/geo/projection/globe_util.js
  src/geo/transform.js
  src/ui/marker.js
  src/ui/popup.js
  test/unit/ui/marker.test.js
  test/unit/ui/popup.test.js
Labels: bug :lady_beetle:, 3d :triangular_ruler:

#11826 Prevent incorrect display of circles and heatmaps during globe-mercator transition
  src/render/draw_circle.js
  src/render/draw_heatmap.js
Labels: bug :lady_beetle:, skip changelog

#11794 Add unit tests for `queryTerrainElevation`
  test/unit/ui/map.test.js
Labels: skip changelog

#11783 Add unit tests for `panBy` and `panTo` in globe view
  test/unit/ui/camera.test.js
Labels: skip changelog

#11833 Increase resolution of heatmaps on globe
  src/render/draw_heatmap.js
  test/integration/render-tests/globe/globe-heatmap/horizontal/expected.png
  test/integration/render-tests/globe/globe-heatmap/near-horizon/expected.png
  test/integration/render-tests/globe/globe-heatmap/vertical/expected.png
Labels: bug :lady_beetle:, skip changelog

#11832 Fix uniforms not being uploaded when atmosphere opacity is 0
  src/render/painter.js
  test/integration/render-tests/regressions/gl-js-team#430/expected.png
  test/integration/render-tests/regressions/gl-js-team#430/style.json
Labels: bug :lady_beetle:, skip changelog

#11836 Update source URIs of query tests
  test/integration/query-tests/globe/antimeridian/box-cross-from-left/style.json
  test/integration/query-tests/globe/antimeridian/box-cross-from-right/style.json
  test/integration/query-tests/globe/circle/opposite-side-over-north-pole/style.json
Labels: skip changelog

#11834 Fix edge cases for popup occlusion
  src/ui/popup.js
  test/unit/ui/popup.test.js
Labels: skip changelog

#11798 Add unit test for `isZooming` in globe view
  test/unit/ui/map/isZooming.test.js
Labels: skip changelog
