Repository mapbox/mapbox-gl-js, pull requests merged in 2022-10, with the labels that each got.

#12265 Update to `jsdom@15.2.1`
  package.json
  test/unit/ui/popup.test.js
  yarn.lock
Labels: testing :100:, skip changelog

#12220 Update style support table for Android and iOS
  src/style-spec/reference/v8.json
Labels: docs :scroll:, skip changelog, style-spec

#12270 Fix bug in LngLatBounds.extend by allowing object literal LngLat as a parameter.
  src/geo/lng_lat_bounds.js
  test/unit/geo/lng_lat_bounds.test.js
Labels: bug :lady_beetle:

#12297 Check if TERRAIN is enabled when using PITCH_WITH_MAP_TERRAIN in symbol shaders
  src/shaders/symbol_icon.vertex.glsl
  src/shaders/symbol_sdf.vertex.glsl
  src/shaders/symbol_text_and_icon.vertex.glsl
Labels: skip changelog

#12286 Adaptive bounds calculation
  src/geo/transform.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#12279 Fix missing ocean tiles
  src/terrain/terrain.js
  test/integration/render-tests/globe/globe-horizon/style.json
  test/integration/render-tests/globe/globe-transition/ocean-artifact/expected.png
  test/integration/render-tests/globe/globe-transition/ocean-artifact/style.json
  test/integration/tiles/5-8-12.mvt
  test/integration/tiles/5-8-13.mvt
  test/integration/tiles/5-9-12.mvt
  test/integration/tiles/5-9-13.mvt
Labels: bug :lady_beetle:

#12299 Fix icons with no image causing other missing icons
  src/data/array_types.js
  src/data/bucket/symbol_bucket.js
  src/symbol/placement.js
  src/symbol/symbol_layout.js
  src/util/struct_array.js
  src/util/struct_array.js.ejs
  test/integration/render-tests/debug/collision-variable-icon-image-simple/expected.png
  test/integration/render-tests/debug/collision-variable-icon-image-simple/style.json
Labels: bug :lady_beetle:, release blocker :no_entry:

#12318 Revert the poles support in Globe `getBounds`
  src/geo/transform.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: skip changelog

#12320 Remove line atlas leftover from style/painter
  src/render/painter.js
  src/style/style.js
Labels: skip changelog

#12323 Update main and style-spec dev version numbers
  package.json
  src/style-spec/package.json
Labels: skip changelog

#12329 fix changelog
  CHANGELOG.md
Labels: skip changelog

#12325 update `main` style-spec to 13.28.0-dev
  src/style-spec/package.json
Labels: skip changelog

#12315 Add poles support in `getBounds` on the Globe
  src/geo/projection/globe_util.js
  src/geo/transform.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#12330 Cleanup in shaders to fix warnings
  src/shaders/_prelude_terrain.vertex.glsl
  src/shaders/hillshade_prepare.fragment.glsl
  src/shaders/line.fragment.glsl
Labels: skip changelog

#12345 Copy documentation conventions from the `mapbox-gl-js-doc`
  CONTRIBUTING.md
Labels: skip changelog

#12264 Update options for `AnimationOptions`
  src/ui/camera.js
Labels: docs :scroll:, skip changelog
