Repository mapbox/mapbox-gl-js, pull requests merged in 2022-11, with the labels that each got.

#12350 Minor struct array types cleanup
  build/generate-struct-arrays.js
  src/data/array_types.js
  src/style/style_layer/fill_extrusion_style_layer.js
  src/util/struct_array.js.ejs
Labels: skip changelog

#12357 Drop documentation.js dependency
  .flowconfig
  package.json
  test/build/downstream-flow-fixture/.flowconfig
  yarn.lock
Labels: skip changelog

#12343 Add live performance counters
  src/gl/context.js
  src/ui/map.js
  src/util/config.js
  src/util/live_performance.js
  src/util/mapbox.js
  src/util/performance.js
  src/util/window.js
  test/unit/ui/map.test.js
  test/unit/util/live_performance.test.js
  test/unit/util/mapbox.test.js
Labels: feature :green_apple:

#12371 Add `lines/slope-occlusion` query test to ignores
  test/ignores.json
Labels: skip changelog

#12372 Fix incorrect transition flag of properties
  src/style-spec/reference/v8.json
Labels: docs :scroll:

#12367 Allow pitch override in camera apis
  debug/padding.html
  src/ui/camera.js
  test/unit/ui/camera.test.js
Labels: api :memo:

#12351 Optimize and simplify symbol placement code
  .eslintrc
  src/data/array_types.js
  src/data/bucket/symbol_attributes.js
  src/data/bucket/symbol_bucket.js
  src/render/draw_symbol.js
  src/symbol/collision_index.js
  src/symbol/placement.js
  src/symbol/projection.js
  src/symbol/symbol_layout.js
  src/symbol/symbol_size.js
Labels: performance :zap:

#12376 Fix crash with multi-line labels along lines + RTL Text plugin
  src/symbol/projection.js
Labels: bug :lady_beetle:

#12384 update changelog and versions to final
  CHANGELOG.md
  package.json
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#12379 Add a basic page for debugging render tests
  debug/render-test.html
Labels: workflow :nail_care:, skip changelog

#12387 Add 3D lighting mode to 2D layer shaders
  src/shaders/_prelude_lighting.glsl
  src/shaders/background.fragment.glsl
  src/shaders/background.vertex.glsl
  src/shaders/background_pattern.fragment.glsl
  src/shaders/circle.fragment.glsl
  src/shaders/fill.fragment.glsl
  src/shaders/fill_outline.fragment.glsl
  src/shaders/fill_outline_pattern.fragment.glsl
  src/shaders/fill_pattern.fragment.glsl
  src/shaders/hillshade.fragment.glsl
  src/shaders/line.fragment.glsl
  src/shaders/line_pattern.fragment.glsl
  src/shaders/raster.fragment.glsl
Labels: skip changelog

#12388 Simplify and speed up render tests a bit
  test/integration/lib/generate-fixture-json.js
  test/integration/lib/harness.js
  test/integration/lib/localize-urls.js
  test/integration/lib/query.js
  test/integration/lib/render.js
  test/util/html_generator.js
Labels: skip changelog

#12373 New lighting model in fill extrusion
  src/shaders/_prelude_lighting.glsl
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_pattern.fragment.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
Labels: skip changelog

#12377 Restore support for breaks along line labels
  src/symbol/shaping.js
  src/symbol/symbol_layout.js
  test/unit/symbol/shaping.test.js
Labels: bug :lady_beetle:

#12397 Optimize image rasterization with `willReadFrequently` hints
  src/source/raster_dem_tile_worker_source.js
  src/util/browser.js
Labels: performance :zap:

#12396 Fix race condition when placing multiline line labels
  src/symbol/projection.js
Labels: skip changelog

#12394 add metric that counts times page hidden
  src/ui/map.js
  src/util/live_performance.js
Labels: skip changelog

#12403 v2.11.1-beta.1
  CHANGELOG.md
  package.json
Labels: skip changelog

#11702 Add localization for UI strings in Indonesian
  src/ui/locales/id.js
Labels: skip changelog

#12414 Fixed Uncaught exception via CVE-2022-41940
  yarn.lock
Labels: skip changelog

#12389 Update changelogs in main branch
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
Labels: skip changelog

#12422 Store explicit projection instead of runtime projection in metrics
  src/ui/map.js
  src/util/live_performance.js
  src/util/mapbox.js
  test/unit/ui/map.test.js
  test/unit/util/live_performance.test.js
  test/unit/util/mapbox.test.js
Labels: skip changelog

#12413 Fix distance-to-center filtering of symbols when terrain is enabled
  src/geo/transform.js
  src/ui/free_camera.js
  test/integration/render-tests/terrain/symbol-distance-from-center/expected.png
  test/integration/render-tests/terrain/symbol-distance-from-center/style.json
Labels: bug :lady_beetle:

#12423 Apply fog in fragment shader in terrain_raster program
  src/render/painter.js
  src/shaders/_prelude_terrain.vertex.glsl
  src/shaders/terrain_raster.fragment.glsl
  src/shaders/terrain_raster.vertex.glsl
  test/integration/render-tests/fog/terrain/zero-exaggeration/expected.png
  test/integration/render-tests/fog/terrain/zero-exaggeration/style.json
Labels: bug :lady_beetle:

#12425 Remove function only added for IE11 compatibility
  src/ui/map.js
Labels: skip changelog
