Repository mapbox/mapbox-gl-js, pull requests merged in 2022-09, with the labels that each got.

#12210 Revert "Fix draping artifact on ocean tiles (#12203)"
  src/terrain/terrain.js
  test/integration/render-tests/globe/globe-horizon/style.json
  test/integration/render-tests/globe/globe-transition/ocean-artifact/expected.png
  test/integration/render-tests/globe/globe-transition/ocean-artifact/style.json
  test/integration/tiles/5-8-12.mvt
  test/integration/tiles/5-8-13.mvt
  test/integration/tiles/5-9-12.mvt
  test/integration/tiles/5-9-13.mvt
Labels: skip changelog

#12207 Fix `aabb.fromPoints` API
  src/util/primitives.js
  test/integration/render-tests/globe/globe-transition/bearing/style.json
  test/integration/render-tests/globe/globe-transition/tile-edges/style.json
  test/integration/render-tests/globe/globe-transition/transition-fill/style.json
  test/unit/util/primitives.test.js
Labels: bug :lady_beetle:

#12200 Add weekly automated dependency upgrade PRs with Dependabot
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: skip changelog

#12214 Fix incorrectly shaded concave corner of fill extrusions when AO is enabled
  src/data/bucket/fill_extrusion_bucket.js
  test/integration/render-tests/fill-extrusion-base/rounded-edge-ao/expected.png
  test/integration/render-tests/fill-extrusion-base/rounded-edge-ao/style.json
Labels: bug :lady_beetle:

#12218 Add missing height calculation for fill extrusion rounded edges in depth shader
  src/shaders/fill_extrusion_depth.vertex.glsl
Labels: skip changelog

#12212 Prevent unnecessary texture upload on image source updates
  src/source/image_source.js
  test/unit/source/image_source.test.js
  test/unit/terrain/terrain.test.js
Labels: bug :lady_beetle:

#12206 Add a CODEOWNERS file
  .github/CODEOWNERS
Labels: skip changelog

#12224 Fix resource leak on Safari on `map.remove()`
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#12233 Shader code to disable roofs from getting rounded in rounded fill extrusion
  src/shaders/fill_extrusion.fragment.glsl
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_depth.vertex.glsl
Labels: skip changelog

#12208 Borders/boundaries for line layer
  src/shaders/line.fragment.glsl
Labels: skip changelog

#12063 Refactor `CustomSource`
  debug/custom-source.html
  src/source/custom_source.js
  src/source/source.js
  src/source/source_cache.js
  src/source/tile.js
  test/unit/source/custom_source.test.js
Labels: bug :lady_beetle:, skip changelog

#12249 Format shaders to support function constant blocks
  src/shaders/atmosphere.fragment.glsl
  src/shaders/circle.vertex.glsl
  src/shaders/fill_extrusion.fragment.glsl
  src/shaders/fill_extrusion.vertex.glsl
  src/shaders/fill_extrusion_depth.vertex.glsl
  src/shaders/fill_extrusion_pattern.vertex.glsl
  src/shaders/globe_raster.fragment.glsl
  src/shaders/heatmap.vertex.glsl
  src/shaders/symbol_icon.vertex.glsl
  src/shaders/symbol_sdf.vertex.glsl
  src/shaders/symbol_text_and_icon.vertex.glsl
Labels: skip changelog

#12248 Upgrade Flow to v0.145
  .flowconfig
  bench/benchmarks/query_box.js
  bench/lib/tile_parser.js
  flow-typed/geojson.js
  flow-typed/jsdom.js
  flow-typed/vector-tile.js
  package.json
  src/data/bucket.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/data/evaluation_feature.js
  src/data/feature_index.js
  src/data/program_configuration.js
  src/geo/projection/resample.js
  src/source/geojson_wrapper.js
  src/source/tile.js
  src/source/vector_tile_worker_source.js
  src/source/worker_tile.js
  src/style-spec/expression/definitions/within.js
  src/style/query_geometry.js
  src/style/style_layer.js
  src/style/style_layer/circle_style_layer.js
  src/style/style_layer/fill_extrusion_style_layer.js
  src/style/style_layer/fill_style_layer.js
  src/style/style_layer/heatmap_style_layer.js
  src/style/style_layer/line_style_layer.js
  src/symbol/projection.js
  src/ui/control/navigation_control.js
  src/ui/handler/box_zoom.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
  src/util/intersection_tests.js
  src/util/polygon_clipping.js
  src/util/util.js
  src/util/vectortile_to_geojson.js
  test/unit/source/vector_tile_worker_source.test.js
  yarn.lock
Labels: skip changelog

#12254 Add i18n language fallbacks support
  src/source/vector_tile_source.js
  src/ui/control/scale_control.js
  src/ui/map.js
  test/unit/ui/map.test.js
Labels: skip changelog

#12242 Fix displaced markers when toggling projections
  src/geo/projection/albers.js
  src/ui/map.js
  src/ui/popup.js
  test/unit/ui/marker.test.js
  test/unit/ui/popup.test.js
Labels: bug :lady_beetle:

#12105 Improve performance of symbol placement with globe
  src/geo/transform.js
  src/terrain/elevation.js
  src/terrain/terrain.js
  test/unit/ui/map.test.js
Labels: performance :zap:
