Repository mapbox/mapbox-gl-js, pull requests merged in 2022-08, with the labels that each got.

#12125 Fix incorrect geometry of chamfered walls for rounded fill extrusions
  debug/buildings.html
  src/data/bucket/fill_extrusion_bucket.js
  test/integration/render-tests/fill-extrusion-base/rounded-edge/expected.png
  test/integration/render-tests/fill-extrusion-base/rounded-edge/style.json
Labels: skip changelog

#12090 Fix globe render test baseline generation under macOS
  package.json
  test/integration/README.md
  test/integration/testem/testem.js
Labels: skip changelog

#12075 Revert tile loading changes from #11988
  src/geo/projection/globe_util.js
  test/ignores.json
  test/integration/render-tests/globe/globe-transition/tile-corners-outside/expected.png
  test/integration/render-tests/globe/globe-transition/tile-corners-outside/style.json
  test/integration/render-tests/globe/globe-transition/transition-bearing/expected.png
  test/integration/tiles/3-4-0.mvt
Labels: bug :lady_beetle:, release blocker :no_entry:, skip changelog

#12146 Make ambient occlusion and edge radius private in the style-spec
  src/style-spec/reference/v8.json
  test/unit/style-spec/spec.test.js
Labels: skip changelog

#12147 Release v2.10.0 cherry-picks
  src/style-spec/reference/v8.json
  test/unit/style-spec/spec.test.js
Labels: skip changelog

#12133 Fix pole geometry elevation sampling
  src/data/array_types.js
  src/geo/projection/globe_util.js
  src/shaders/globe_raster.vertex.glsl
  src/terrain/draw_terrain_raster.js
  src/terrain/globe_attributes.js
  test/integration/render-tests/globe/globe-transforms/north-pole-padded-dem/expected.png
  test/integration/render-tests/globe/globe-transforms/north-pole-padded-dem/style.json
  test/integration/render-tests/globe/globe-transforms/south-pole-padded-dem/expected.png
  test/integration/render-tests/globe/globe-transforms/south-pole-padded-dem/style.json
  test/integration/tiles/0-0-0.terrain-dem-v1.514.png
Labels: bug :lady_beetle:

#12124 Fix abrupt jump with globe view + maxBounds after transition to mercator
  src/geo/transform.js
  src/ui/map.js
Labels: skip changelog

#12154 Fix blank globe on Android by reverting "Prevent unnecessary terrain define with globe"
  src/render/draw_symbol.js
  src/render/painter.js
Labels: release blocker :no_entry:, skip changelog

#12162 Set the release version to 2.10.0-beta.1
  package.json
Labels: skip changelog

#12145 Fix 1-pixel flickering between tiles on dark styles
  src/geo/projection/globe_util.js
  src/shaders/globe_raster.vertex.glsl
  src/terrain/draw_terrain_raster.js
  test/integration/render-tests/globe/globe-antialiasing/high-exaggeration/expected.png
  test/integration/render-tests/globe/globe-tile-padding/expected.png
  test/integration/render-tests/globe/globe-tile-padding/style.json
Labels: bug :lady_beetle:

#12137 Fix tile cover during globe-to-Mercator transition
  src/geo/projection/globe_util.js
  src/util/primitives.js
  test/ignores.json
  test/integration/render-tests/globe/globe-transition/tiles-high-pitch/expected.png
Labels: bug :lady_beetle:

#12165 Allowing two-finger pitch with cooperative gestures in fullscreen
  src/ui/handler/touch_zoom_rotate.js
  test/unit/ui/handler/touch_zoom_rotate.test.js
Labels: bug :lady_beetle:

#12152 Fixing globe not displaying on Android
  src/render/painter.js
  src/render/program.js
  src/terrain/terrain.js
Labels: release blocker :no_entry:, skip changelog

#12177 Fix error in shadow edge tap smoothing calculation
  src/shaders/_prelude_shadow.fragment.glsl
Labels: skip changelog

#12163 Fix terrain "source" error being fired when using `map.getStyle()` with globe view
  src/style/style.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:

#12183 Upgrade Tap to v16 (and other unit test deps)
  build/run-tap
  package.json
  test/browser/drag.test.js
  test/unit/source/canvas_source.test.js
  test/unit/source/raster_dem_tile_source.test.js
  test/unit/source/raster_tile_source.test.js
  test/unit/source/vector_tile_source.test.js
  test/unit/style-spec/feature_filter.test.js
  test/unit/style-spec/fixture/invalidjson.output.json
  test/unit/style-spec/validate.test.js
  test/unit/style-spec/validate_mapbox_api_supported.test.js
  test/unit/style/style.test.js
  test/unit/terrain/terrain.test.js
  test/unit/ui/map.test.js
  test/unit/util/ajax.test.js
  test/unit/util/mapbox.test.js
  test/unit/util/tile_request_cache.test.js
  test/util/test.js
  yarn.lock
Labels: skip changelog

#12178 Updating READMEs and version numbers for v2.10.0 final release.
  CHANGELOG.md
  package.json
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#12131 Add debug AABB visualization and fix to tile bounds debug visualization during globe transition
  build/rollup_plugins.js
  debug/animate-point-along-route.html
  debug/debug.html
  debug/terrain-debug.html
  src/geo/projection/globe_util.js
  src/render/draw_debug.js
  src/render/painter.js
  src/source/tile.js
  src/ui/map.js
  src/ui/marker.js
  src/util/debug.js
  test/integration/render-tests/globe/globe-transition/transition-bearing/expected.png
  test/integration/render-tests/globe/globe-transition/transition-fill/expected.png
Labels: skip changelog

#12186 Updating changelogs to include release v2.10.0
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
Labels: skip changelog

#12176 Use 2x2 edge tap smoothing sampling for second shadow cascade
  src/shaders/_prelude_shadow.fragment.glsl
Labels: skip changelog

#12188 Edits to the spec with respect to new fill-extrusion properties
  src/style-spec/reference/v8.json
Labels: skip changelog

#12189 Upgrade dependencies where possible
  .circleci/config.yml
  bench/data/style-benchmark-locations.json
  bench/styles/benchmarks.js
  bench/versions/benchmarks.js
  package.json
  postcss.config.cjs
  src/types/window.js
  yarn.lock
Labels: skip changelog

#11724 Add localization for UI strings in Traditional Chinese
  src/ui/locales/zh-Hant.js
Labels: skip changelog

#12172 Fix crashing Lambert Conformal Conic projection at South pole
  src/geo/projection/lambert.js
  test/integration/render-tests/map-projections/albers/polar-north/expected.png
  test/integration/render-tests/map-projections/albers/polar-north/style.json
  test/integration/render-tests/map-projections/albers/polar-south/expected.png
  test/integration/render-tests/map-projections/albers/polar-south/style.json
  test/integration/render-tests/map-projections/lambert/polar-north/expected.png
  test/integration/render-tests/map-projections/lambert/polar-north/style.json
  test/integration/render-tests/map-projections/lambert/polar-south/expected.png
  test/integration/render-tests/map-projections/lambert/polar-south/style.json
Labels: bug :lady_beetle:

#12199 Add a debug page for globe getBounds
  debug/globe-bounds.html
Labels: skip changelog

#12203 Fix draping artifact on ocean tiles
  src/terrain/terrain.js
  test/integration/render-tests/globe/globe-horizon/style.json
  test/integration/render-tests/globe/globe-transition/ocean-artifact/expected.png
  test/integration/render-tests/globe/globe-transition/ocean-artifact/style.json
  test/integration/tiles/5-8-12.mvt
  test/integration/tiles/5-8-13.mvt
  test/integration/tiles/5-9-12.mvt
  test/integration/tiles/5-9-13.mvt
Labels: bug :lady_beetle:, 3d :triangular_ruler:
