Repository mapbox/mapbox-gl-js, pull requests merged in 2022-05, with the labels that each got.

#11840 Do not create stars if star intensity is zero
  src/shaders/atmosphere.fragment.glsl
Labels: skip changelog

#11843 Use high precision atmosphere related shader operations
  src/shaders/_prelude_fog.fragment.glsl
  src/shaders/atmosphere.fragment.glsl
Labels: skip changelog

#11774 Fix tiles being erroneously culled near poles
  src/geo/projection/globe_util.js
  test/unit/geo/projection/globe.test.js
Labels: bug :lady_beetle:, skip changelog

#11828 include performance timelines with performance metrics
  build/rollup_plugins.js
  rollup.config.js
  src/index.js
  src/ui/map.js
  src/util/performance.js
  src/util/worker_performance_utils.js
  test/browser/performance_metrics.test.js
Labels: skip changelog

#11844 Fix render test for globe-terrain
  test/integration/render-tests/globe/globe-terrain/expected.png
  test/integration/render-tests/globe/globe-terrain/style.json
  test/integration/tiles/4-10-5.terrain.png
  test/integration/tiles/4-10-6.terrain.png
  test/integration/tiles/4-11-5.terrain.png
  test/integration/tiles/4-11-6.terrain.png
  test/integration/tiles/4-12-5.terrain.png
  test/integration/tiles/4-12-6.terrain.png
Labels: skip changelog

#11830 Resolve zoom on terrain with exaggeration 0
  src/geo/transform.js
  test/unit/geo/transform.test.js
Labels: bug :lady_beetle:, 3d :triangular_ruler:

#11838 Adding more links to examples in addLayer docs
  src/ui/map.js
Labels: docs :scroll:, skip changelog

#11848 Revert stencil mask skipping optimization
  src/render/painter.js
  src/terrain/terrain.js
Labels: bug :lady_beetle:

#11845 Update fog documentation in style spec
  src/style-spec/reference/v8.json
Labels: docs :scroll:, skip changelog

#11765 Support map aligned symbols in globe view
  build/generate-struct-arrays.js
  flow-typed/gl-matrix.js
  src/data/array_types.js
  src/data/bucket/symbol_attributes.js
  src/data/bucket/symbol_bucket.js
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/geo/projection/projection.js
  src/geo/projection/resample.js
  src/render/draw_symbol.js
  src/render/program.js
  src/render/program/symbol_program.js
  src/render/vertex_array_object.js
  src/shaders/symbol_icon.vertex.glsl
  src/shaders/symbol_sdf.vertex.glsl
  src/shaders/symbol_text_and_icon.vertex.glsl
  src/symbol/collision_index.js
  src/symbol/placement.js
  src/symbol/projection.js
  src/symbol/symbol_layout.js
  test/integration/render-tests/globe/globe-symbols/icon-map-align-rotate-with-map/expected.png
  test/integration/render-tests/globe/globe-symbols/icon-map-align-rotate-with-map/style.json
  test/integration/render-tests/globe/globe-symbols/icon-map-align/expected.png
  test/integration/render-tests/globe/globe-symbols/icon-map-align/style.json
  test/integration/render-tests/globe/globe-symbols/icon-viewport-align-rotate-with-map/expected.png
  test/integration/render-tests/globe/globe-symbols/icon-viewport-align-rotate-with-map/style.json
  test/integration/render-tests/globe/globe-symbols/line-placement-map-align-keep-upright/expected.png
  test/integration/render-tests/globe/globe-symbols/line-placement-map-align-keep-upright/style.json
  test/integration/render-tests/globe/globe-symbols/line-placement-map-align/expected.png
  test/integration/render-tests/globe/globe-symbols/line-placement-map-align/style.json
  test/integration/render-tests/globe/globe-symbols/line-placement-viewport-align/expected.png
  test/integration/render-tests/globe/globe-symbols/line-placement-viewport-align/style.json
  test/integration/render-tests/globe/globe-symbols/text-map-align-rotate-with-map/expected.png
  test/integration/render-tests/globe/globe-symbols/text-map-align-rotate-with-map/style.json
  test/integration/render-tests/globe/globe-symbols/text-map-align/expected.png
  test/integration/render-tests/globe/globe-symbols/text-map-align/style.json
  test/integration/render-tests/globe/globe-symbols/text-viewport-align-rotate-with-map/expected.png
  test/integration/render-tests/globe/globe-symbols/text-viewport-align-rotate-with-map/style.json
  test/integration/render-tests/globe/globe-symbols/variable-anchor-text-map-align/expected.png
  test/integration/render-tests/globe/globe-symbols/variable-anchor-text-map-align/style.json
Labels: bug :lady_beetle:, skip changelog

#11827 Enable antialias on globe view when not set in map constructor
  src/geo/projection/globe_util.js
  src/gl/context.js
  src/render/draw_atmosphere.js
  src/render/program.js
  src/shaders/atmosphere.fragment.glsl
  src/shaders/globe_raster.fragment.glsl
  src/shaders/shaders.js
  src/terrain/draw_terrain_raster.js
  src/terrain/globe_raster_program.js
  test/integration/lib/render.js
  test/integration/render-tests/globe/globe-antialiasing/default/expected.png
  test/integration/render-tests/globe/globe-antialiasing/default/style.json
  test/integration/render-tests/globe/globe-antialiasing/horizon-blend/expected.png
  test/integration/render-tests/globe/globe-antialiasing/horizon-blend/style.json
Labels: skip changelog

#11859 Fix failing render tests in main due to missing rebase of PR #11827
  test/integration/render-tests/regressions/gl-js-team#430/expected.png
Labels: skip changelog

#11854 Fix incorrect fog contribution of fog during the globe-mercator transition
  src/geo/projection/globe.js
  src/geo/projection/projection.js
  src/geo/transform.js
  src/render/program/circle_program.js
  src/shaders/globe_raster.vertex.glsl
  src/terrain/draw_terrain_raster.js
  src/terrain/globe_raster_program.js
  test/integration/render-tests/regressions/gl-js-team#426/expected.png
  test/integration/render-tests/regressions/gl-js-team#426/style.json
  test/integration/render-tests/regressions/mapbox-gl-js#11769/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#11769/style.json
Labels: bug :lady_beetle:, skip changelog

#11799 Add a new query test for circle layer + map-pitch-alignment + zero pitch
  test/integration/query-tests/circle-pitch-scale/map-inside-align-map-zero-pitch/expected.json
  test/integration/query-tests/circle-pitch-scale/map-inside-align-map-zero-pitch/style.json
Labels: skip changelog

#11851 Fix the floating circles/heatmap artifact which occurs during globe/mercator transition
  src/data/bucket/circle_bucket.js
  src/render/draw_heatmap.js
  test/integration/render-tests/globe/globe-heatmap/horizontal/expected.png
  test/integration/render-tests/globe/globe-heatmap/near-transition/expected.png
  test/integration/render-tests/globe/globe-heatmap/near-transition/style.json
Labels: skip changelog

#11863 Add globe to heatmap testing page
  debug/heatmap-layer.html
  test/release/index.js
  test/release/local_release_page_list.txt
Labels: skip changelog

#11837 Fix the floating circles/heatmap artifact which occurs during globe/mercator transition
  src/geo/projection/globe.js
  test/integration/render-tests/globe/globe-circle/near-transition/expected.png
  test/integration/render-tests/globe/globe-circle/near-transition/style.json
  test/integration/render-tests/globe/globe-heatmap/near-transition/expected.png
  test/integration/render-tests/globe/globe-transition/with-symbols/expected.png
  test/integration/render-tests/regressions/gl-js-team#426/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#11769/expected.png
Labels: bug :lady_beetle:, skip changelog

#11868 Remove unused shader attribute
  src/shaders/symbol_text_and_icon.vertex.glsl
Labels: skip changelog

#11822 Clarifying documentation for CameraOptions and improving types for easeTo wrappers
  src/ui/camera.js
Labels: docs :scroll:, skip changelog

#11872 Relax atmosphere check to slightly increase globe radius for 0 `horizon-blend` values
  src/render/draw_atmosphere.js
Labels: bug :lady_beetle:, skip changelog

#11876 Add render test for globe label collision
  test/integration/render-tests/globe/globe-symbols/line-placement-map-align-collision/expected.png
  test/integration/render-tests/globe/globe-symbols/line-placement-map-align-collision/style.json
Labels: skip changelog

#11882 Ensure unsupported APIs are no-op when used with globe projection
  src/ui/camera.js
  src/ui/map.js
  test/unit/ui/camera.test.js
  test/unit/ui/map.test.js
Labels: skip changelog

#11879 Add render tests to validate `setProjection` precedence over `setStyle`
  test/integration/render-tests/map-projections/integrations/set-projection/set-projection-precedence-fallback/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/set-projection-precedence-fallback/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/set-projection-precedence/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/set-projection-precedence/style.json
Labels: skip changelog

#11862 Fix clamping behavior of pointCoordinate leading to false positives in feature queries
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/geo/projection/projection.js
  src/geo/transform.js
  test/integration/query-tests/globe/horizon/box-above/expected.json
  test/integration/query-tests/globe/horizon/box-above/style.json
  test/integration/query-tests/globe/horizon/box/expected.json
  test/integration/query-tests/globe/horizon/box/style.json
  test/integration/query-tests/globe/horizon/point-above/expected.json
  test/integration/query-tests/globe/horizon/point-above/style.json
  test/integration/query-tests/globe/horizon/point/expected.json
  test/integration/query-tests/globe/horizon/point/style.json
  test/unit/ui/map.test.js
Labels: skip changelog

#11883 Add globe release test with `setData` calls and map aligned symbol
  debug/animate-point-along-route.html
  test/release/index.js
  test/release/local_release_page_list.txt
Labels: testing :100:, skip changelog

#11878 Add release testing page for atmosphere and globe view
  debug/atmosphere.html
  test/release/index.js
  test/release/local_release_page_list.txt
Labels: testing :100:, skip changelog

#11881 Add globe to testing image on a map
  debug/image-on-globe.html
  test/release/index.js
  test/release/local_release_page_list.txt
Labels: testing :100:, skip changelog

#11889 Fix to map-aligned markers on globe ignoring marker rotation
  src/ui/marker.js
Labels: skip changelog

#11893 Changelog v2.9.0-beta.1
  CHANGELOG.md
  package.json
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#11890 Adding test for globe marker rotation
  test/unit/ui/marker.test.js
Labels: skip changelog

#11899 Aidan/cherry pick marker fix v2.9.0
  src/ui/marker.js
  test/unit/ui/marker.test.js
Labels: bug :lady_beetle:

#11700 Add localization for UI strings in Hebrew
  src/ui/locales/he.js
Labels: skip changelog

#11888 Add filter features within map view with globe release test
  debug/filter-features-with-globe.html
  test/release/index.js
  test/release/local_release_page_list.txt
Labels: testing :100:, skip changelog

#11904 Fix incorrect circle bucket up direction
  src/render/program/circle_program.js
  src/render/program/heatmap_program.js
  test/integration/render-tests/globe/globe-heatmap/near-transition/expected.png
  test/integration/render-tests/regressions/mapbox-gl-js#11769/expected.png
Labels: bug :lady_beetle:

#11850 ScaleControl: add i18n support
  debug/i18n.html
  src/css/mapbox-gl.css
  src/ui/control/scale_control.js
  src/ui/default_locale.js
  src/ui/map.js
  test/unit/ui/control/scale.test.js
Labels: feature :green_apple:, skip changelog

#11912 Add minimum/maximum definitions for center/parallels
  src/style-spec/reference/v8.json
Labels: skip changelog

#11887 Update for next release cycle
  package.json
  src/style-spec/package.json
Labels: skip changelog

#11933 Add new render test for globe antialiasing
  test/integration/render-tests/globe/globe-antialiasing/tilted/expected.png
  test/integration/render-tests/globe/globe-antialiasing/tilted/style.json
Labels: skip changelog

#11928 Fix potential flickering on image source updates
  src/source/image_source.js
  test/unit/source/image_source.test.js
Labels: bug :lady_beetle:

#11913 Fix setStyle breaking with globe view
  src/ui/map.js
  test/integration/render-tests/globe/globe-set-style/default/expected.png
  test/integration/render-tests/globe/globe-set-style/default/style.json
Labels: skip changelog

#11943 Fix tiles not rendering across antimeridian in globe
  src/geo/projection/globe_util.js
  test/integration/render-tests/globe/globe-transforms/antimeridian-left/expected.png
  test/integration/render-tests/globe/globe-transforms/antimeridian-left/style.json
  test/integration/render-tests/globe/globe-transforms/antimeridian-right/expected.png
  test/integration/render-tests/globe/globe-transforms/antimeridian-right/style.json
Labels: bug :lady_beetle:, skip changelog

#11945 Fix unit test in Globe view fix #11381
  test/unit/ui/map.test.js
Labels: testing :100:, skip changelog

#11947 Do not render atmosphere when fog isn't supported by the map projection
  src/render/painter.js
  test/integration/render-tests/map-projections/unsupported-fog/expected.png
  test/integration/render-tests/map-projections/unsupported-fog/style.json
Labels: bug :lady_beetle:, skip changelog
