Repository mapbox/mapbox-gl-js, pull requests merged in 2022-02, with the labels that each got.

#11458 Remove a leftover from util.js
  src/util/util.js
  test/unit/util/util.test.js
Labels: skip changelog

#11447 Enforce more deliberate grouping of mixed binary or logical operators
  .eslintrc
  src/data/bucket/symbol_bucket.js
  src/data/program_configuration.js
  src/gl/value.js
  src/render/glyph_manager.js
  src/source/source_cache.js
  src/source/tile.js
  src/style-spec/expression/evaluation_context.js
  src/symbol/projection.js
  src/ui/camera.js
  src/ui/control/scale_control.js
  src/ui/map.js
  src/ui/marker.js
  src/util/util.js
  test/unit/source/canvas_source.test.js
  test/unit/source/video_source.test.js
Labels: skip changelog

#11456 Upgrade Flow to v0.142.0
  .flowconfig
  flow-typed/gl-matrix.js
  flow-typed/grid-index.js
  flow-typed/pbf.js
  flow-typed/point-geometry.js
  flow-typed/potpack.js
  flow-typed/tiny-sdf.js
  flow-typed/vector-tile.js
  package.json
  src/data/bucket.js
  src/data/evaluation_feature.js
  src/render/painter.js
  src/render/texture.js
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/query_features.js
  src/source/raster_dem_tile_worker_source.js
  src/source/vector_tile_source.js
  src/source/worker_source.js
  src/style-spec/expression/index.js
  src/style-spec/style-spec.js
  src/style/format_section_override.js
  src/terrain/terrain.js
  src/ui/control/navigation_control.js
  src/ui/handler/box_zoom.js
  src/ui/handler/handler_util.js
  src/ui/handler/map_event.js
  src/ui/map.js
  src/ui/popup.js
  src/util/image.js
  src/util/struct_array.js
  src/util/tile_request_cache.js
  src/util/util.js
  src/util/web_worker_transfer.js
  test/unit/source/raster_dem_tile_worker_source.test.js
  yarn.lock
Labels: skip changelog

#11448 Always wrap center coordinate to the range [-180, 180]
  src/geo/projection/globe_tile_transform.js
  src/geo/transform.js
  src/util/util.js
  test/unit/geo/projection/globe.test.js
  test/unit/util/util.test.js
Labels: bug :lady_beetle:

#11466 Fix performance issue when placing many symbols on terrain
  src/data/dem_data.js
  test/unit/data/dem_data.test.js
Labels: performance :zap:

#11464 Add heatmap layer support for globe view
  src/geo/projection/globe.js
  src/render/draw_heatmap.js
  src/render/program/heatmap_program.js
  src/render/program/program_uniforms.js
  test/ignores.json
  test/integration/render-tests/globe/globe-heatmap/default-zoomed/expected.png
Labels: feature :green_apple:, skip changelog

#11471 [Flow] Add missing export types to gl/*
  src/gl/context.js
  src/gl/value.js
Labels: skip changelog

#11472 [Flow] Type exports for data/*
  src/data/bounds_attributes.js
  src/data/bucket/circle_attributes.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/dash_attributes.js
  src/data/bucket/fill_attributes.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_attributes.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/line_attributes.js
  src/data/bucket/line_attributes_ext.js
  src/data/bucket/line_bucket.js
  src/data/bucket/pattern_attributes.js
  src/data/bucket/pattern_bucket_features.js
  src/data/bucket/symbol_attributes.js
  src/data/bucket/symbol_bucket.js
  src/data/dem_data.js
  src/data/dem_tree.js
  src/data/feature_index.js
  src/data/pos_attributes.js
  src/data/program_configuration.js
  src/data/segment.js
Labels: skip changelog

#11468 Improve Popup typing and simplify code
  src/ui/popup.js
Labels: skip changelog

#11474 Use named exports for DOM functions for better tree shaking
  src/ui/control/attribution_control.js
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/logo_control.js
  src/ui/control/navigation_control.js
  src/ui/control/scale_control.js
  src/ui/events.js
  src/ui/handler/box_zoom.js
  src/ui/handler/mouse.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler/touch_pan.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/handler_manager.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
  src/util/dom.js
  test/unit/ui/handler/box_zoom.test.js
  test/unit/ui/handler/dblclick_zoom.test.js
  test/unit/ui/handler/drag_pan.test.js
  test/unit/ui/handler/drag_rotate.test.js
  test/unit/ui/handler/keyboard.test.js
  test/unit/ui/handler/map_event.test.js
  test/unit/ui/handler/mouse_rotate.test.js
  test/unit/ui/handler/scroll_zoom.test.js
  test/unit/ui/handler/touch_pan.test.js
  test/unit/ui/handler/touch_zoom_rotate.test.js
  test/unit/ui/map/isMoving.test.js
  test/unit/ui/map/isRotating.test.js
  test/unit/ui/map/isZooming.test.js
Labels: skip changelog

#11473 Remove unused code in terrain.js and fix lint config
  src/render/draw_background.js
  src/render/draw_fill.js
  src/render/draw_hillshade.js
  src/render/draw_line.js
  src/render/draw_raster.js
  src/render/painter.js
  src/terrain/terrain.js
Labels: skip changelog

#11480 [Flow] Add missing types in various util files
  src/util/ajax.js
  src/util/browser.js
  src/util/browser/window.js
  src/util/classify_rings.js
  src/util/dictionary_coder.js
  src/util/global_worker_pool.js
  src/util/intersection_tests.js
  src/util/script_detection.js
  src/util/tile_request_cache.js
  src/util/util.js
  src/util/verticalize_punctuation.js
  src/util/window.js
Labels: skip changelog

#11478 [Flow] Add missing types to LngLat & LngLatBounds
  src/geo/lng_lat.js
  src/geo/lng_lat_bounds.js
Labels: skip changelog

#11485 [Flow] Add minor missing types to misc files
  src/geo/mercator_coordinate.js
  src/geo/projection/adjustments.js
  src/geo/transform.js
  src/render/skybox_attributes.js
  src/shaders/encode_attribute.js
  src/terrain/globe_attributes.js
  src/terrain/terrain.js
  src/util/primitives.js
Labels: skip changelog

#11484 [Flow] Add missing types for line atlas and sprite positions
  src/data/bucket.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/data/program_configuration.js
  src/render/image_atlas.js
  src/render/image_manager.js
  src/render/line_atlas.js
  src/render/texture.js
  src/source/tile.js
  src/source/worker_tile.js
  src/util/image.js
Labels: skip changelog

#11488 [Flow] Add missing export types to painter.js
  src/render/painter.js
Labels: skip changelog

#11479 [Flow] Improve types in `vectortile_to_geojson.js`
  src/data/feature_index.js
  src/source/tile.js
  src/util/vectortile_to_geojson.js
Labels: skip changelog

#11486 [Flow] Add missing export types to source/*
  src/data/feature_index.js
  src/source/query_features.js
  src/source/rtl_text_plugin.js
  src/source/source_cache.js
  src/source/source_state.js
  src/source/tile.js
  src/source/tile_bounds.js
  src/util/vectortile_to_geojson.js
Labels: skip changelog

#11483 [Flow] Add missing types for controls & hash
  src/ui/control/attribution_control.js
  src/ui/control/fullscreen_control.js
  src/ui/control/geolocate_control.js
  src/ui/control/logo_control.js
  src/ui/control/navigation_control.js
  src/ui/control/scale_control.js
  src/ui/hash.js
  src/ui/map.js
Labels: skip changelog

#11487 [Flow] Add missing export types to bench/*
  bench/benchmarks/expressions.js
  bench/benchmarks/hillshade_load.js
  bench/benchmarks/layout.js
  bench/benchmarks/layout_dds.js
  bench/benchmarks/symbol_layout.js
  bench/lib/benchmark.js
  bench/lib/tile_parser.js
Labels: skip changelog

#11496 [Flow] Add more missing export types to source/*
  src/render/draw_fill_extrusion.js
  src/source/rtl_text_plugin.js
  src/source/source_cache.js
  src/source/tile.js
  src/source/tile_cache.js
  src/style/style_layer/fill_extrusion_style_layer.js
Labels: skip changelog

#11503 [Flow] Add missing export types to handler/*
  src/ui/handler/box_zoom.js
  src/ui/handler/click_zoom.js
  src/ui/handler/handler_util.js
  src/ui/handler/keyboard.js
  src/ui/handler/map_event.js
  src/ui/handler/mouse.js
  src/ui/handler/scroll_zoom.js
  src/ui/handler/shim/dblclick_zoom.js
  src/ui/handler/shim/drag_pan.js
  src/ui/handler/shim/drag_rotate.js
  src/ui/handler/shim/touch_zoom_rotate.js
  src/ui/handler/tap_drag_zoom.js
  src/ui/handler/tap_zoom.js
  src/ui/handler/touch_pan.js
  src/ui/handler/touch_zoom_rotate.js
  src/ui/handler_manager.js
  src/ui/marker.js
  src/util/evented.js
Labels: skip changelog

#11499 Improve globe performance by caching globe matrix
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/geo/projection/tile_transform.js
  src/geo/transform.js
  src/render/draw_globe_atmosphere.js
  src/render/program/symbol_program.js
  src/symbol/projection.js
  src/terrain/draw_terrain_raster.js
Labels: skip changelog

#11506 [Flow] Add missing export types to style/style_layer/*
  src/style/create_style_layer.js
  src/style/style.js
  src/style/style_layer/background_style_layer.js
  src/style/style_layer/custom_style_layer.js
  src/style/style_layer/fill_extrusion_style_layer.js
  src/style/style_layer/fill_style_layer.js
  src/style/style_layer/heatmap_style_layer.js
  src/style/style_layer/hillshade_style_layer.js
  src/style/style_layer/line_style_layer.js
  src/style/style_layer/raster_style_layer.js
  src/style/style_layer/sky_style_layer.js
  src/style/style_layer/symbol_style_layer.js
  src/style/validate_style.js
Labels: skip changelog

#11500 Simplify globe buffers code
  src/geo/projection/globe_util.js
  src/terrain/draw_terrain_raster.js
Labels: skip changelog

#11512 Flow fixes for util/performance.js
  src/util/performance.js
Labels: skip changelog

#11511 Simplify web worker registry to reduce bundle size
  src/data/array_types.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/heatmap_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/data/dem_data.js
  src/data/feature_index.js
  src/data/feature_position_map.js
  src/data/program_configuration.js
  src/data/segment.js
  src/render/glyph_atlas.js
  src/render/image_atlas.js
  src/render/line_atlas.js
  src/source/raster_dem_tile_worker_source.js
  src/source/tile_id.js
  src/style/format_section_override.js
  src/style/properties.js
  src/symbol/anchor.js
  src/symbol/opacity_state.js
  src/util/ajax.js
  src/util/image.js
  src/util/struct_array.js.ejs
  src/util/struct_array_layout.js.ejs
  src/util/web_worker_transfer.js
  test/unit/util/web_worker_transfer.test.js
Labels: skip changelog

#11445 Globe fill extrusion
  build/generate-struct-arrays.js
  debug/globe-fill-extrusion.html
  src/data/array_types.js
  src/data/bucket.js
  src/data/bucket/circle_bucket.js
  src/data/bucket/fill_bucket.js
  src/data/bucket/fill_extrusion_attributes.js
  src/data/bucket/fill_extrusion_bucket.js
  src/data/bucket/line_bucket.js
  src/data/bucket/symbol_bucket.js
  src/geo/projection/globe.js
  src/render/draw_fill_extrusion.js
  src/render/program/fill_extrusion_program.js
  src/source/vector_tile_worker_source.js
  src/source/worker_tile.js
  src/style/style.js
  src/util/polygon_clipping.js
  test/integration/render-tests/globe/globe-fill-extrusion/default/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/default/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/opacity/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/opacity/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/pattern/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/pattern/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/stack-interleaved-layers/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/stack-interleaved-layers/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/translate/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/translate/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/vertical_gradient/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/vertical_gradient/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/zero-height-clipping-angle-limit/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/zero-height-clipping-angle-limit/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/zero-height-clipping-complex/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/zero-height-clipping-complex/style.json
  test/integration/render-tests/globe/globe-fill-extrusion/zero-height-clipping-simple/expected.png
  test/integration/render-tests/globe/globe-fill-extrusion/zero-height-clipping-simple/style.json
  test/unit/source/vector_tile_worker_source.test.js
  test/unit/util/polygon_clipping.test.js
Labels: skip changelog

#11517 Fix recently introduced globe regression during the transition
  src/terrain/draw_terrain_raster.js
  test/integration/render-tests/globe/globe-transition/transition-fill/expected.png
  test/integration/render-tests/globe/globe-transition/transition-fill/style.json
  test/integration/tiles/5-15-10.mvt
  test/integration/tiles/5-15-11.mvt
  test/integration/tiles/5-15-12.mvt
  test/integration/tiles/5-16-10.mvt
  test/integration/tiles/5-16-11.mvt
  test/integration/tiles/5-16-12.mvt
  test/integration/tiles/5-17-10.mvt
  test/integration/tiles/5-17-11.mvt
  test/integration/tiles/5-17-12.mvt
Labels: bug :lady_beetle:, skip changelog

#11515 Improve globe atmosphere rendering
  build/generate-struct-arrays.js
  src/data/array_types.js
  src/geo/projection/globe_util.js
  src/render/draw_globe_atmosphere.js
  src/shaders/globe_atmosphere.fragment.glsl
  src/shaders/globe_atmosphere.vertex.glsl
  src/terrain/globe_raster_program.js
  test/integration/render-tests/globe/globe-circle/change-projection/set-projection/expected.png
  test/integration/render-tests/globe/globe-circle/change-projection/set-style/expected.png
  test/integration/render-tests/globe/globe-circle/default-zoomed/expected.png
  test/integration/render-tests/globe/globe-circle/default/expected.png
  test/integration/render-tests/globe/globe-circle/horizontal/expected.png
  test/integration/render-tests/globe/globe-circle/near-horizon/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-map-scaled-map-aligned/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-map-scaled-viewport-aligned/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-viewport-scaled-map-aligned/expected.png
  test/integration/render-tests/globe/globe-circle/vertical-viewport-scaled-viewport-aligned/expected.png
  test/integration/render-tests/globe/globe-default/expected.png
  test/integration/render-tests/globe/globe-heatmap/default-zoomed/expected.png
  test/integration/render-tests/globe/globe-heatmap/default/expected.png
  test/integration/render-tests/globe/globe-heatmap/horizontal/expected.png
  test/integration/render-tests/globe/globe-heatmap/near-horizon/expected.png
  test/integration/render-tests/globe/globe-heatmap/vertical/expected.png
  test/integration/render-tests/globe/globe-horizon/expected.png
  test/integration/render-tests/globe/globe-symbols/collision-pitched-wrapped/expected.png
  test/integration/render-tests/globe/globe-symbols/globe-edge-clipping-allow-overlap/expected.png
  test/integration/render-tests/globe/globe-symbols/globe-edge-clipping/expected.png
  test/integration/render-tests/globe/globe-symbols/icon-allow-overlap/expected.png
  test/integration/render-tests/globe/globe-symbols/line-placement-terrain/expected.png
  test/integration/render-tests/globe/globe-symbols/map-text-rotation-alignment-map-terrain/expected.png
  test/integration/render-tests/globe/globe-symbols/text-allow-overlap/expected.png
  test/integration/render-tests/globe/globe-symbols/variable-anchor-icon/expected.png
  test/integration/render-tests/globe/globe-symbols/variable-anchor-text/expected.png
  test/integration/render-tests/globe/globe-terrain/expected.png
  test/integration/render-tests/globe/globe-transforms/high-lat-high-lng/expected.png
  test/integration/render-tests/globe/globe-transforms/low-lat-low-lng/expected.png
  test/integration/render-tests/globe/globe-transforms/mid-lat-mid-lng/expected.png
  test/integration/render-tests/globe/globe-transforms/north-pole-z0/expected.png
  test/integration/render-tests/globe/globe-transforms/north-pole/expected.png
  test/integration/render-tests/globe/globe-transforms/south-pole-z0/expected.png
  test/integration/render-tests/globe/globe-transition/show-unsupported-layer/expected.png
Labels: skip changelog

#11524 [Flow] Add missing export types to `ui/camera.js`
  src/geo/edge_insets.js
  src/ui/camera.js
Labels: skip changelog

#11528 [Flow] Add missing export types to `src/style/*`
  src/style-spec/feature_filter/index.js
  src/style/query_utils.js
  src/style/style_image.js
  src/style/style_layer.js
  src/style/style_layer/custom_style_layer.js
  src/style/terrain.js
  src/style/zoom_history.js
Labels: skip changelog

#11537 link to src/ui/default_locale.js source file
  src/ui/map.js
Labels: skip changelog

#11533 Prevent rays facing away from center to be counted as inside
  src/shaders/globe_atmosphere.fragment.glsl
Labels: bug :lady_beetle:, skip changelog

#11540 Cleanup popup close event listener
  src/ui/popup.js
  test/unit/ui/popup.test.js
Labels: bug :lady_beetle:

#11538 Switch style-spec scripts to native ESM
  .circleci/config.yml
  package.json
  src/style-spec/bin/gl-style-composite
  src/style-spec/bin/gl-style-composite.js
  src/style-spec/bin/gl-style-format.js
  src/style-spec/bin/gl-style-migrate
  src/style-spec/bin/gl-style-migrate.js
  src/style-spec/bin/gl-style-validate.js
  src/style-spec/build/.gitkeep
  src/style-spec/package.json
  src/style-spec/test.js
Labels: bug :lady_beetle:

#11461 Do not update camera zoom when DEM data isn't available yet
  src/geo/transform.js
  src/terrain/elevation.js
  src/ui/camera.js
  test/unit/geo/transform.test.js
  test/unit/terrain/terrain.test.js
Labels: bug :lady_beetle:

#11531 Reduce blurriness of draped line rendering
  src/render/draw_line.js
  src/render/program/line_program.js
  test/integration/render-tests/globe/globe-line/2x-pixelratio-lines/expected.png
  test/integration/render-tests/globe/globe-line/2x-pixelratio-lines/style.json
  test/integration/render-tests/terrain/2x-pixelratio-lines/expected.png
  test/integration/render-tests/terrain/2x-pixelratio-lines/style.json
Labels: bug :lady_beetle:

#11542 Skip tile clipping mask rendering if tile has no render data
  src/render/painter.js
Labels: performance :zap:, skip changelog

#11546 Only pass tile stencil drawing for greater values
  src/render/painter.js
  src/terrain/terrain.js
Labels: skip changelog

#11508 Tile cover optimization for globe
  build/generate-struct-arrays.js
  src/data/array_types.js
  src/data/pos_attributes.js
  src/geo/mercator_coordinate.js
  src/geo/projection/globe_util.js
  src/geo/projection/tile_transform.js
  src/geo/transform.js
  src/render/draw_debug.js
  src/render/program/debug_program.js
  src/render/program/program_uniforms.js
  src/source/tile.js
  test/integration/render-tests/globe/globe-fill-extrusion/opacity/expected.png
  test/integration/render-tests/globe/globe-transition/at-transition-zoom/expected.png
  test/integration/render-tests/globe/globe-transition/at-transition-zoom/style.json
  test/unit/geo/projection/globe.test.js
Labels: performance :zap:
