Repository mapbox/mapbox-gl-js, pull requests merged in 2022-03, with the labels that each got.

#11563 Simplifying marker rotation
  src/ui/marker.js
Labels: refactoring :building_construction:, skip changelog

#11564 Fix image source performance regression
  src/source/image_source.js
  src/util/browser.js
Labels: performance :zap:

#11572 Fix globe atmosphere not taking camera padding into account
  src/render/draw_globe_atmosphere.js
  test/ignores.json
Labels: skip changelog

#11547 Allow the second argument to 'in' expression to be an empty string
  src/style-spec/expression/definitions/in.js
  test/integration/expression-tests/in/basic-string/test.json
Labels: bug :lady_beetle:

#11530 Fix: #11516, #11041. Terrain: buildings on tile borders.
  src/data/bucket.js
  src/data/bucket/fill_extrusion_bucket.js
  src/render/draw_fill_extrusion.js
  test/ignores.json
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-gl-js#11516/expected.png
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-gl-js#11516/style.json
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-over-border-of-different-zoom-zoomin/expected.png
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-over-border-of-different-zoom-zoomin/style.json
  test/integration/render-tests/fill-extrusion-terrain/flat-roof-over-border-of-different-zoom/expected.png
  test/integration/tiles/15-5237-12668.mvt
  test/integration/tiles/15-5238-12669.mvt
  test/integration/tiles/15-5239-12668.mvt
  test/integration/tiles/mapbox.country-boundaries-v1/2-0-1.mvt
  test/integration/tiles/mapbox.country-boundaries-v1/2-0-2.mvt
  test/integration/tiles/mapbox.country-boundaries-v1/2-1-1.mvt
  test/integration/tiles/mapbox.country-boundaries-v1/2-1-2.mvt
Labels: bug :lady_beetle:, skip changelog

#11545 Rework globe controls
  flow-typed/gl-matrix.js
  src/geo/projection/globe.js
  src/geo/transform.js
  src/ui/camera.js
  src/ui/handler_manager.js
  test/unit/geo/projection/globe.test.js
  test/unit/ui/camera.test.js
  test/unit/ui/handler/scroll_zoom.test.js
Labels: skip changelog

#11568 Fix map.fitBounds() with non-zero bearing
  debug/padding.html
  src/ui/camera.js
  test/unit/ui/camera.test.js
Labels: bug :lady_beetle:

#11475 Fix fallback conditional for filter validation
  src/style-spec/validate/validate_expression.js
  test/unit/style-spec/expression.test.js
Labels: bug :lady_beetle:

#11529 [Flow] Add missing export types to `src/style-spec/validate/*`
  src/style-spec/.eslintrc
  src/style-spec/bin/gl-style-composite.js
  src/style-spec/bin/gl-style-format.js
  src/style-spec/bin/gl-style-migrate.js
  src/style-spec/bin/gl-style-validate.js
  src/style-spec/reference/latest.js
  src/style-spec/validate/validate.js
  src/style-spec/validate/validate_array.js
  src/style-spec/validate/validate_boolean.js
  src/style-spec/validate/validate_color.js
  src/style-spec/validate/validate_enum.js
  src/style-spec/validate/validate_filter.js
  src/style-spec/validate/validate_fog.js
  src/style-spec/validate/validate_formatted.js
  src/style-spec/validate/validate_function.js
  src/style-spec/validate/validate_glyphs_url.js
  src/style-spec/validate/validate_image.js
  src/style-spec/validate/validate_layer.js
  src/style-spec/validate/validate_layout_property.js
  src/style-spec/validate/validate_light.js
  src/style-spec/validate/validate_number.js
  src/style-spec/validate/validate_object.js
  src/style-spec/validate/validate_paint_property.js
  src/style-spec/validate/validate_projection.js
  src/style-spec/validate/validate_property.js
  src/style-spec/validate/validate_source.js
  src/style-spec/validate/validate_string.js
  src/style-spec/validate/validate_terrain.js
  src/style-spec/validate_style.min.js
  test/unit/style-spec/fixture/functions.output-api-supported.json
  test/unit/style-spec/fixture/functions.output.json
Labels: skip changelog

#11493 Calculate correct canvas size if more than one parent container has a css transform property
  debug/canvas-size.html
  src/ui/map.js
Labels: bug :lady_beetle:

#11574 Remove redundant manual testing pages and add gestures testing page
  debug/3d-playground.html
  debug/extrusion-query.html
  debug/featurestate.html
  debug/fog.html
  debug/markers.html
  debug/scroll_zoom_blocker.html
  debug/video.html
  test/release/3d-playground.html
  test/release/canvas-size.html
  test/release/fog-demo.html
  test/release/fog.html
  test/release/index.js
  test/release/skybox-gradient.html
Labels: testing :100:, skip changelog

#11391 Adding render tests for image fallback with feature constant expressions and `addImage` operation
  test/integration/render-tests/image-fallback-nested/add-image/expected.png
  test/integration/render-tests/image-fallback-nested/add-image/style.json
  test/integration/render-tests/image-fallback-nested/constant/available/expected.png
  test/integration/render-tests/image-fallback-nested/constant/available/style.json
  test/integration/render-tests/image-fallback-nested/constant/missing/expected.png
  test/integration/render-tests/image-fallback-nested/constant/missing/style.json
  test/integration/render-tests/image-fallback-nested/feature-state/add-image/expected.png
  test/integration/render-tests/image-fallback-nested/feature-state/add-image/style.json
  test/integration/render-tests/image-fallback-nested/feature-state/inside/expected.png
  test/integration/render-tests/image-fallback-nested/feature-state/inside/style.json
  test/integration/render-tests/image-fallback-nested/feature-state/outside/expected.png
  test/integration/render-tests/image-fallback-nested/feature-state/outside/style.json
Labels: skip changelog

#11581 Automate NPM publish through CodeBuild
  build/diff-tarball.js
  build/publish.sh
  buildspec.yml
  package.json
  src/style-spec/package.json
  test/unit/changelog.js
  yarn.lock
Labels: skip changelog

#11580 fix: update ImageAtlas render callbacks after image removal
  src/render/image_atlas.js
  src/render/image_manager.js
Labels: bug :lady_beetle:

#11578 Fix camera under terrain when exaggeration changes
  debug/fog.html
  src/geo/transform.js
  src/ui/map.js
  test/integration/render-tests/terrain/decrease-exaggeration-fog/expected.png
  test/integration/render-tests/terrain/decrease-exaggeration-fog/style.json
  test/integration/render-tests/terrain/increase-exaggeration/expected.png
  test/integration/render-tests/terrain/increase-exaggeration/style.json
  test/unit/geo/projection/globe.test.js
  test/unit/geo/transform.test.js
Labels: bug :lady_beetle:

#11588 Fix regressions and expand test coverage for projection transitions
  src/style/style.js
  src/ui/map.js
  test/integration/render-tests/globe/globe-symbols/set-style/expected.png
  test/integration/render-tests/globe/globe-symbols/set-style/style.json
  test/integration/render-tests/map-projections/albers/rotation-correction-flip/expected.png
  test/integration/render-tests/map-projections/albers/rotation-correction-flip/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/globe-to-mercator/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/globe-to-mercator/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/globe-to-winkel-tripel/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/globe-to-winkel-tripel/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/null-default/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/null-default/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-albers/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-albers/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-globe/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-globe/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-raster/expected.png
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-raster/style.json
  test/integration/render-tests/map-projections/integrations/set-style/albers/expected.png
  test/integration/render-tests/map-projections/integrations/set-style/albers/style.json
  test/integration/render-tests/map-projections/integrations/set-style/equirectangular/expected.png
  test/integration/render-tests/map-projections/integrations/set-style/equirectangular/style.json
  test/integration/render-tests/map-projections/integrations/set-style/globe/expected.png
  test/integration/render-tests/map-projections/integrations/set-style/globe/style.json
  test/integration/render-tests/map-projections/integrations/set-style/lambert/expected.png
  test/integration/render-tests/map-projections/integrations/set-style/lambert/style.json
  test/integration/tiles/mapbox.mapbox-streets-v8/0-0-0.mvt
  test/unit/style/style.test.js
  test/unit/ui/map.test.js
Labels: bug :lady_beetle:, release blocker :no_entry:, skip changelog, 3d :triangular_ruler:

#11560 Globe view further optimizations
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/render/program/program_uniforms.js
  src/shaders/_prelude.glsl
  src/shaders/globe_raster.vertex.glsl
  src/source/tile.js
  src/terrain/draw_terrain_raster.js
  src/terrain/globe_raster_program.js
  src/terrain/terrain.js
Labels: performance :zap:, 3d :triangular_ruler:

#11600 [Flow] Add missing export types to style-spec/expression/definitions/*
  src/style-spec/expression/definitions/assertion.js
  src/style-spec/expression/definitions/at.js
  src/style-spec/expression/definitions/case.js
  src/style-spec/expression/definitions/coalesce.js
  src/style-spec/expression/definitions/coercion.js
  src/style-spec/expression/definitions/collator.js
  src/style-spec/expression/definitions/comparison.js
  src/style-spec/expression/definitions/format.js
  src/style-spec/expression/definitions/image.js
  src/style-spec/expression/definitions/in.js
  src/style-spec/expression/definitions/index_of.js
  src/style-spec/expression/definitions/interpolate.js
  src/style-spec/expression/definitions/length.js
  src/style-spec/expression/definitions/let.js
  src/style-spec/expression/definitions/literal.js
  src/style-spec/expression/definitions/match.js
  src/style-spec/expression/definitions/number_format.js
  src/style-spec/expression/definitions/slice.js
  src/style-spec/expression/definitions/step.js
  src/style-spec/expression/definitions/var.js
  src/style-spec/expression/expression.js
Labels: skip changelog

#11602 [Flow] Add missing export types to style-spec/expression/definitions/*
  src/style-spec/expression/definitions/assertion.js
  src/style-spec/expression/definitions/at.js
  src/style-spec/expression/definitions/case.js
  src/style-spec/expression/definitions/coalesce.js
  src/style-spec/expression/definitions/coercion.js
  src/style-spec/expression/definitions/collator.js
  src/style-spec/expression/definitions/comparison.js
  src/style-spec/expression/definitions/format.js
  src/style-spec/expression/definitions/image.js
  src/style-spec/expression/definitions/in.js
  src/style-spec/expression/definitions/index_of.js
  src/style-spec/expression/definitions/interpolate.js
  src/style-spec/expression/definitions/length.js
  src/style-spec/expression/definitions/let.js
  src/style-spec/expression/definitions/literal.js
  src/style-spec/expression/definitions/match.js
  src/style-spec/expression/definitions/number_format.js
  src/style-spec/expression/definitions/slice.js
  src/style-spec/expression/definitions/step.js
  src/style-spec/expression/definitions/within.js
  src/style-spec/expression/evaluation_context.js
  src/style-spec/expression/expression.js
  src/style-spec/expression/index.js
Labels: skip changelog

#11603 [Flow] Add missing export types to map.js & style.js
  src/style/style.js
  src/ui/map.js
  src/ui/marker.js
  src/util/ajax.js
Labels: skip changelog

#11619 Disables cooperative gestures when map is fullscreen in Safari
  src/ui/handler/scroll_zoom.js
  test/unit/ui/handler/scroll_zoom.test.js
Labels: bug :lady_beetle:, environment-specific :desktop_computer:

#11615 Disables antialias for 15.4/15.5 iOS and M1 devices and provides a console warning
  src/ui/map.js
  src/util/util.js
  test/unit/util/util.test.js
Labels: bug :lady_beetle:, environment-specific :desktop_computer:, release blocker :no_entry:

#11621 update version number and changelog
  CHANGELOG.md
  package.json
Labels: skip changelog

#11622 update changelog for v2.7.1
  CHANGELOG.md
Labels: skip changelog

#11608 Add custom-raster tile source
  debug/custom-source.html
  src/source/custom_source.js
  src/source/raster_tile_source.js
  src/source/source.js
  src/source/source_cache.js
  src/source/tile.js
  test/integration/lib/operation-handlers.js
  test/integration/render-tests/custom-source/albers/expected.png
  test/integration/render-tests/custom-source/albers/style.json
  test/integration/render-tests/custom-source/equal-earth/expected.png
  test/integration/render-tests/custom-source/equal-earth/style.json
  test/integration/render-tests/custom-source/equirectangular/expected.png
  test/integration/render-tests/custom-source/equirectangular/style.json
  test/integration/render-tests/custom-source/lambert/expected.png
  test/integration/render-tests/custom-source/lambert/style.json
  test/integration/render-tests/custom-source/natural-earth/expected.png
  test/integration/render-tests/custom-source/natural-earth/style.json
  test/integration/render-tests/custom-source/satellite/expected.png
  test/integration/render-tests/custom-source/satellite/style.json
  test/integration/render-tests/custom-source/terrain/expected.png
  test/integration/render-tests/custom-source/terrain/style.json
  test/integration/render-tests/custom-source/winkel-tripel/expected.png
  test/integration/render-tests/custom-source/winkel-tripel/style.json
  test/unit/source/custom_source.test.js
  test/unit/source/source_cache.test.js
Labels: feature :green_apple:

#11585 update dev versions
  package.json
  src/style-spec/package.json
Labels: skip changelog

#11631 disable globe view for 2.8.0
  debug/3d-playground.html
  debug/circles.html
  debug/globe-fill-extrusion.html
  debug/projections.html
  debug/terrain-debug.html
  src/geo/projection/index.js
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  src/ui/map.js
  test/integration/lib/render.js
  test/unit/geo/projection/far_z.test.js
  test/unit/geo/projection/globe.test.js
  test/unit/ui/camera.test.js
  test/unit/ui/handler/scroll_zoom.test.js
  test/unit/ui/map.test.js
Labels: skip changelog

#11634 Fix style spec and gl js versions
  package.json
  src/style-spec/package.json
Labels: skip changelog

#11636 Updating changelogs to include v2.8.0-beta.1
  CHANGELOG.md
  src/style-spec/CHANGELOG.md
Labels: skip changelog

#11645 Increase diff threshold for terrain/wireframe render test
  test/integration/render-tests/terrain/wireframe/style.json
Labels: skip changelog

#11648 Update dependencies and move minimist to devDependencies
  .stylelintrc
  package.json
  src/css/mapbox-gl.css
  src/util/window.js
  test/build/browserify-test-fixture.js
  test/build/style-spec.test.js
  test/unit/ui/handler/scroll_zoom.test.js
  test/unit/util/tile_request_cache.test.js
  test/util/test.js
  yarn.lock
Labels: skip changelog

#11556 Globe view marker support
  debug/markers.html
  flow-typed/gl-matrix.js
  src/geo/projection/far_z.js
  src/geo/projection/globe_util.js
  src/geo/projection/projection.js
  src/geo/transform.js
  src/ui/map.js
  src/ui/marker.js
  src/ui/popup.js
  test/unit/ui/marker.test.js
Labels: skip changelog, 3d :triangular_ruler:

#11651 Add github actions workflow to check changelog requirements in PR
  .github/actions/check-changelog/action.yml
  .github/actions/check-changelog/index.js
  .github/actions/package.json
  .github/actions/yarn.lock
  .github/workflows/pull-request-requirements.yml
Labels: skip changelog

#11655 Use cached globe matrix
  src/geo/projection/globe_util.js
Labels: performance :zap:, 3d :triangular_ruler:

#11653 Add `synchronize` to check-changelog github action types
  .github/workflows/pull-request-requirements.yml
Labels: skip changelog

#11657 fix map center calculation in ScaleControl
  src/ui/control/scale_control.js
  test/unit/ui/control/scale.test.js
Labels: bug :lady_beetle:
