Repository mapbox/mapbox-gl-js, pull requests merged in 2022-12, with the labels that each got.

#12427 Fix distance-to-center filtering of symbols when terrain is enabled
  src/geo/transform.js
  src/ui/free_camera.js
  test/integration/render-tests/terrain/symbol-distance-from-center/expected.png
  test/integration/render-tests/terrain/symbol-distance-from-center/style.json
Labels: skip changelog

#12428 Clean up test folders slightly
  test/fixtures/expected/text-shaping-default.json
  test/fixtures/expected/text-shaping-images-horizontal.json
  test/fixtures/expected/text-shaping-images-vertical.json
  test/fixtures/expected/text-shaping-linebreak.json
  test/fixtures/expected/text-shaping-newline.json
  test/fixtures/expected/text-shaping-newlines-in-middle.json
  test/fixtures/expected/text-shaping-null.json
  test/fixtures/expected/text-shaping-spacing.json
  test/fixtures/expected/text-shaping-zero-width-space.json
  test/integration/data/anchors.json
  test/integration/data/point.json
  test/integration/render-tests/icon-image/stretchable-content/style.json
  test/integration/render-tests/icon-image/stretchable/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor-1x-image-2x-screen/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor-2x-image-1x-screen/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor-2x-image-2x-screen/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor-icon-anchor/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor-icon-offset/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor-padding/style.json
  test/integration/render-tests/icon-text-fit/both-text-anchor/style.json
  test/integration/render-tests/icon-text-fit/height-text-anchor-padding/style.json
  test/integration/render-tests/icon-text-fit/height-text-anchor/style.json
  test/integration/render-tests/icon-text-fit/stretch-fifteen-part/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-@2x/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-content-collision/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-content/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-just-height/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part-just-width/style.json
  test/integration/render-tests/icon-text-fit/stretch-nine-part/style.json
  test/integration/render-tests/icon-text-fit/stretch-three-part/style.json
  test/integration/render-tests/icon-text-fit/stretch-two-part/style.json
  test/integration/render-tests/icon-text-fit/stretch-underscale/style.json
  test/integration/render-tests/icon-text-fit/width-text-anchor-padding/style.json
  test/integration/render-tests/icon-text-fit/width-text-anchor/style.json
  test/integration/render-tests/runtime-styling/set-style-source-add-geojson-url/style.json
  test/integration/render-tests/runtime-styling/source-add-geojson-url/style.json
  test/integration/video/0.png
  test/unit/symbol/shaping.test.js
Labels: skip changelog

#12430 Update dependencies where possible
  package.json
  yarn.lock
Labels: skip changelog

#11692 Add localization for UI strings in Czech
  src/ui/locales/cs.js
Labels: skip changelog

#12444 bump to v2.11.1
  CHANGELOG.md
  package.json
Labels: skip changelog

#12435 Add missing precision qualifiers to shader uniforms
  src/shaders/_prelude_lighting.glsl
Labels: skip changelog

#12448 Add optional spec parameter to `validateMapboxApiSupported`
  src/style-spec/validate_mapbox_api_supported.js
  test/unit/style-spec/validate_mapbox_api_supported.test.js
Labels: skip changelog

#12449 Derive source type values from spec
  src/style-spec/validate/validate_source.js
Labels: skip changelog

#12451 Update URLs in help messages for access token documentation
  src/util/ajax.js
  src/util/mapbox.js
  test/unit/util/ajax.test.js
Labels: skip changelog

#12453 Release `style-spec` v13.28.0-beta.1
  src/style-spec/CHANGELOG.md
  src/style-spec/package.json
Labels: skip changelog

#12436 Refactor render tests
  test/integration/lib/operation-handlers.js
  test/integration/lib/render.js
  test/integration/lib/server.js
  test/integration/render-tests/dynamic-filter/symbols/line/combined-pitch-distance-data-driven/early-dynamic-high-pitch/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/combined-pitch-distance-data-driven/early-dynamic-low-pitch/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/combined-pitch-distance-data-driven/late-dynamic/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/combined-pitch-distance/high-pitch-far-hidden/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/combined-pitch-distance/low-pitch-far-visible/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/distance-far-cull/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/distance-near-and-far-cull/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/distance-near-cull/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/distance-nofilter/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/pitch-high-cull/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/pitch-high-show/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/pitch-low-cull/style.json
  test/integration/render-tests/dynamic-filter/symbols/line/pitch-low-show/style.json
  test/util/html_generator.js
Labels: skip changelog

#12392 Add cached request count to live performance counters
  src/util/config.js
  src/util/live_performance.js
  src/util/mapbox.js
  test/unit/util/mapbox.test.js
Labels: skip changelog

#12354 Alternate zoom with terrain
  src/geo/transform.js
  src/render/painter.js
  src/terrain/terrain.js
  src/ui/handler/keyboard.js
  src/ui/handler_manager.js
  src/ui/map.js
  test/integration/render-tests/debug/terrain/camera-collides-with-terrain/expected.png
  test/integration/render-tests/debug/terrain/camera-collides-with-terrain/style.json
  test/integration/render-tests/debug/terrain/camera-under-terrain/expected.png
  test/integration/render-tests/terrain/buildings-on-raster/expected.png
  test/unit/geo/transform.test.js
  test/unit/terrain/terrain.test.js
Labels: bug :lady_beetle:

#12463 Update allowed for camera under terrain render test
  test/integration/render-tests/debug/terrain/camera-under-terrain/style.json
Labels: skip changelog

#12461 Fix line-border-color with line-trim-offset
  src/shaders/line.fragment.glsl
Labels: bug :lady_beetle:

#12466 Update changelog and versions for v2.12-beta.1
  CHANGELOG.md
  package.json
  src/style-spec/package.json
Labels: skip changelog

#12462 Reuse more work in render tests on Windows
  .circleci/config.yml
  test/integration/testem/testem.js
Labels: skip changelog

#12468 Fix workflows for CI deploy jobs
  .circleci/config.yml
Labels: skip changelog

#12404 Use RAM disks in CircleCI
  .circleci/config.yml
  package.json
Labels: skip changelog

#12469 Remove redundant `@babel/preset-flow`
  .eslintrc
  package.json
  yarn.lock
Labels: skip changelog

#12472 Remove unnecessary attribute in terrain related rendering code.
  src/shaders/ground_shadow.vertex.glsl
  src/shaders/terrain_depth.vertex.glsl
  src/shaders/terrain_raster.vertex.glsl
  src/terrain/terrain.js
Labels: performance :zap:

#12454 Reduce flakiness in the render tests
  .circleci/config.yml
  package.json
  src/util/ajax.js
  test/browser/util/browser.js
  test/integration/lib/middlewares.cjs
  test/integration/lib/operation-handlers.js
  test/integration/lib/render.js
  test/integration/lib/server.js
  test/integration/testem/testem.js
  test/integration/tilesets/mapbox.mapbox-streets-v7
  test/integration/tilesets/mapbox.satellite
  test/integration/tilesets/raster.json
  test/integration/tilesets/vector.json
  test/util/html_generator.js
  yarn.lock
Labels: skip changelog

#12488 Fix #12450
  src/geo/transform.js
  src/ui/camera.js
  test/unit/geo/transform.test.js
  test/unit/ui/camera.test.js
Labels: bug :lady_beetle:
