Repository mapbox/mapbox-gl-js, pull requests merged in 2023-04, with the labels that each got.

#12642 Update package version and the CHANGELOG for the 2.14.0-beta.1 release
  CHANGELOG.md
  package.json
Labels: skip changelog

#12643 Bump dev version
  CHANGELOG.md
  package.json
Labels: skip changelog

#12644 Including spaces between Magnitude and Unit in Scale Control Formatting
  src/ui/control/scale_control.js
Labels: bug :lady_beetle:

#12655 v2.14.0
  CHANGELOG.md
  package.json
Labels: skip changelog

#12658 Forbid class fields to fix transpilation errors with Vite/ESBuild
  .eslintrc
  src/style/style_layer/line_style_layer.js
  test/unit/util/util.test.js
Labels: bug :lady_beetle:

#12661 v2.14.1
  .eslintrc
  CHANGELOG.md
  package.json
  src/style/style_layer/line_style_layer.js
  test/unit/util/util.test.js
Labels: skip changelog

#12668 [MAPS3D-785] fill-extrusion-rounded-roof
  src/render/draw_fill_extrusion.js
  src/style-spec/reference/v8.json
  src/style-spec/types.js
  src/style/style_layer/fill_extrusion_style_layer_properties.js
  test/integration/render-tests/fill-extrusion-base/rounded-edge-flat-roof-ao/expected.png
  test/integration/render-tests/fill-extrusion-base/rounded-edge-flat-roof-ao/style.json
Labels: feature :green_apple:

#12669 Improve performance of symbol layers with identical or no text
  debug/symbols-generated.html
  flow-typed/kdbush.js
  package.json
  src/render/painter.js
  src/symbol/cross_tile_symbol_index.js
  test/unit/symbol/cross_tile_symbol_index.js
Labels: performance :zap:

#12671 Fix inconsistency removeFeatureState docs #12612
  src/ui/map.js
Labels: docs :scroll:, skip changelog
