Repository mapbox/mapbox-gl-js, pull requests merged in 2023-01, with the labels that each got.

#12500 Cherry-pick for v2.12.0 final
  test/integration/render-tests/debug/terrain/camera-under-terrain/style.json
Labels: skip changelog

#12501 v2.12.0 final
  CHANGELOG.md
  package.json
  src/style-spec/package.json
Labels: skip changelog

#12502 Update for next release cycle
  CHANGELOG.md
  package.json
  src/style-spec/package.json
Labels: skip changelog

#12499 update license
  LICENSE.txt
  README.md
Labels: skip changelog

#12509 Fix `test-browser` failures by unpinning chrome version
  .circleci/config.yml
Labels: testing :100:, skip changelog

#12508 Adding CircleCI render test run on MacOS Safari
  .circleci/config.yml
  package.json
  test/ignores/linux-firefox.js
  test/ignores/mac-chrome.js
  test/ignores/mac-safari.js
  test/ignores/windows-chrome.js
  test/integration/lib/generate-fixture-json.js
  test/integration/lib/render.js
  test/integration/render-tests/fog/2d/fill-extrusion-pattern/style.json
  test/integration/render-tests/fog/switch-style-disable/style.json
  test/integration/render-tests/fog/switch-style-reset-defaults/style.json
  test/integration/render-tests/globe/globe-antialiasing/high-exaggeration/style.json
  test/integration/render-tests/globe/globe-camera/reset-north/style.json
  test/integration/render-tests/globe/globe-circle/change-projection/set-projection/style.json
  test/integration/render-tests/globe/globe-circle/change-projection/set-style/style.json
  test/integration/render-tests/globe/globe-circle/near-transition/style.json
  test/integration/render-tests/globe/globe-heatmap/near-transition/style.json
  test/integration/render-tests/globe/globe-horizon/style.json
  test/integration/render-tests/globe/globe-padding/style.json
  test/integration/render-tests/globe/globe-rotate-to/style.json
  test/integration/render-tests/globe/globe-set-style/albers-globe-toggle/style.json
  test/integration/render-tests/globe/globe-set-style/default/style.json
  test/integration/render-tests/globe/globe-set-style/raster/style.json
  test/integration/render-tests/globe/globe-set-style/symbol/style.json
  test/integration/render-tests/globe/globe-symbols/globe-edge-clipping-allow-overlap/style.json
  test/integration/render-tests/globe/globe-symbols/globe-edge-clipping/style.json
  test/integration/render-tests/globe/globe-symbols/icon-allow-overlap/style.json
  test/integration/render-tests/globe/globe-symbols/set-style/style.json
  test/integration/render-tests/globe/globe-symbols/text-allow-overlap/style.json
  test/integration/render-tests/globe/globe-transforms/high-lat-high-lng/style.json
  test/integration/render-tests/globe/globe-transforms/mid-lat-mid-lng/style.json
  test/integration/render-tests/globe/globe-transforms/north-pole-padded-dem/style.json
  test/integration/render-tests/globe/globe-transforms/south-pole-padded-dem/style.json
  test/integration/render-tests/globe/globe-transition/ocean-artifact/style.json
  test/integration/render-tests/globe/globe-transition/pitch/expected.png
  test/integration/render-tests/globe/globe-transition/pitch/style.json
  test/integration/render-tests/globe/globe-transition/show-unsupported-layer/expected.png
  test/integration/render-tests/globe/globe-transition/tile-corners-outside/style.json
  test/integration/render-tests/globe/globe-transition/tile-edges/style.json
  test/integration/render-tests/globe/globe-transition/transition-fill/style.json
  test/integration/render-tests/globe/globe-zoom-visibility/tiles-consistent/style.json
  test/integration/render-tests/line-dasharray/case/round/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/null-fallback-globe/style.json
  test/integration/render-tests/map-projections/integrations/set-projection/set-projection-precedence-fallback/style.json
  test/integration/testem/testem.js
Labels: skip changelog

#12442 security: update minimist and geojson-rewind to avoid CVE-2021-44906
  package.json
  yarn.lock
Labels: skip changelog

#12528 Increase render tests start delay for Safari
  test/integration/testem/testem.js
Labels: skip changelog

#12514 WebGL2 support
  .circleci/config.yml
  build/rollup_plugins.js
  debug/terrain-debug.html
  src/gl/context.js
  src/render/draw_fill_extrusion.js
  src/render/draw_heatmap.js
  src/render/painter.js
  src/render/program.js
  src/shaders/_prelude.fragment.glsl
  src/shaders/_prelude.vertex.glsl
  src/ui/map.js
  test/integration/README.md
  test/integration/lib/render.js
Labels: skip changelog

#12530 Upgrade Flow to v0.152.0
  .flowconfig
  package.json
  src/gl/framebuffer.js
  src/gl/index_buffer.js
  src/gl/value.js
  src/gl/vertex_buffer.js
  src/render/painter.js
  src/render/program.js
  src/render/texture.js
  src/source/custom_source.js
  src/source/geojson_source.js
  src/source/image_source.js
  src/source/raster_tile_source.js
  src/source/tile.js
  src/source/vector_tile_source.js
  src/terrain/terrain.js
  src/util/tile_request_cache.js
  yarn.lock
Labels: skip changelog

#12182 Custom layer immediate and draped rendering on globe and terrain
  debug/color-earth-custom-layer.js
  debug/custom-layer-globe.html
  debug/satellites-custom-layer.js
  debug/space-track-leo.txt
  src/geo/lng_lat.js
  src/geo/mercator_coordinate.js
  src/geo/projection/globe.js
  src/geo/projection/globe_util.js
  src/geo/transform.js
  src/render/draw_custom.js
  src/render/painter.js
  src/style/style.js
  src/style/style_layer/custom_style_layer.js
  src/terrain/terrain.js
  test/integration/custom_layer_implementations.js
  test/integration/render-tests/custom-layer-js/draped/expected.png
  test/integration/render-tests/custom-layer-js/draped/style.json
Labels: feature :green_apple:, skip changelog

#12539 remove redundant call to prerender from old code, some review fixes
  src/geo/lng_lat.js
  src/geo/projection/globe_util.js
  src/render/draw_custom.js
Labels: skip changelog

#12510 Clear tiles with zoom dependent `line-width` layers from the terrain render cache
  src/style/style_layer/line_style_layer.js
  src/terrain/terrain.js
Labels: bug :lady_beetle:

#12541 Increase "allowed" value for `custom-layer-js/draped` render test
  test/integration/render-tests/custom-layer-js/draped/style.json
Labels: skip changelog

#12543 Fix map pan speed while pinching in
  src/ui/handler_manager.js
Labels: bug :lady_beetle:

#12398 Add missing queryTerrainElevation to docs
  src/ui/camera.js
Labels: docs :scroll:, skip changelog

#12542 Update CircleCI Orbs
  .circleci/config.yml
Labels: skip changelog

#12544 fix discontinuity when transitioning from globe to mercator in custom layer example
  debug/satellites-custom-layer.js
  src/geo/transform.js
  src/render/draw_custom.js
  src/style/style_layer/custom_style_layer.js
Labels: release blocker :no_entry:, skip changelog
